### ISSUE TITLE
VolatilityQuotingStrategy неправильно вычисляет цену заявки

### ISSUE THREAD

**Issue by Sergey-Dvortsov** [StockSharp/StockSharp#101]
Quik 6.17.1.17, s# 4.3.6.0 

VolatilityQuotingStrategy неправильно вычисляет цену заявки - всегда возвращает 0..

код теста:

namespace VolatilityQuotingTest
{
    class Program
    {
        private static Connector _trader;
       private static AutoResetEvent reset = new AutoResetEvent(false);
        static void Main(string[] args)
        {
            string _securityID = "SR7500BF5@FORTS";
            string _portfolioName = "22921";
            Portfolio _portfolio = null;
            Security _security = null;
            Range<decimal> _volRange = new Range<decimal>(31, 34);
            decimal _volume = 1;
            Sides _direction = Sides.Buy;
            LogManager _log = new StockSharp.Logging.LogManager();
            _log.Listeners.Add(new DebugLogListener());
            _trader = new QuikTrader();
            _log.Sources.Add(_trader);

            _trader.NewSecurities += securities =>
            {
                foreach (Security security in securities)
                {
                    if (security.Id == _securityID)
                    {
                        _security = security;
                        Debug.WriteLine("Получен инструмент: " + security.Id);
                        if (_portfolio != null)
                        {
                            reset.Set();
                        }
                    }
                }
            };

            _trader.NewPortfolios += portfolios =>
            {
                foreach (Portfolio portfolio in portfolios)
                {
                    if (portfolio.Name == _portfolioName)
                    {
                        _portfolio = portfolio;
                        Debug.WriteLine("Получен портфельт: " + portfolio.Name);
                        if (_security != null)
                        {
                            reset.Set();
                        }
                    }
                }
            };
           
            _trader.Connected += () =>
            {
                Debug.WriteLine("Соединение установлено");
            };

            _trader.Disconnected += () =>
            {
                _trader.Dispose();
            };

            _trader.Connect();

            reset.WaitOne();

            try
            {
                VolatilityQuotingStrategy strategy = new VolatilityQuotingStrategy(_direction, _volume, _volRange)
                {
                    Connector = _trader,
                    Security = _security,
                    Portfolio = _portfolio
                };

                _log.Sources.Add(strategy);
                strategy.Start();
            }
            catch (Exception ex)
            {
               Debug.WriteLine(ex.Message + " " + ex.StackTrace);
            }
            Console.Read();
        }
    }
}

Лог:

VolatilityQuotingTest.vshost.exe Information: 0 : QuikTrader Connect
VolatilityQuotingTest.vshost.exe Information: 0 : QuikTrader Создан новый портфель SPBFUT00FJA.
VolatilityQuotingTest.vshost.exe Information: 0 : VQS_SR7500BF5@FORTS_22921 Стратегия Запущена. [0,-1]. Позиция 0.
VolatilityQuotingTest.vshost.exe Information: 0 : VQS_SR7500BF5@FORTS_22921 Котирование на Buy объема 1.
VolatilityQuotingTest.vshost.exe Information: 0 : VQS_SR7500BF5@FORTS_22921 Цена текущей NULL и лучшей 0.
VQS_SR7500BF5@FORTS_22921 Лучший бид 176 и лучший аск 186.
VQS_SR7500BF5@FORTS_22921 Регистрация новой Limit (0x2BDDEF8) заявки на Buy с ценой 0 и объемом 1. 
QuikTrader RegisterOrder: 0/ Покупка Цена=0 Объем=1 Сост=None Бал=0 
VolatilityQuotingTest.vshost.exe Error: 0 : QuikTrader System.InvalidOperationException: Сообщение 'Execution,T(L)=2015/05/25 16:30:17.798,T(S)=2015/05/25 16:30:17.798,(Order),Sec=S#:SR7500BF5@FORTS, Native:,Type:Option,Ord=/0/0,Fail=System.ArgumentException: Цена лимитной заявки не может быть равной 0.
Имя параметра: order
   в StockSharp.Algo.Connector.ChechOrderState(Order order)
   в StockSharp.Algo.Connector.CheckOnNew(Order order, Boolean checkVolume, Boolean checkTransactionId)
   в StockSharp.Algo.Connector.RegisterOrder(Order order, Boolean initOrder),TId=,Pf=22921,TPrice=,UId=' привело к ошибке обработки. ---> System.ArgumentOutOfRangeException: Идентификатор транзакции должен быть отличен от нуля.
Имя параметра: message
Фактическое значение было 0.
   в StockSharp.Algo.EntityCache.ProcessOrderFailMessage(Security security, ExecutionMessage message)
   в StockSharp.Algo.Connector.ProcessOrderMessage(Security security, ExecutionMessage message)
   в StockSharp.Algo.Connector.<>c__DisplayClass59.<ProcessExecutionMessage>b__50(Security security)
   в StockSharp.Algo.Connector.<>c__DisplayClass59.<ProcessExecutionMessage>b__52(Security s, ExecutionMessage m)
   в StockSharp.Algo.Connector.ProcessSecurityAction[TMessage](TMessage message, Func`2 getId, Action`2 action, Boolean ignoreIfNotExist, String associatedBoard)
   в StockSharp.Algo.Connector.ProcessExecutionMessage(ExecutionMessage message)
   в StockSharp.Algo.Connector.OnProcessMessage(Message message, MessageDirections direction)
   --- Конец трассировки внутреннего стека исключений ---

**Comment by mikasoukhov** [comment]
Нужно под дебагом https://github.com/StockSharp/StockSharp/blob/master/Algo/Derivatives/DerivativesHelper.cs#L722 поставить точку останова, и сказать, какие значения приводят к нулевому результату.

**Comment by Sergey-Dvortsov** [comment]
![premium_locals](https://cloud.githubusercontent.com/assets/10364235/7808848/cc98b390-039e-11e5-857b-12c4af225862.png)
