### ISSUE TITLE
Неправильная цена сделки RTS (дробное число) при тестировании на истории

### ISSUE THREAD

**Issue by ingler-ok** [StockSharp/StockSharp#106]
Пишу исторические данные с Квика версии 6.17, т.к. нужны миллисекунды.
Версия библиотеки 4.3.6.
Работаю с фьючерсом на индекс РТС.

Шаг цены указываю равным 10. 
<pre>
...
var level1Info = new Level1ChangeMessage
            {
                SecurityId = selected_security.ToSecurityId(),
                ServerTime = startTime,
            }
            .TryAdd(Level1Fields.PriceStep, 10m)
            .TryAdd(Level1Fields.StepPrice, 10m)
            .TryAdd(Level1Fields.MinPrice, 10m)
            .TryAdd(Level1Fields.MaxPrice, 1000000m)
            .TryAdd(Level1Fields.MarginBuy, 10000m)
            .TryAdd(Level1Fields.MarginSell, 10000m);
...
</pre>

Сообщение о комисси закоментировано. 

Сделки и стакан реальные, загружаются успешно:
<pre>
...
connector.RegisterMarketDepth(selected_security);
connector.RegisterOrderLog(selected_security);
connector.RegisterTrades(selected_security);
....
FileAccess (Load): C:\Program Files (x86)\Hydra\R\RIM5@FORTS\2015_05_25\quotes.bin
FileAccess (Load): C:\Program Files (x86)\Hydra\R\RIM5@FORTS\2015_05_25\trades.bin
</pre>

В Гидре цены в стакане имеют знаки после запятой, но нули:
![image](https://cloud.githubusercontent.com/assets/12250965/7898001/e7de5092-06fa-11e5-99b5-db07d2eaebee.png)

Сами сделки при этом записаны правильно, без нулей:
![image](https://cloud.githubusercontent.com/assets/12250965/7898015/7e9e43b6-06fb-11e5-9ca0-fad99fbb5f29.png)

Однако, при работе, сделки проходят с неправильной ценой, такой как <b>103539,98</b>

Фрагмент лог файла стратегии:
<pre>
2015/05/25 15:45:00.206|       |WS_RIM5@FORTS_Тестовый портфель|Новая Sell сделка 30 по цене <b>103539,98</b> на 1 заявки 37.
2015/05/25 15:45:00.206|       |WS_RIM5@FORTS_Тестовый портфель|Заявка 37 (0xE40D4D) больше не активна.
</pre>

**Comment by mikasoukhov** [comment]
На примере с выложенными данными ошибка воспроизводится?

**Comment by ingler-ok** [comment]
Ишью, наверное, можно закрыть. Ошибка на примере SS ( – SampleHistoryTesting) не воспроизвелась. Начал искать у себя в коде. Оказалось, что для решения проблемы нужно было прописать в создаваемом инструменте поле:
<pre>
PriceStep = 10 //шаг цены фьюча на РТС
</pre>

Почему тестовый пример (SampleHistoryTesting) не воспроизвел ошибку - так и не понял, ведь в его настройках шага цены тоже не прописано:
<pre>
// create test security
var security = new Security
{
    Id = SecId.Text, // sec id has the same name as folder with historical data
    Code = secCode,
    Board = board,
};
</pre>


В результате, у меня заработало с такими настройками, PNL тоже считается правильно:
<pre>
Security selected_security = new Security
{
    Id = sec_text, // sec id has the same name as folder with historical data
    Code = secCode,
    Board = board,
    PriceStep = 10
};

var level1Info = new Level1ChangeMessage
{
    SecurityId = selected_security.ToSecurityId(),
    ServerTime = startTime,
}
.TryAdd(Level1Fields.PriceStep, 10m)
.TryAdd(Level1Fields.StepPrice, 10m)
.TryAdd(Level1Fields.MinPrice, 10m)
.TryAdd(Level1Fields.MaxPrice, 1000000m)
.TryAdd(Level1Fields.MarginBuy, 10000m)
.TryAdd(Level1Fields.MarginSell, 10000m);
</pre>
