### ISSUE TITLE
Ошибка в ExcelExporter

### ISSUE THREAD

**Issue by Sergey-Dvortsov** [stocksharp/stocksharp#11]
При вызове метода ExcelExporter.Export возникает ошибка:

Не удалось привести тип объекта "Ecng.Collections.ListEx`1[StockSharp.Algo.Candles.Candle]" к типу "Ecng.Collections.IEnumerableEx`1[StockSharp.Algo.Candles.Candle]".

Код:
  
 var exporter = new ExcelExporter(_lkoh, null, ExportCanceled, "candels.xls", Breaked);
ListEx<Candle> candles = new ListEx<Candle>(_candles);
exporter.Export(typeof(Candle), candles);

**Comment by mikasoukhov** [comment]
https://github.com/stocksharp/stocksharp/commit/92369bffed2ca034f228f097f02f97412ba54ad2
