### ISSUE TITLE
Ошибка при импорте в гидре

### ISSUE THREAD

**Issue by Sergey-Dvortsov** [StockSharp/StockSharp#110]
Ошибка:
Cannot convert 12:05:35 with format hh:mm:ss to TimeSpan

Данные:
Инструмент;Площадка;Идентификатор;Номер;Дата;Время;Цена;Объем;Инициатор
MyFuture;MyBoard;34678;12345;03.06.2015 +03;12:05:35;97890;5;Buy
MyFuture;MyBoard;34678;12347;03.06.2015 +03;12:05:36;97880;3;Sell

ЛОг
15:11:35.910|Error  |S#.Data (Hydra)|System.InvalidCastException: Cannot convert 12:05:35 with format hh:mm:ss to TimeSpan. ---> System.FormatException: Входная строка имела неверный формат.
   в System.Globalization.TimeSpanParse.TryParseByFormat(String input, String format, TimeSpanStyles styles, TimeSpanResult& result)
   в System.Globalization.TimeSpanParse.TryParseExactTimeSpan(String input, String format, IFormatProvider formatProvider, TimeSpanStyles styles, TimeSpanResult& result)
   в System.Globalization.TimeSpanParse.ParseExact(String input, String format, IFormatProvider formatProvider, TimeSpanStyles styles)
   в Ecng.Common.TimeHelper.ToTimeSpan(String value, String format)
   --- Конец трассировки внутреннего стека исключений ---
   в Ecng.Common.TimeHelper.ToTimeSpan(String value, String format)
   в StockSharp.Hydra.Panes.ImportPane.FieldMapping.ApplyValue(Object instance, Object value)
   в StockSharp.Hydra.Panes.ImportPane.FieldMapping.ApplyFileValue(Object instance, String value)
   в CallSite.Target(Closure , CallSite , FieldMapping , Object , String )
   в StockSharp.Hydra.Panes.ImportPane.<>c__DisplayClass18d.<OnDoWork>b__18c()
   в Ecng.Common.Converter.<>c__DisplayClassf.<DoInCulture>b__e()
   в Ecng.Common.Converter.DoInCulture[T](CultureInfo cultureInfo, Func`1 func)
   в Ecng.Common.Converter.DoInCulture(CultureInfo cultureInfo, Action action)
   в StockSharp.Hydra.Panes.ImportPane.OnDoWork(Object sender, DoWorkEventArgs e)
   в System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   в System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

Возможно из-за этого:
http://stackoverflow.com/questions/11719055/why-does-timespan-parseexact-not-work

![import_error](https://cloud.githubusercontent.com/assets/10364235/7959656/bc54f7c6-0a03-11e5-9f72-2145e2a5c7ae.png)

**Comment by mikasoukhov** [comment]
Это не ошибка гидры. Формат времени указан неверно.
