### ISSUE TITLE
Конкурс: Кольцевой буфер в LengthIndicator

### ISSUE THREAD

**Issue by AlexanderYastrebov** [StockSharp/StockSharp#111]
Предлагается сменить реализацию Buffer в LengthIndicator с List на кольцевой буфер, т.к. во многих индикаторах используется удаление Buffer.RemoveAt(0) со сложностью O(n).

**Comment by mikasoukhov** [comment]
А в чем смысл?
5 июня 2015 г. 0:27 пользователь "Alexander Yastrebov" <
notifications@github.com> написал:

**Comment by AlexanderYastrebov** [comment]
Смысл в повышении производительности.
Вы же оптимизируете производительность, например здесь https://github.com/StockSharp/StockSharp/blob/master/Algo/Indicators/Highest.cs#L54

**Comment by mikasoukhov** [comment]
Это отдельный элемент, которые не влияет на производительность в целом. Вы
можете запустить под профайлером пример SampleHistoryTesting где
используются два этих индикатора. Так наглядно будет показано, что
индикаторы никак не влияют на общую картину.

Mikhail Sukhov,
StockSharp LLC, http://stocksharp.com

2015-06-05 13:31 GMT+03:00 Alexander Yastrebov <notifications@github.com>:
