### ISSUE TITLE
Ошибка при автоматическом экспорте тиков

### ISSUE THREAD

**Issue by doitagainforme** [StockSharp/StockSharp#12]
![image](https://cloud.githubusercontent.com/assets/10797984/5992512/c4675f2e-aa3d-11e4-833a-e2faecddac75.png)

Имя	Время	Тип	Сообщение
Экспорт (авто)	01.02.2015 16:33:54 +03:00	Info	Инициализируется.
Экспорт (авто)	01.02.2015 16:33:54 +03:00	Info	Перешел в состояние Starting.
Экспорт (авто)	01.02.2015 16:33:54 +03:00	Info	Перешел в состояние Started.
Экспорт (авто)	01.02.2015 16:33:54 +03:00	Info	Старт с 26.01.2015.
Экспорт (авто)	01.02.2015 16:33:54 +03:00	Info	GAZP@TQBS. Экспорт Trade в Txt.
Finam	01.02.2015 16:33:54 +03:00	Info	Инициализируется.
Finam	01.02.2015 16:33:54 +03:00	Info	Перешел в состояние Starting.
Finam	01.02.2015 16:33:54 +03:00	Info	Перешел в состояние Started.
Finam	01.02.2015 16:33:54 +03:00	Info	Старт загрузки сделок за 31.01.2015 для GAZP@TQBS.
Finam	01.02.2015 16:33:54 +03:00	Info	Окончание итерации.
Экспорт (авто)	01.02.2015 16:33:54 +03:00	Info	GAZP@TQBS. Экспорт Trade в Txt. Дата 28.01.2015 0:00:00.
Экспорт (авто)	01.02.2015 16:33:54 +03:00	Error	System.InvalidCastException: Не удалось привести тип объекта "EnumerableEx`1[StockSharp.Messages.ExecutionMessage]" к типу "Ecng.Collections.IEnumerableEx`1[StockSharp.BusinessEntities.Trade]".
в StockSharp.Algo.Export.BaseExporter.#=q_byiiwUtM2cMAXp_nE3zyOTgUGrMftcBXuIT8bnFs9s=.#=qVZllsRg_r$Yv1bgqeBcutw==()
в Ecng.Common.Converter.<>c__DisplayClassf.<DoInCulture>b__e()
в Ecng.Common.Converter.DoInCulture[T](CultureInfo cultureInfo, Func`1 func)
в StockSharp.Algo.Export.BaseExporter.Export(Type dataType, IEnumerable values)
в StockSharp.Hydra.Converters.ExportTask.OnProcess()
Экспорт (авто)	01.02.2015 16:33:54 +03:00	Info	GAZP@TQBS. Экспорт Trade в Txt. Дата 29.01.2015 0:00:00.
Экспорт (авто)	01.02.2015 16:33:54 +03:00	Error	System.InvalidCastException: Не удалось привести тип объекта "EnumerableEx`1[StockSharp.Messages.ExecutionMessage]" к типу "Ecng.Collections.IEnumerableEx`1[StockSharp.BusinessEntities.Trade]".
в StockSharp.Algo.Export.BaseExporter.#=q_byiiwUtM2cMAXp_nE3zyOTgUGrMftcBXuIT8bnFs9s=.#=qVZllsRg_r$Yv1bgqeBcutw==()
в Ecng.Common.Converter.<>c__DisplayClassf.<DoInCulture>b__e()
в Ecng.Common.Converter.DoInCulture[T](CultureInfo cultureInfo, Func`1 func)
в StockSharp.Algo.Export.BaseExporter.Export(Type dataType, IEnumerable values)
в StockSharp.Hydra.Converters.ExportTask.OnProcess()
Экспорт (авто)	01.02.2015 16:33:54 +03:00	Info	GAZP@TQBS. Экспорт Trade в Txt. Дата 30.01.2015 0:00:00.
Экспорт (авто)	01.02.2015 16:33:54 +03:00	Error	System.InvalidCastException: Не удалось привести тип объекта "EnumerableEx`1[StockSharp.Messages.ExecutionMessage]" к типу "Ecng.Collections.IEnumerableEx`1[StockSharp.BusinessEntities.Trade]".
в StockSharp.Algo.Export.BaseExporter.#=q_byiiwUtM2cMAXp_nE3zyOTgUGrMftcBXuIT8bnFs9s=.#=qVZllsRg_r$Yv1bgqeBcutw==()
в Ecng.Common.Converter.<>c__DisplayClassf.<DoInCulture>b__e()
в Ecng.Common.Converter.DoInCulture[T](CultureInfo cultureInfo, Func`1 func)
в StockSharp.Algo.Export.BaseExporter.Export(Type dataType, IEnumerable values)
в StockSharp.Hydra.Converters.ExportTask.OnProcess()
Экспорт (авто)	01.02.2015 16:33:54 +03:00	Info	Окончание итерации.

**Comment by mikasoukhov** [comment]
Не воспроизводится.
