### ISSUE TITLE
Неправильная отрисовка по времени индикатора (точек) на области графика

### ISSUE THREAD

**Issue by ingler-ok** [StockSharp/StockSharp#122]
На графике есть 2 области: свечи со сделками и гистограммы линий Боллинджера. 
На момент совершения сделки хочу на гистограмме зафиксировать текущее значение  (нарисовать значение точкой поверх гистрограммы). 

Проблема: точки рисуются не по датам, а с самого начала графика (на рисунке обвёл фиолетовым сделки и точки. Также показал, где точки должны быть):
![image](https://cloud.githubusercontent.com/assets/12250965/8259787/c8424400-16c7-11e5-97b9-f6318b3e19d6.png)

Добавление индикатора точек на график:
<pre>
ChartIndicatorElement e_trades_bbw1 = new ChartIndicatorElement { DrawStyle = ChartIndicatorDrawStyles.Dot, Color = Color.FromRgb(0, 0, 0), StrokeThickness = 10, FullTitle = "Сделки" };
chart.AddElement(area_bbw1, e_trades_bbw1);
</pre>

При возникновении события совершённой сделки (в стратегии) делаю следующее:
<pre>
var dict = new Dictionary<IChartElement, object>();
dict.Add(chart_window.e_trades_bbw1, new DecimalIndicatorValue(bbw1.Indicator, bbw1.val));
chart_window.chart.Draw(gs.main_serie.GetCurrentCandle<TimeFrameCandle>().OpenTime, dict);
</pre>

main_serie.GetCurrentCandle().OpenTime - 100% правильная (смотрел время в дебагере).

Вопрос: это моя ошибка или баг?

**Comment by mikasoukhov** [comment]
создайте мини пример для воспроизведения проблемы.

**Comment by ingler-ok** [comment]
Убрал из проекта всё-всё лишнее, оставив минимум для воспроизведения ошибки.
 
Скачать можно по прямой ссылке с моего сервера:  http://spiridonov.me/files/Nadejda_AI_test.zip

Проблему удалось воспроизвести (на рисунке синим обвёл сделки и точки, линиями указал, где должны быть точки):
![image](https://cloud.githubusercontent.com/assets/12250965/8273505/82adabb0-1879-11e5-94bb-32eaa29b6695.png).

Пояснения по структуре, выявляющего ошибку примера:
1) В архиве 2 папки: 
"R" - исторические данные по индексу РТС за один тестируемый день (2015-05-19). 
"Nadejda_AI_test" - исходники проекта с DLL файлами вашего Проекта (версия 4.3.6)

2) Какие файлы примера актуальны:
- HistoryTestingWindow.xaml.cs (тут создаётся HistoryEmulationTrader, создаётся стратегия и запускается). 
- WorkStrategy.cs 
Файл стратегии, в нём происходит обработка события изменения свеч, 
<pre>
main_serie
   .WhenCandlesChanged()
   .Do(ProcessCandle)
   .Apply(this);
</pre>

В функции <b>ProcessCandle</b> происходит совершение сделок при удовлетворении правилам торговли (для простоты: продаём, когда кривая ROC-индикатора ниже 0, и покупаем - когда выше). Также в этой функции происходит отрисовка совершённых сделок и индикаторов (значения индикаторов вычисляются на каждом изменении свечки, индикаторы писал сам).
<pre>
main_tfcw.chart.Draw(main_tfcw.e_candles, candle);
bbw1.Indicator.drawOnChart(main_tfcw, bbw1);
roc1.Indicator.drawOnChart(main_tfcw, roc1);
</pre>

Здесь: 
<b>main_serie</b> - серия свечек типа TimeFrameCandle, 15 минут.
<b>main_tfcw</b> - экземпляр класса окна графика (MainTimeFrameChartWindow.cs)

3) MainTimeFrameChartWindow.cs - окно графика.
В окне три области: 
- свечки / сделки
- гистограммы линий Боллинджера + точки(!)
- РОК кривая

Остальные файлы как-либо на текущую ошибку не влияют (имхо). 

П.С. Для быстроты навигации:
Номера строк кода отрисовки свечей и индикаторов: 89-91 ( WorkStrategy.cs )
Номер строк кода отрисовки сделок и точек на гистограммах Б.: 274-277 (WorkStrategy.cs )

П.П.С. Огромно спасибо, что проявили внимание, представляю, сколько у вас действительно важных задач в сравнении с проблемами отрисовки, да ещё и точек на индикаторе.

**Comment by mikasoukhov** [comment]
Создайте мини-пример. Запустить, загрузить данные, отрисовать данные.

**Comment by mikasoukhov** [comment]
Желательно чтобы весь код уместился максимум в 15 строчек.
