### ISSUE TITLE
S#4.3.7 QuikLua. Не приходит событие NewOrders

### ISSUE THREAD

**Issue by RomSunZ** [StockSharp/StockSharp#126]
S#4.3.7 QuikLua.Событие NewOrders вызывается только при подключении, в дальнейшем это собыите не вызывается.

**Comment by mikasoukhov** [comment]
не воспроизводится.

**Comment by RomSunZ** [comment]
Значит событие не приходит только с ордерами, выставленными вручную в терминале.
