### ISSUE TITLE
SampleHistoryTestingParallelPublic - Series не наступает WhenCandles

### ISSUE THREAD

**Issue by rogonke** [stocksharp/stocksharp#14]
Во время работы примера SampleHistoryTestingParallelPublic у серии свечек не наступает событие WhenCandlesFinished (как и WhenCandles).

Поменял только таймфрейм, инструмент и даты начала-конца. 
В обычном SampleHistoryTestingPublic с этими параметрами работает нормально.

>0001/01/01 00:00:00.000|       |HistoryEmulationConnector|Connect
2014/03/03 00:00:00.000|       |HistoryEmulationConnector|Изменение состояния эмуляции Stopped -> Starting
2014/03/03 00:00:00.000|       |HistoryEmulationConnector|StartExport
2014/03/03 00:00:00.000|       |SS_SBER@FORTS_test account|Переинициализация.
2014/03/03 00:00:00.000|       |SS_SBER@FORTS_test account|Новая позиция: .
2014/03/03 00:00:00.000|Debug  |SS_SBER@FORTS_test account|Переход из состояния Stopped в Started.
2014/03/03 00:00:00.000|       |SS_SBER@FORTS_test account|Стратегия запущена. [0,-1]. Позиция 0.
2014/03/03 00:00:00.000|Debug  |SS_SBER@FORTS_test account|My_test_log_message : OnStarted
2014/03/03 00:00:00.000|       |HistoryEmulationConnector|Инструмент SBER@FORTS зарегистрирован на получение рыночных данных для CandleTimeFrame.
2014/03/03 00:00:00.000|       |HistoryEmulationConnector|Создан новый портфель test account.
2014/03/03 00:00:00.000|       |HistoryEmulationConnector|Создан новый портфель test account_1.
2014/03/03 00:00:00.000|       |HistoryEmulationConnector|Изменение состояния эмуляции Starting -> Started
2014/03/03 00:00:00.000|       |Эмулятор  |Loading 03.03.2014 0:00:00 Events: 0
2014/03/03 00:00:00.000|       |Эмулятор  |Loading 04.03.2014 0:00:00 Events: 8
2014/03/03 00:00:00.000|       |Эмулятор  |Loading 05.03.2014 0:00:00 Events: 16
2014/03/03 00:00:00.000|       |Эмулятор  |Loading 06.03.2014 0:00:00 Events: 24
2014/03/03 00:00:00.000|       |Эмулятор  |Loading 07.03.2014 0:00:00 Events: 32
2014/03/03 00:00:00.000|       |Эмулятор  |Loading 10.03.2014 0:00:00 Events: 40
2014/03/03 00:00:00.000|       |Эмулятор  |Loading 11.03.2014 0:00:00 Events: 48
2014/03/03 00:00:00.000|       |Эмулятор  |Loading 12.03.2014 0:00:00 Events: 56
2014/03/03 00:00:00.000|       |Эмулятор  |Loading 13.03.2014 0:00:00 Events: 64
2014/03/03 00:00:00.000|       |Эмулятор  |Loading 14.03.2014 0:00:00 Events: 72
2014/03/03 00:00:00.000|       |Эмулятор  |Loading 17.03.2014 0:00:00 Events: 80
2014/03/03 00:00:00.000|       |Эмулятор  |Loading 18.03.2014 0:00:00 Events: 88
2014/03/03 00:00:00.000|       |Эмулятор  |Loading 19.03.2014 0:00:00 Events: 96
2014/03/03 00:00:00.000|       |Эмулятор  |Loading 20.03.2014 0:00:00 Events: 104
2014/03/03 00:00:00.000|       |Эмулятор  |Loading 21.03.2014 0:00:00 Events: 112
2014/03/03 00:00:00.000|       |Эмулятор  |Loading 24.03.2014 0:00:00 Events: 120
2014/03/03 00:00:00.000|       |Эмулятор  |Loading 25.03.2014 0:00:00 Events: 128
2014/03/03 00:00:00.000|       |Эмулятор  |Loading 26.03.2014 0:00:00 Events: 136
2014/03/03 00:00:00.000|       |Эмулятор  |Loading 27.03.2014 0:00:00 Events: 144
2014/03/03 00:00:00.000|       |Эмулятор  |Loading 28.03.2014 0:00:00 Events: 152
2014/03/30 00:00:00.000|       |HistoryEmulationConnector|Изменение состояния эмуляции Started -> Stopping
2014/03/30 00:00:00.000|       |HistoryEmulationConnector|StopExport
2014/03/30 00:00:00.000|       |HistoryEmulationConnector|Изменение состояния эмуляции Stopping -> Stopped
2014/03/30 00:00:00.000|Debug  |SS_SBER@FORTS_test account|Переход из состояния Started в Stopping.
2014/03/30 00:00:00.000|       |SS_SBER@FORTS_test account|Стратегия останавливается. [0,-1]. Позиция 0.
2014/03/30 00:00:00.000|       |SS_SBER@FORTS_test account|Ожидание снятия всех активных заявок.
2014/03/30 00:00:00.000|Debug  |SS_SBER@FORTS_test account|Правило 'Законченные свечи TimeFrameCandle_SBER@FORTS_00-01-00 (0x73C956)'. Удаляется.
2014/03/30 00:00:00.000|Debug  |SS_SBER@FORTS_test account|Правило 'Законченные свечи TimeFrameCandle_SBER@FORTS_00-01-00 (0x73C956)'. Освободило ресурсы.
2014/03/30 00:00:00.000|Debug  |SS_SBER@FORTS_test account|Правило 'Законченные свечи TimeFrameCandle_SBER@FORTS_00-01-00 (0x73C956)'. Удалено.
2014/03/30 00:00:00.000|Debug  |SS_SBER@FORTS_test account|Переход из состояния Stopping в Stopped.
2014/03/30 00:00:00.000|       |SS_SBER@FORTS_test account|Стратегия остановлена. [0,-1]. Позиция 0.
2014/03/30 00:00:00.000|       |HistoryEmulationConnector|Disconnect

UPD:
Смотрел на 4.2.58

**Comment by mikasoukhov** [comment]
Без исправлений работает?

**Comment by rogonke** [comment]
Не нашел данные на которых он тестирует по-умолчанию

**Comment by mikasoukhov** [comment]
Тогда читайте докуентацию. Ошибку закрываю.

**Comment by rogonke** [comment]
Косяк действительно мой.

Если для кого-то кроме меня это тоже покажется не очень очевидным :

Таймфрейм читаемых из истории свечей по-умолчанию равен 5-ти минутам, и если такого в истории нет - тестер никаких сообщений вам не выдаст.

Меняется этот таймфрейм не в MarketTimeChangedInterval и даже не в
```
batchEmulation.EmulationConnector.MarketEmulator.Settings.UseCandlesTimeFrame
```
А в базовом классе EmulationSettings - MarketEmulatorSettings.UseCandlesTimeFrame 
```
var batchEmulation = new BatchEmulation(new[] { security }, new[] { portfolio }, storageRegistry)
{
	EmulationSettings =
	{
		MarketTimeChangedInterval = timeFrame,
		StartTime = startTime,
		StopTime = stopTime,
		UseCandlesTimeFrame = historyTimeFrame,	//<--- таймфрейм читаемых свечей
		BatchSize = periods.Length,
	}
};
```
