### ISSUE TITLE
Hydra обнаружил несколько ошибок

### ISSUE THREAD

**Issue by Prival1** [StockSharp/StockSharp#140]
записал видео. Кратко 
при конвертации в формат txt тиков, неправильно выводится время
формат файла не txt а csv
при большол объеме файла нехватка памяти
акции сбер банка без копеек. только рубли.
Все видно на видео
https://drive.google.com/file/d/0B5zAjuLApjZJdFVNa3I0TlZWelU/view

**Comment by mikasoukhov** [comment]
Не увидел ошибок.

**Comment by Prival1** [comment]
т.е. так как на видео гидра и должна работать ? именно так и задумано ?
Вместо времени в файле вот такое пишется - 
100000000000 +03:00 
Это 10 часов утра, бог с ним с нулями +03:00 зачем выводить ?
И то что стоимость сбербанка скачивается только рубли, копеек нет. Это тоже норма ? Если я выкачиваю руками, то копейки есть, а в гидре нету ((((
Или Вы не все видео просмотрели ?
