### ISSUE TITLE
S#4.3.8 QuikLua. LuaServer не всегда получает транзакцию заявки

### ISSUE THREAD

**Issue by RomSunZ** [StockSharp/StockSharp#146]
Периодически в LuaFixServer в функцию Process(Message message) дублем приходят сообщения о заявках с не заполненным полем TransactionId:
=========================лог ЛУА======================================
2015/07/27 22:37:44.204|       |LuaServer |Request: Type = OrderRegister TrId = 80978136 Value = t = {}
t["ACCOUNT"] = "NL0011100043"
t["CLASSCODE"] = "QJSIM"
t["SECCODE"] = "SBER"
t["QUANTITY"] = "2"
t["CLIENT_CODE"] = "93036"
t["EXPIRY_DATE"] = "GTC"
t["OPERATION"] = "B"
t["TYPE"] = "L"
t["ACTION"] = "NEW_ORDER"
t["PRICE"] = "71.85"
t["EXECUTION_CONDITION"] = "PUT_IN_QUEUE"
t["TRANS_ID"] = "80978136"
return sendTransaction(t)
 SecId =  OrdType = Limit IsSubscribe = False DataType = Level1
2015/07/27 22:37:45.183|Error  |LuaServer |Out. Execution,T(L)=0001.01.01 00:00:00.000,T(S)=2015.07.27 19:37:52.000,(Order),Sec=S#:SBER@QJSIM, Native:,Type:,Ord=1801805733/15/0,Fail=,TId=,Pf=93036,TPrice=,UId=... OriginalTransactionId 0 transaction ---,  error ---
2015/07/27 22:37:45.286|Error  |LuaServer |Out. Execution,T(L)=0001.01.01 00:00:00.000,T(S)=2015.07.27 19:37:52.000,(Order),Sec=S#:SBER@QJSIM, Native:,Type:,Ord=1801805733/80978136/80978136,Fail=,TId=,Pf=93036,TPrice=,UId=... OriginalTransactionId 80978136 transaction ACCOUNT=NL0011100043; CLASSCODE=QJSIM; SECCODE=SBER; QUANTITY=2; CLIENT_CODE=93036; EXPIRY_DATE=GTC; OPERATION=B; TYPE=L; ACTION=NEW_ORDER; PRICE=71.85; EXECUTION_CONDITION=PUT_IN_QUEUE; TRANS_ID=80978136; error ---
===============================================================
из-за чего трейдер создает два ордера: один раз с правильным TransactionId, а второй раз с неправильным:
========================лог коннектора=======================================
22:37:45.185|Debug  |FIX       |Сессия 'server'. Получено: '8=FIX.4.0^9=219^35=8^49=quik^56=StockSharpTS^52=20150727-16:37:45.198^34=1024^11=15^150=I^39=0^58=93036^60=20150727-16:37:52.000^55=SBER^207=QJSIM^37=1801805733^151=2^38=2^1=93036^44=71.85^126=99991231-23:59:59.999^14=0^40=2^59=1^54=1^10=012^'
22:37:45.185|Debug  |QuikLUA   |BP:Execution,T(L)=2015.07.27 22:37:45.185,T(S)=2015.07.27 19:37:52.000,(Order),Sec=S#:SBER@QJSIM, Native:,Type:,Ord=1801805733/15/15,Fail=,TId=,Pf=93036,TPrice=,UId=
22:37:45.185|       |QuikLUA   |New order: 15/1801805733 Покупка Цена=71.85 Объем=2 Сост=Active Бал=2 
22:37:45.288|Debug  |FIX       |Сессия 'server'. Получено: '8=FIX.4.0^9=237^35=8^49=quik^56=StockSharpTS^52=20150727-16:37:45.300^34=1025^41=80978136^11=80978136^150=I^39=0^58=93036^60=20150727-16:37:52.000^55=SBER^207=QJSIM^37=1801805733^151=2^38=2^1=93036^44=71.85^126=99991231-23:59:59.999^14=0^40=2^59=1^54=1^10=143^'
22:37:45.285|Debug  |QuikLUA   |BP:Execution,T(L)=2015.07.27 22:37:45.287,T(S)=2015.07.27 19:37:52.000,(Order),Sec=S#:SBER@QJSIM, Native:,Type:,Ord=1801805733/80978136/80978136,Fail=,TId=,Pf=93036,TPrice=,UId=
22:37:45.287|       |QuikLUA   |Order changed: 80978136/1801805733 Покупка Цена=71.85 Объем=2 Сост=Active Бал=2 
===============================================================
Не смотря на то, что в трейдере пишет событие Order changed, на самом деле в Connector.Orders висят оба ордера и с id=15 и с id=80978136, но ордер с id=15 всегда находится в состоянии Active.

**Comment by mikasoukhov** [comment]
нужны логи

**Comment by RomSunZ** [comment]
логи см. выше. Больше записей по заявкам в логах нет.
