### ISSUE TITLE
Использование нескольких BufferedChart 

### ISSUE THREAD

**Issue by ingler-ok** [StockSharp/StockSharp#153]
Добрый вечер. 

При использовании 
<pre>
chart = new BufferedChart(this.Chart);
</pre>
График рисуется только для одного из таймфреймов, второй - пустой, хотя создание второго идентично первому (взято из примера).
![image](https://cloud.githubusercontent.com/assets/12250965/9151023/cde95090-3dfc-11e5-88e4-59eef97c775e.png)

<pre>
//1
cw_one = new ChartWindow(params);
cw_one.Show();

//2
cw_two = new ChartWindow(params);
cw_two.Show();
</pre>
ChartWindow - окно графика из примера СС, при инициализации которого создаётся area  и добавляются  различные индикаторы. 

Почему не выходит использовать несколько окон для отрисовки? Ведь создаются разные экземпляры класса ChartWindow. Спасибо за внимание.

**Comment by mikasoukhov** [comment]
Не воспроизводиться.

**Comment by ingler-ok** [comment]
Если не использовать BufferedChart, ошибка действительно не воспроизводится, можно отобразить миллион окон:
<pre>
chart = this.Chart
</pre>

Если же использовать 
<pre>
chart = new BufferedChart(this.Chart);
</pre>
Работает только в одном окне. 

Хотябы намекните, почему? 
chart - переменная внутри класса ChartWindow.xaml.cs
