### ISSUE TITLE
S#4.3.9.1 Ошибка System.DivideByZeroException в Hydra источник РТС 

### ISSUE THREAD

**Issue by RomSunZ** [StockSharp/StockSharp#154]
При попытке скачать данные с РТС. Пытался скачать данные по опционам ( в частности RI85000BR5 за 29.05.2015г) 

RTS 10.08.2015 19:55:25 +06:00 Error System.DivideByZeroException: Попытка деления на нуль.
   в System.Decimal.FCallDivide(Decimal& d1, Decimal& d2)
   в System.Decimal.Remainder(Decimal d1, Decimal d2)
   в #=qNtrpoXnrptmPqsCVyyouoXgYiw1Bbz_D1A_U5dMzsqJ3QBU2Ufm$VM6imR0Y4dZv.#=q5ee53xQRPO59CLQkFNdO2Q==(ISecurityStorage #=qqOHRAlI$Ao4an$_hfDLAjkQ7T3RbJ9fenY0Q5FZjM4g=, IDictionary`2 #=qbhT7FBw8ozQ$F_w0eYpfBQ==, String #=qmHVoN4VXAEypGSFue$gg_Q==, DateTime #=qkfcOdnbhMAUiwMO8SWWSfg==, Boolean #=qpEDNFeRNhfewbKF1jxrVTCOg5I0KyM0vbX2OciTF$zI=)
   в #=qNtrpoXnrptmPqsCVyyouoXgYiw1Bbz_D1A_U5dMzsqJ3QBU2Ufm$VM6imR0Y4dZv.#=qHnDxuSdt_hRTJyNK3G7c4Q==(ISecurityStorage #=qzI8sNwY9rVB5G0JyQmX$ByE6T3kcrBgj_FnZJrV1f$k=, FtpClient #=qHS5Mx1KAh7$mNb6sor$hKw==, DateTime #=qahmw42po8tnf0fpWXz_t_Q==, Boolean #=qWsawuZyZ3O4IEKsuZo85PCt7IBLkr2cUH_Zkq5K338U=)
   в StockSharp.Algo.History.Russian.Rts.RtsHistorySource.#=qvs25Yn5d$OA0GFh6m7HrzIL$g8f5EiRtmkZBXw3ar2U=.#=qZGQItT68KzB8Jm8kmliblMUKCnLsbDwnSj0I3jPS9Fo=()
   в Ecng.Common.Converter.DoInCulture[T](CultureInfo cultureInfo, Func`1 func)
   в StockSharp.Algo.History.Russian.Rts.RtsHistorySource.LoadTrades(ISecurityStorage storage, DateTime date)
   в StockSharp.Hydra.Rts.RtsTask.OnProcess()
   в StockSharp.Hydra.Core.BaseHydraTask.<Start>b__0()

**Comment by mikasoukhov** [comment]
Данные битые. Не ошибка Гидры.
