### ISSUE TITLE
IqFeed - ошибка при получении исторических свечек.

### ISSUE THREAD

**Issue by moadip84** [stocksharp/stocksharp#16]
Сборка 4.2.61
В SampleIqFeed при получения исторических свечек.
![641051423397074527545665143093](https://cloud.githubusercontent.com/assets/10475028/6096500/b35fe19e-afbd-11e4-9254-5793642c4e3d.png)

**Comment by mikasoukhov** [comment]
https://github.com/stocksharp/stocksharp/commit/46365c799a09e94776ac6143e0f0369427f0afb9
