### ISSUE TITLE
Неправильный результаты тестирования при использовании StopLossStrategy

### ISSUE THREAD

**Issue by Sergey-Dvortsov** [stocksharp/stocksharp#17]
При использовании StopLossStrategy неправильно рассчитываются результаты тестирования:

Сделки по содержимому лога:
-----------------------------------------
Род. стратегия Sell - 61200
SLS Buy - 61900
Род. стратегия Buy - 66180 
SLS Sell - 68650
Реализ. Pnl  = 2480

Результат из PnlManager 
--------------------------------
Pnl =  - 5010

Код стратегии:
----------------------
namespace SampleHistoryTesting
{
	using System.Linq;
	using System.Collections.Generic;
        using System.Diagnostics;
	using Ecng.Common;
	using StockSharp.Algo;
	using StockSharp.Algo.Candles;
	using StockSharp.Algo.Indicators;
	using StockSharp.Algo.Strategies;
	using StockSharp.Algo.Strategies.Quoting;
        using StockSharp.Algo.Strategies.Protective;
	using StockSharp.Logging;
	using StockSharp.BusinessEntities;
	using StockSharp.Messages;
	using StockSharp.Xaml.Charting;
	using StockSharp.Localization;

	class SmaStrategy : BasketStrategy
	{
		private readonly IChart _chart;
		private readonly ChartCandleElement _candlesElem;
		private readonly ChartTradeElement _tradesElem;
		private readonly ChartIndicatorElement _shortElem;
		private readonly ChartIndicatorElement _longElem;
		private readonly List<MyTrade> _myTrades = new List<MyTrade>();
		private readonly CandleSeries _series;
		private bool _isShortLessThenLong;

		public SmaStrategy(IChart chart, ChartCandleElement candlesElem, ChartTradeElement tradesElem, 
			SimpleMovingAverage shortMa, ChartIndicatorElement shortElem,
			SimpleMovingAverage longMa, ChartIndicatorElement longElem,
            CandleSeries series, BasketStrategyFinishModes finishMode)
            : base(finishMode)
		{
			_chart = chart;
			_candlesElem = candlesElem;
			_tradesElem = tradesElem;
			_shortElem = shortElem;
			_longElem = longElem;
			_series = series;
			ShortSma = shortMa;
			LongSma = longMa;
		}

		public SimpleMovingAverage LongSma { get; private set; }
		public SimpleMovingAverage ShortSma { get; private set; }

		protected override void OnStarted()
		{
			_series
				.WhenCandlesFinished()
				.Do(ProcessCandle)
				.Apply(this);

            //Security _securuty = new Security();.
            var s = _series.GetCandleCount();

            _series.WhenCandlesChanged().And(_series.WhenCurrentCandleTotalVolumeMore(100)).Do(() => { do1(); });
			
            // запоминаем текущее положение относительно друг друга
			_isShortLessThenLong = ShortSma.GetCurrentValue() < LongSma.GetCurrentValue();
        
        this.WhenNewMyTrades()
                .Do(trades =>
                   {
                       foreach (MyTrade trade in trades)
                       {
                           try
                           {
                               var sl = new StopLossStrategy(trade, new Unit(10)); 
                               ChildStrategies.Add(sl);
                           }
                           catch (System.Exception ex)
                           {
                              Debug.WriteLine(ex.Message);
                           }
                       }
                   } 
                   )
                .Apply(this); 

	         base.OnStarted();
		 }

        private void do1()
        {
            this
                .WhenNewMyTrades()
                .Do(trades =>  _myTrades.AddRange(trades))
                .Apply(this); 
        }

		private void ProcessCandle(Candle candle)
		{
			// если наша стратегия в процессе остановки
			if (ProcessState == ProcessStates.Stopping)
			{
				// отменяем активные заявки
				CancelActiveOrders();
				return;
			}

			this.AddInfoLog(LocalizedStrings.Str2177Params.Put(candle.OpenTime, candle.OpenPrice, candle.HighPrice, candle.LowPrice, candle.ClosePrice, candle.TotalVolume));

			// добавляем новую свечу
			var longValue = LongSma.Process(candle);
			var shortValue = ShortSma.Process(candle);

			// вычисляем новое положение относительно друг друга
			var isShortLessThenLong = ShortSma.GetCurrentValue() < LongSma.GetCurrentValue();

			// если произошло пересечение
			if (_isShortLessThenLong != isShortLessThenLong)
			{
				// если короткая меньше чем длинная, то продажа, иначе, покупка.
				var direction = isShortLessThenLong ? Sides.Sell : Sides.Buy;

				// вычисляем размер для открытия или переворота позы
				var volume = Position == 0 ? Volume : Position.Abs().Min(Volume) * 2;

				if (!SafeGetConnector().RegisteredMarketDepths.Contains(Security))
				{
                    if (Position == 0)
                    {
                        var price = Security.GetMarketPrice(Connector, direction);
                        // регистрируем псевдо-маркетную заявку - лимитная заявка с ценой гарантирующей немедленное исполнение.
                        if (price != null)
                            RegisterOrder(this.CreateOrder(direction, price.Value, volume));
                    }
                    //else
                    //{
                    //    // переворачиваем позицию через котирование
                    //    var strategy = new MarketQuotingStrategy(direction, volume)
                    //    {
                    //        WaitAllTrades = true,
                    //    };
                    //    ChildStrategies.Add(strategy);
                   
                    //}

				}

				// запоминаем текущее положение относительно друг друга
				_isShortLessThenLong = isShortLessThenLong;

			}

			var trade = _myTrades.FirstOrDefault();
			_myTrades.Clear();

			var dict = new Dictionary<IChartElement, object>
			{
				{ _candlesElem, candle },
				{ _shortElem, new ChartIndicatorValue(ShortSma, shortValue) },
				{ _longElem, new ChartIndicatorValue(LongSma, longValue) },
				{ _tradesElem, trade }
			};

			_chart.Draw(candle.OpenTime, dict);
		}
	}
}

Результаты тестирования:
---------------------------------- 
![historytest](https://cloud.githubusercontent.com/assets/10364235/6103711/19b31d36-b058-11e4-9d9a-1f75d522dd97.png)

Лог:
----------------------------
0001/01/01 00:00:00.000|       |HistoryEmulationConnector|Connect
0001/01/01 00:00:00.000|       |HistoryEmulationConnector|StartExport
2014/12/16 00:00:00.000|       |HistoryEmulationConnector|Изменение состояния эмуляции Stopped -> Starting
2014/12/16 00:00:00.000|       |HistoryEmulationConnector|Создан новый портфель test account.
2014/12/16 00:00:00.000|       |HistoryEmulationConnector|Изменение состояния эмуляции Starting -> Started
2014/12/16 00:00:00.000|       |HistoryEmulationConnector|Инструмент RIH5@FORTS зарегистрирован на получение рыночных данных для Candles.
2014/12/16 00:00:00.000|       |Эмулятор  |Loading 16.12.2014 0:00:00 Events: 0
2014/12/16 00:00:00.000|       |Эмулятор  |Loading 17.12.2014 0:00:00 Events: 163
2014/12/16 10:00:00.000|       |SS_RIH5@FORTS_test account|Стратегия запущена. [0,-1]. Позиция 0.
2014/12/16 10:05:00.000|       |SS_RIH5@FORTS_test account|Новая свеча 12/16/2014 10:00:00 +03:00: 67100;77000;67100;70730; объем 45150
........................
2014/12/16 16:30:00.000|       |SS_RIH5@FORTS_test account|Новая свеча 12/16/2014 16:25:00 +03:00: 61340;61640;60760;61250; объем 2303
2014/12/16 16:30:00.000|       |SS_RIH5@FORTS_test account|Регистрация новой Limit (0x1153926) заявки на Sell с ценой 40260 и объемом 1. 
2014/12/16 16:30:00.000|       |HistoryEmulationConnector|RegisterOrder: 0/ Продажа Цена=40260 Объем=1 Сост=None Бал=0 
2014/12/16 16:30:00.000|       |HistoryEmulationConnector|New order: 1/ Продажа Цена=40260 Объем=1 Сост=Pending Бал=1 
2015/02/09 11:37:24.766|       |#=qhaDw3u2OKwPRZ4GTeEcYhloszQZeybELWSJLOr8_KqA=|Заявка 1 зарегистрирована.
2015/02/09 11:37:24.832|       |#=qhaDw3u2OKwPRZ4GTeEcYhloszQZeybELWSJLOr8_KqA=|Заявка 1. Исполнение объема 1 по цене 61200.
2015/02/09 11:37:24.833|       |#=qhaDw3u2OKwPRZ4GTeEcYhloszQZeybELWSJLOr8_KqA=|Заявка 1 полностью исполнена.
2015/02/09 11:37:24.836|       |#=qhaDw3u2OKwPRZ4GTeEcYhloszQZeybELWSJLOr8_KqA=|Сделка 1 заявки 1 P=61200 V=1.
2014/12/16 16:30:00.000|       |HistoryEmulationConnector|Order changed: 1/1 Продажа Цена=40260 Объем=1 Сост=Done Бал=0 
2014/12/16 16:30:00.000|       |SS_RIH5@FORTS_test account|Новая позиция: test account-RIH5@FORTS=-1.
2014/12/16 16:30:00.000|       |SS_RIH5@FORTS_test account|Заявка 1 (0x1153926) больше не активна.
2014/12/16 16:30:00.000|       |SLS_RIH5@FORTS_test account|Стратегия запущена. [0,1]. Позиция 0.
2014/12/16 16:30:00.000|       |SLS_RIH5@FORTS_test account|Защита позиции Sell/61200 с объемом 1. Уровень=10, Скользящий=False, Маркет-заявки=False, Котирование=False, Проскальзывание=0
2014/12/16 16:30:00.000|       |SLS_RIH5@FORTS_test account|Котирование на Buy объема 1.
2014/12/16 16:30:00.000|       |SS_RIH5@FORTS_test account|Новая Sell сделка 1 по цене 61200 на 1 заявки 1.
2014/12/16 16:30:00.000|       |HistoryEmulationConnector|Инструмент RIH5@FORTS зарегистрирован на получение рыночных данных для MarketDepth.
2014/12/16 16:30:00.000|       |SLS_RIH5@FORTS_test account|Защита активирована. Закрытие позиции по 93940.
2014/12/16 16:30:00.000|       |SLS_RIH5@FORTS_test account|Цена текущей NULL и лучшей 93940.
2014/12/16 16:30:00.000|       |SLS_RIH5@FORTS_test account|Лучший бид 61480 и лучший аск 61500.
2014/12/16 16:30:00.000|       |SLS_RIH5@FORTS_test account|Регистрация новой Limit (0x227D7D6) заявки на Buy с ценой 93940 и объемом 1. 
2014/12/16 16:30:00.000|       |HistoryEmulationConnector|RegisterOrder: 0/ Покупка Цена=93940 Объем=1 Сост=None Бал=0 
2014/12/16 16:30:00.000|       |HistoryEmulationConnector|New order: 4/ Покупка Цена=93940 Объем=1 Сост=Pending Бал=1 
2014/12/16 16:35:00.000|       |SS_RIH5@FORTS_test account|Новая свеча 12/16/2014 16:30:00 +03:00: 61200;61500;60920;61190; объем 4407
2015/02/09 11:37:25.456|       |#=qhaDw3u2OKwPRZ4GTeEcYhloszQZeybELWSJLOr8_KqA=|Заявка 4 зарегистрирована.
2015/02/09 11:37:25.456|       |#=qhaDw3u2OKwPRZ4GTeEcYhloszQZeybELWSJLOr8_KqA=|Заявка 4. Исполнение объема 1 по цене 61190.
2015/02/09 11:37:25.456|       |#=qhaDw3u2OKwPRZ4GTeEcYhloszQZeybELWSJLOr8_KqA=|Заявка 4 полностью исполнена.
2015/02/09 11:37:25.456|       |#=qhaDw3u2OKwPRZ4GTeEcYhloszQZeybELWSJLOr8_KqA=|Сделка 2 заявки 4 P=61190 V=1.
2014/12/16 16:35:00.000|       |HistoryEmulationConnector|Order changed: 4/2 Покупка Цена=93940 Объем=1 Сост=Done Бал=0 
2014/12/16 16:35:00.000|       |SS_RIH5@FORTS_test account|Новая позиция: test account-RIH5@FORTS=0.
2014/12/16 16:35:00.000|       |SLS_RIH5@FORTS_test account|Новая позиция: test account-RIH5@FORTS=1.
2014/12/16 16:35:00.000|       |SLS_RIH5@FORTS_test account|Позиция изменилась на 1. Оставшийся объем 0.
2014/12/16 16:35:00.000|       |SLS_RIH5@FORTS_test account|Заканчиваем котирование.
2014/12/16 16:35:00.000|       |SLS_RIH5@FORTS_test account|Стратегия останавливается. [0,1]. Позиция 1.
2014/12/16 16:35:00.000|       |SLS_RIH5@FORTS_test account|Ожидание снятия всех активных заявок.
2014/12/16 16:35:00.000|       |SLS_RIH5@FORTS_test account|Стратегия остановлена. [0,1]. Позиция 1.
2014/12/16 16:40:00.000|       |SS_RIH5@FORTS_test account|Новая свеча 12/16/2014 16:35:00 +03:00: 61190;61400;60640;60930; объем 2482
......................................
2014/12/16 19:25:00.000|       |SS_RIH5@FORTS_test account|Новая свеча 12/16/2014 19:20:00 +03:00: 63850;66210;63810;66160; объем 5656
2014/12/16 19:25:00.000|       |SS_RIH5@FORTS_test account|Регистрация новой Limit (0xA30206) заявки на Buy с ценой 93940 и объемом 1. 
2014/12/16 19:25:00.000|       |HistoryEmulationConnector|RegisterOrder: 0/ Покупка Цена=93940 Объем=1 Сост=None Бал=0 
2014/12/16 19:25:00.000|       |HistoryEmulationConnector|New order: 6/ Покупка Цена=93940 Объем=1 Сост=Pending Бал=1 
2015/02/09 11:37:34.002|       |#=qhaDw3u2OKwPRZ4GTeEcYhloszQZeybELWSJLOr8_KqA=|Заявка 6 зарегистрирована.
2015/02/09 11:37:34.002|       |#=qhaDw3u2OKwPRZ4GTeEcYhloszQZeybELWSJLOr8_KqA=|Заявка 6. Исполнение объема 1 по цене 66180.
2015/02/09 11:37:34.002|       |#=qhaDw3u2OKwPRZ4GTeEcYhloszQZeybELWSJLOr8_KqA=|Заявка 6 полностью исполнена.
2015/02/09 11:37:34.002|       |#=qhaDw3u2OKwPRZ4GTeEcYhloszQZeybELWSJLOr8_KqA=|Сделка 3 заявки 6 P=66180 V=1.
2014/12/16 19:25:00.000|       |HistoryEmulationConnector|Order changed: 6/3 Покупка Цена=93940 Объем=1 Сост=Done Бал=0 
2014/12/16 19:25:00.000|       |SS_RIH5@FORTS_test account|Новая позиция: test account-RIH5@FORTS=1.
2014/12/16 19:25:00.000|       |SS_RIH5@FORTS_test account|Заявка 6 (0xA30206) больше не активна.
2014/12/16 19:25:00.000|       |SLS_RIH5@FORTS_test account|Стратегия запущена. [0,1]. Позиция 0.
2014/12/16 19:25:00.000|       |SLS_RIH5@FORTS_test account|Защита позиции Buy/66180 с объемом 1. Уровень=10, Скользящий=False, Маркет-заявки=False, Котирование=False, Проскальзывание=0
2014/12/16 19:25:00.000|       |SLS_RIH5@FORTS_test account|Котирование на Sell объема 1.
2014/12/16 19:25:00.000|       |SS_RIH5@FORTS_test account|Новая Buy сделка 3 по цене 66180 на 1 заявки 6.
2014/12/16 19:25:00.000|       |HistoryEmulationConnector|Инструмент RIH5@FORTS зарегистрирован на получение рыночных данных для MarketDepth.
2014/12/16 19:25:00.000|       |SLS_RIH5@FORTS_test account|Защита активирована. Закрытие позиции по 40260.
2014/12/16 19:25:00.000|       |SLS_RIH5@FORTS_test account|Цена текущей NULL и лучшей 40260.
2014/12/16 19:25:00.000|       |SLS_RIH5@FORTS_test account|Лучший бид 66160 и лучший аск 66170.
2014/12/16 19:25:00.000|       |SLS_RIH5@FORTS_test account|Регистрация новой Limit (0x285DFA9) заявки на Sell с ценой 40260 и объемом 1. 
2014/12/16 19:25:00.000|       |HistoryEmulationConnector|RegisterOrder: 0/ Продажа Цена=40260 Объем=1 Сост=None Бал=0 
2014/12/16 19:25:00.000|       |HistoryEmulationConnector|New order: 9/ Продажа Цена=40260 Объем=1 Сост=Pending Бал=1 
2014/12/16 19:30:00.000|       |SS_RIH5@FORTS_test account|Новая свеча 12/16/2014 19:25:00 +03:00: 66180;70060;66170;68650; объем 13232
2015/02/09 11:37:34.192|       |#=qhaDw3u2OKwPRZ4GTeEcYhloszQZeybELWSJLOr8_KqA=|Заявка 9 зарегистрирована.
2015/02/09 11:37:34.192|       |#=qhaDw3u2OKwPRZ4GTeEcYhloszQZeybELWSJLOr8_KqA=|Заявка 9. Исполнение объема 1 по цене 68650.
2015/02/09 11:37:34.192|       |#=qhaDw3u2OKwPRZ4GTeEcYhloszQZeybELWSJLOr8_KqA=|Заявка 9 полностью исполнена.
2015/02/09 11:37:34.192|       |#=qhaDw3u2OKwPRZ4GTeEcYhloszQZeybELWSJLOr8_KqA=|Сделка 4 заявки 9 P=68650 V=1.
2014/12/16 19:30:00.000|       |HistoryEmulationConnector|Order changed: 9/4 Продажа Цена=40260 Объем=1 Сост=Done Бал=0 
2014/12/16 19:30:00.000|       |SS_RIH5@FORTS_test account|Новая позиция: test account-RIH5@FORTS=0.
2014/12/16 19:30:00.000|       |SLS_RIH5@FORTS_test account|Новая позиция: test account-RIH5@FORTS=-1.
2014/12/16 19:30:00.000|       |SLS_RIH5@FORTS_test account|Позиция изменилась на -1. Оставшийся объем 0.
2014/12/16 19:30:00.000|       |SLS_RIH5@FORTS_test account|Заканчиваем котирование.
2014/12/16 19:30:00.000|       |SLS_RIH5@FORTS_test account|Стратегия останавливается. [0,1]. Позиция -1.
2014/12/16 19:30:00.000|       |SLS_RIH5@FORTS_test account|Ожидание снятия всех активных заявок.
2014/12/16 19:30:00.000|       |SLS_RIH5@FORTS_test account|Стратегия остановлена. [0,1]. Позиция -1.
2014/12/16 19:35:00.000|       |SS_RIH5@FORTS_test account|Новая свеча 12/16/2014 19:30:00 +03:00: 68600;70340;68590;69400; объем 8514
............................
2014/12/16 23:45:00.000|       |SS_RIH5@FORTS_test account|Новая свеча 12/16/2014 23:40:00 +03:00: 67230;67620;67160;67600; объем 273
2014/12/17 00:00:00.000|       |HistoryEmulationConnector|Изменение состояния эмуляции Started -> Stopping
2014/12/17 00:00:00.000|       |HistoryEmulationConnector|Изменение состояния эмуляции Stopping -> Stopped

**Comment by pikcher56** [comment]
Из-за того, что позиция не закрывается по основной стратегии при закрытии позиции по дочерней, невозможно тестировать

**Comment by Sergey-Dvortsov** [comment]
Проблема была связана, с тем что дочерняя стратегия удалялась, до момента прихода сделки, в результате "дочерние" сделки не поступали на обработку в "родительскую" стратегию. Решение в применении флага WaitAllTrades = true для дочерней стратегии.. Но в этом случае необходимо фильтровать "дочерние" сделки в событии WhenNewMyTrades родительской стратегии...
