### ISSUE TITLE
Пожелание по добавлению инструментов вручную для Blackwood

### ISSUE THREAD

**Issue by viosee** [stocksharp/stocksharp#18]
В данный момент инструменты для торговли добавляются автоматически при появлении каких-либо данных с них.
Просьба добавить в коннектор функцию наподобие такой:
Security AddSecurity(string security, string board)
Пример использования:
var newSec = Trader.AddSecurity("AAPL", "BATS");
Функция добавляет инструмент AAPL с площадкой BATS в список Trader.Securities если его там нет, саму площадку в список Trader.ExchangeBoards если ее там нет, зажигает соответствующие события и возвращает этот инструмент.
Нужна данная функция, чтобы этот инструмент впоследствии можно было использовать в торговле, отправлять на него ордера, и они корректно обрабатывались системой, по ним приходили события об изменении, трейды и прочее.
Вместе с этим просьба убрать существующие ограничения на отправку ордеров на произвольные площадки, такие например как NSDQ, STOP и др.

**Comment by mikasoukhov** [comment]
Противоречит дизайну.
