### ISSUE TITLE
Невозможно установить в VS2015 через Nuget

### ISSUE THREAD

**Issue by AlexNirX** [StockSharp/StockSharp#188]
Ошибка 

Could not install package 'StockSharp 4.3.13'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by osya** [comment]
This problem discussed here https://github.com/NuGet/Home/issues/1542

**Comment by egorpavlikhin** [comment]
The issue is with how this package was created, it should be exactly here.

**Comment by osya** [comment]
Mikhail Soukhov decided it shouldn't be here
