### ISSUE TITLE
S#.Studio отображение сделок при тестировании

### ISSUE THREAD

**Issue by MozGangster** [StockSharp/StockSharp#2]
В S#.Studio при тестировании, стандартной стратегии сделанной в дизайнере, на данных локального хранилища скачанного при помощи Гидры с Финнама. Сделки проходят и отображаются с опозданием в 7 часов (разница времени с Москвой). 
Скрин: http://clickscreen.ru/screens/4/52c3f794.png
На форуме: http://stocksharp.com/forum/yaf_postst5443findunread_Tiestirovaniie-v--S--Studio.aspx#post34350

**Comment by mikasoukhov** [comment]
Нужны данные.

**Comment by MozGangster** [comment]
Все данные выложил на форуме, если еще какие нибудь надо, подскажите
http://stocksharp.com/forum/yaf_postsm34365_Tiestirovaniie-v--S--Studio.aspx#34365
