### ISSUE TITLE
Маркер не обновляется при обновлении свечки на графике

### ISSUE THREAD

**Issue by RomSunZ** [StockSharp/StockSharp#20]
Пример Quik SampleCandles при обновлении свечки в реальном времени маркер не обновляется:
![11](https://cloud.githubusercontent.com/assets/10460695/6199024/ae4054b6-b452-11e4-86cc-bec73abe73c2.jpg)

**Comment by mikasoukhov** [comment]
Что такое маркер?

**Comment by RomSunZ** [comment]
значение Close свечки на оси Y не обновляется

**Comment by mikasoukhov** [comment]
https://github.com/StockSharp/StockSharp/commit/aa97beb02d8587ea4f7871a2c52201b26e59f263
