### ISSUE TITLE
Повторная загрузка сделок/стаканов по окончании дня.

### ISSUE THREAD

**Issue by ingler-ok** [StockSharp/StockSharp#207]
Версия s#: 4.3.13

При тестировании на истории (HistoryEmulationConnector) вместо загрузки сделок нового дня, дублируется загрузка сделок текущего дня, при этом тестирование останавливается. В логи печатается ошибка (ниже привел).

Настройки HistoryEmulationConnector
<pre>
connector = new HistoryEmulationConnector(
                new[] { selected_security },
                new[] { selected_portfolio })
            {
                Name = "Connector#" + index.ToString(),

                EmulationAdapter =
                {
                    Emulator =
                    {
                        Settings =
                        {
                            Latency = TimeSpan.FromMilliseconds(int.Parse(htw.tb_Latency.Text)),
                        },
                    }
                },

                HistoryMessageAdapter =
                {
                    StorageRegistry = new StorageRegistry { DefaultDrive = new LocalMarketDataDrive(htw.path_to_historical_data) },
                    StartDate = gs.startTime,
                    StopDate = gs.stopTime,
                    Name = "HistoryMessageAdapter# " + index.ToString(),
                },
            };
</pre>

<pre>
Суммарное число дней: 2. Ожидаемая продолжительность вычислений: 33,1 мин. (0,6 ч.)
Connector#0 подключен. Запуск стратегии Str#0
FileAccess (Load): C:\Users\inglerok\Documents\Visual Studio 2013\Projects\Nadejda_AI\Nadejda_AI\Hydra_data\R\RIH6@FORTS\2016_01_21\quotes.bin
FileAccess (Load): C:\Users\inglerok\Documents\Visual Studio 2013\Projects\Nadejda_AI\Nadejda_AI\Hydra_data\R\RIH6@FORTS\2016_01_21\trades.bin
<b>FileAccess (Load): C:\Users\inglerok\Documents\Visual Studio 2013\Projects\Nadejda_AI\Nadejda_AI\Hydra_data\R\RIH6@FORTS\2016_01_21\quotes.bin
FileAccess (Load): C:\Users\inglerok\Documents\Visual Studio 2013\Projects\Nadejda_AI\Nadejda_AI\Hydra_data\R\RIH6@FORTS\2016_01_21\trades.bin</b>
Str#0 остановлена. Запуск очистки памяти...
Время старта 2016-01-26 14:00:03. Время финиша: 2016-01-26 14:00:29, продолжительность вычислений: 00:00:21.96
</pre>

Логи:
<pre>
0001/01/01 00:00:00.000|       |HistoryMessageAdapter# 0|Loading 21.01.2016 0:00:00 Events: 7
2016/01/21 10:56:00.187|Error  |HistoryBasketMessageAdapter|System.InvalidOperationException: Не найден подходящий адаптер для MarketData.
   в StockSharp.Algo.BasketMessageAdapter.OnSendInMessage(Message message)
   в StockSharp.Messages.MessageAdapter.SendInMessage(Message message)
2016/01/21 10:56:00.187|Error  |HistoryBasketMessageAdapter|System.InvalidOperationException: Не найден подходящий адаптер для MarketData.
   в StockSharp.Algo.BasketMessageAdapter.OnSendInMessage(Message message)
   в StockSharp.Messages.MessageAdapter.SendInMessage(Message message)
2016/01/21 10:56:00.187|Error  |HistoryBasketMessageAdapter|System.InvalidOperationException: Адаптер для работы с портфелем TestingPortfolio#0 не найден.
   в StockSharp.Algo.BasketMessageAdapter.ProcessPortfolioMessage(String portfolioName, Message message)
   в StockSharp.Algo.BasketMessageAdapter.OnSendInMessage(Message message)
   в StockSharp.Messages.MessageAdapter.SendInMessage(Message message)
2016/01/21 10:56:00.187|Error  |Connector#0|System.InvalidOperationException: Адаптер для работы с портфелем TestingPortfolio#0 не найден.
   в StockSharp.Algo.BasketMessageAdapter.ProcessPortfolioMessage(String portfolioName, Message message)
   в StockSharp.Algo.BasketMessageAdapter.OnSendInMessage(Message message)
   в StockSharp.Messages.MessageAdapter.SendInMessage(Message message)
2016/01/21 10:56:00.187|Error  |HistoryBasketMessageAdapter|System.InvalidOperationException: Не найден подходящий адаптер для MarketData.
   в StockSharp.Algo.BasketMessageAdapter.OnSendInMessage(Message message)
   в StockSharp.Messages.MessageAdapter.SendInMessage(Message message)
2016/01/21 10:56:00.187|Error  |HistoryBasketMessageAdapter|System.InvalidOperationException: Не найден подходящий адаптер для MarketData.
   в StockSharp.Algo.BasketMessageAdapter.OnSendInMessage(Message message)
   в StockSharp.Messages.MessageAdapter.SendInMessage(Message message)
2016/01/21 10:56:00.187|Error  |HistoryBasketMessageAdapter|System.InvalidOperationException: Не найден подходящий адаптер для MarketData.
   в StockSharp.Algo.BasketMessageAdapter.OnSendInMessage(Message message)
   в StockSharp.Messages.MessageAdapter.SendInMessage(Message message)
</pre>

**Comment by mikasoukhov** [comment]
Пример SampleHistTesting работает. У вас какие-то модификации?
