### ISSUE TITLE
Класс BlackScholes не позволяет получить Implied Volatily и греков

### ISSUE THREAD

**Issue by oshkalo89** [StockSharp/StockSharp#216]
BlackScholes blackScholes = new BlackScholes(OptionSecurity.SelectedSecurity, OptionSecurity.SecurityProvider, Trader);
decimal a = 0;
a = (decimal)blackScholes.ImpliedVolatility(DateTimeOffset.Now);

При запросе волатильности (впрочем, как и греков, и даты экспирации по контракту) всегда возвращает null.

**Comment by mikasoukhov** [comment]
Скорее всего дело в неправильных настройках. БС - это алгоритм. Что-то не то идет на вход.
