### ISSUE TITLE
Заявленные данные не выгружаются из Quik для опционов

### ISSUE THREAD

**Issue by oshkalo89** [StockSharp/StockSharp#217]
В описании класса Security есть заявленные поля "TheorPrice" и "ImpliedVolatility".
При запросе данных из коннектора Quik (Lua подключение), значения возвращают null. 
decimal a =0;
a = (decimal)MainWindow.Instance._optionsWindow.OptionSecurity.SelectedSecurity.TheorPrice;
a = (decimal)MainWindow.Instance._optionsWindow.OptionSecurity.SelectedSecurity.ImpliedVolatility;

При этом другие данные, такие как Strike либо ExpiryDate приходят нормально.

**Comment by dmDen** [comment]
Проверил у себя, данные приходят.
