### ISSUE TITLE
ChartPanel - кривая индикатора на графике "убегает" вперед

### ISSUE THREAD

**Issue by techno1d** [StockSharp/StockSharp#220]
При передаче в ChartIndicatorElement значения индикатора IIndacatorValue, у которого IsFinal = false иногда не обновляет значение кривой, а рисует новое значение, в следствие чего кривая убегает вперед. Поймать момент, в который это происходит не получилось. Точно могу сказать, что IsFinal = true в метод не передавалось. (Окончательное значение индикатора рисуется другим методом вместе с другими кривыми)
UPD: поведение графика стало таким после перехода на последний релиз (4.3.14)

**Comment by mikasoukhov** [comment]
Если нет возможности воспроизвести, тогда закрываю багу.
