### ISSUE TITLE
Проблема создания стоп заявки коннекторе Transaq

### ISSUE THREAD

**Issue by lromanb** [StockSharp/StockSharp#226]
Добрый день
С использованием примера S#.Api была предпринята попытка создания take profit заявки, но заявка не доходит до сервера Транзак, что подтверждено службой поддержки Финам на основании лога
![pic2](https://cloud.githubusercontent.com/assets/18715198/14879173/7e942a48-0d49-11e6-9889-18b16b217b4e.JPG)
![pic1](https://cloud.githubusercontent.com/assets/18715198/14879183/8630a268-0d49-11e6-97e5-a93e29ec7567.JPG)

[20160426_xdf.txt](https://github.com/StockSharp/StockSharp/files/240055/20160426_xdf.txt)

 из примера.
Прикладываю лог и снимки экрана.
в файле 20160426_xdf.txt содержится zip архив (нужно его переименовать), т.к. почему-то с расширением zip закачать сюда его не удалось

**Comment by mikasoukhov** [comment]
Не воспроизводиться.
