### ISSUE TITLE
Некорректный расчет заблокированной суммы при тестировании на акциях

### ISSUE THREAD

**Issue by evgorshkov** [StockSharp/StockSharp#227]
При тестировании на акциях после закрытия ранее открытой позиции в классе PortfolioEmulator некорректно рассчитывается значение поля _blockedValue. Оно не обнуляется, что приводит к тому, что полученная сумма убытка от первой сделки купли / продажи акции учитывается дважды в методе CheckRegistration при попытке открыть новую позицию. Первый раз - как уменьшенная текущая сумма портфеля, второй раз - как не обнуленное значение поля _blockedValue.
В результате в определенных случаях может некорректно появиться ошибка недостаточности денег в портфеле.
Проблема не возникает, если тестирование выполняется на инструментах, для которых заданы свойства MaginBuy и MarginSell.
Некорректную работу можно увидеть в стандартном примере тестировщика SampleHistoryTestingPublic, если доработать его для тестирования на акциях, убрать заполнение свойств MarginBuy и MarginSell и установить точку прерывания в методе CheckRegistration класса PortfolioEmulator в строке с проверкой if ((_currentValue - _blockedValue) < needBlock).

**Comment by mikasoukhov** [comment]
Как воспроизвести проблему?

Момент с указывание внутренних кодов. Код на гитхабе частично не совпадает с релизом. Поэтому воспроизведение с указанием строчек кода внутри S# невозможно.

**Comment by evgorshkov** [comment]
Проблема выявлена на основе кода, выложенного на гитхаб.
Воспроизвести проблему можно следующим образом:
Изменить SampleHistoryTestingPublic таким образом, чтобы он открывал позиции только в лонг и на всю текущую сумму портфеля. Плюс убрать заполнение свойств MarginBuy и MarginSell.
Если по итогам первой операции купли / продажи будет получен убыток, то при попытке открыть новую позицию на всю сумму портфеля (без его превышения) вылетит ошибка недостаточности денег на счете.

**Comment by mikasoukhov** [comment]
Это правильное поведение. Если вы только в лонг открыли, то у вас заблокировали сумму.

**Comment by evgorshkov** [comment]
Нет. Если мы только открыли позицию - то сумма заблокирована, это конечно правильно. Но если мы купили, а потом продали весь купленный объем, пусть и в убыток, то никакой заблокированной суммы у нас быть не должно. А она есть.
На примере, сейчас получается так:
Купили 10 штук по 15 рублей - заблокирована сумма 150 рублей.
Продали 10 штук по 14 рублей - в портфеле 140 рублей и 10 рублей еще заблокировано.
В момент следующей покупки почему-то будет разрешено потратить только 140-10=130 рублей.

Вопрос, почему эти 10 рублей блокируются при нулевой открытой позиции?

**Comment by mikasoukhov** [comment]
Вы же пишите что стратегия только от лонга работает. Как она может продать?

**Comment by evgorshkov** [comment]
Что значит "как она может продать"?
Закрывать то открытую в лонг позицию как? Есть другой способ кроме продажи?

**Comment by mikasoukhov** [comment]
Вы выше написали фразу "Изменить SampleHistoryTestingPublic таким образом, чтобы он открывал позиции только в лонг".

Пришлите, пожалуйста, измененный пример с комментариями, чтобы можно было понять о чем речь и воспроизвести проблему, если она есть.

**Comment by evgorshkov** [comment]
[SampleHistoryTesting.zip](https://github.com/StockSharp/StockSharp/files/253582/SampleHistoryTesting.zip)
Замените приложенные в архиве файлы в папке SampleHistoryTesting. Пример сделан на основе текущих исходников, выложенный на гитхабе.
В местах изменениях сделаны комментарии, что именно изменено. 
Кроме изменений самой стратегии изменены параметры тестирования:
- сумма портфеля установлена в значение 150500;
- Не заполняются свойства MaginBuy и MarginSell, чтобы сэмулировать торговлю акциями.
Воспроизводить следующим образом:
1. Поставить точку прерывания в 123 строке файла SmaStrategy (где выставляется заявка).
2. Запустить тестирование на основе тиков. Другие параметры изменять не нужно.
3. При первой остановке будет выставлена заявка на покупку 1 штуки по цене 150400. Заявка будет исполнена по цене 150382. Position = 1. Portfolio.CurrentValue = 117.99.
4. При второй остановке будет выставлена заявка на продажу 1 штуки (закрытие позиции) по цене 149670. Заявка будет исполнена по цене 149670. Position = 0. Portfolio.CurrentValue = 149787.98.
5. При третьей остановке будет осуществлена попытка выставления заявки на покупку 1 штуки по цене 149360. Заявка выставлена не будет (State=Failed). В логе появится запись: "Заявка 8 не зарегистрирована. Причина 'На счету test account недостаточно денег для регистрации заявки 8. Необходимо 149360, имеется 149787.98, заблокировано 730.".

Вопрос: откуда взялась эта блокировка 730, если текущих открытых позиций нет, и почему заявка, выставляемая в 5 пункте, в итоге выставлена не была?

**Comment by evgorshkov** [comment]
Похоже, что проблема ушла только частично.
Именно из-за полученного убытка лишней блокировки нет.
Но похоже, что есть лишняя блокировка из-за разницы в цене заявки и в реальной цене исполнения.
![ss_20160527](https://cloud.githubusercontent.com/assets/18752614/15597431/e19249ce-23e0-11e6-8e23-749ffd9e57be.PNG)
На приложенном скриншоте видно, что после исполнения третьей сделки на покупку по цене 149360 заблокированная сумма стала равна 149378. Почему? Причем разница очень похожа на разницу в цене заявки и цене исполнения первой заявки на покупку. Интересно, что после первой сделки на покупку (когда эта разница реально была получена), лишней блокировки не было.
Причем после поступления следующей сделки на продажу - четвертой (то есть Position станет равным 0), блокировка в 18 рублей останется висеть.

Пример абсолютно то тот же самый, только нужно дать исполниться третьей заявке.

Не пойму, можно ли заново открыть эту ветку, поэтому если нужно, могу создать новую ветку обсуждения.

**Comment by mikasoukhov** [comment]
Я восстановил ишью. Нужно опять пример для воспроизведения ошибки. Тот, что был ранее, не выдает проблемы.

**Comment by evgorshkov** [comment]
Погонял еще. Блокируемая сумма остается висеть, но она теперь не мешает выставлению заявок. Если само по себе наличие ненулевой блокированной суммы при Strategy.Position=0 не является ошибкой, то данное обращение можно закрыть. Если же это все-таки ошибка, то напишите - я все-таки выложу новый пример.

**Comment by mikasoukhov** [comment]
Сумма же блокируется не только при позиции. При выставленных заявках так же идет блокировка (обеспечение).

Я закрываю ишью. Если будут новые подробности - восстановлю.
