### ISSUE TITLE
Некорректная проверка на рабочее время площадки для периодов с различным смещением времени относительно UTC

### ISSUE THREAD

**Issue by evgorshkov** [StockSharp/StockSharp#228]
При построении свечей на основе тиковых данных для периодов с различным смещением времени относительно UTC (например, 2012-2013 годы), выполняется некорректная проверка на рабочее время площадки.

При обработке данных, полученных из источника все временные данные прогоняются через метод Ecng.Common.TimeHelper.ApplyTimeZone, который несмотря на то, что ему на вход подается временная зона +3 (TimeHelper.Moscow), на выходе для рассматриваемых годов возвращает смещение (Offset) +4. Например, при обработке часовой свечи с 10 часов за 2013 год на выходе после работы этого метода время свечи окажется равным 6 часов +4.

В последствии при построении свечей  в методе TraderHelper.IsTradeTime выполняется проверка на рабочее время биржи. В нем вызывается метод Ecng.Common.TimeHelper.ToLocalTime, которому также на вход подается временная зона +3, но этот метод в отличии от ApplyTimeZone специфику рассматриваемых годов не учитывает. В результате свеча с временем 6 часов +4 будет конвертирована во время 9 часов, что для ММВБ является нерабочим временем.

Результатом такого подхода является то, что тиковые данные обрабатываются нормально, а первые свечи каждого дня - не обрабатываются вообще.

Проверить можно загрузив тиковые данные через гидру за 2013 год (например с финама по лукойлу) и прогнав их в стандартном тестировщике SampleHistoryTesting на основе тиковых данных. Первая свеча каждого дня будет игнорироваться.

**Comment by mikasoukhov** [comment]
Что значит первая свеча "игнорируется"? Она не поступает в код? По ней не выставляются заявки? Не происходит расчет индикаторов?

Просьба приложить исторические данные, на которых можно воспроизвести ошибку.

**Comment by evgorshkov** [comment]
[LKOH@TQBR.ZIP](https://github.com/StockSharp/StockSharp/files/251522/LKOH.TQBR.ZIP)
Приложил тиковые данные по акциям лукойла за июль-август 2013 года.
Данные закачаны через гидру с финама.

В стандартном примере тестирования SampleHistoryTesting при прогоне на тиках по всем свечам, у которых после конвертации времени в локальное время биржи в методе TraderHelper.IsTradeTime время начала свечи окажется меньше 10 часов не вызовется метод SmaStrategy.ProcessCandle. То есть до конвертации времени он было 6 +4 (то есть в локальном выражении - должно быть 10 часов), а после конвертации в локальное время биржи (с помощью метода Ecng.Common.TimeHelper.ToLocalTime) окажется не 10 часов, а 9.

**Comment by mikasoukhov** [comment]
О какой конвертации идет речь? Данные как-то изменены вами после скачивания Гидрой?

**Comment by evgorshkov** [comment]
Нет, данные никак не изменены.
Под конвертацией имелся в виду вызов метода Ecng.Common.TimeHelper.ToLocalTime из метода TraderHelper.IsTradeTime.

**Comment by mikasoukhov** [comment]
Не воспроизводиться. Все свечи приходят в обработчик. Или я не так понял описание проблемы.

**Comment by evgorshkov** [comment]
Вы на приложенном данных запускали? На тиковых данных или на свечах?

**Comment by mikasoukhov** [comment]
Да, на выложенных выше файлах. Свечи строились из тиков.

**Comment by NikolayFlerov** [comment]
Приветствую, Михаил и Евгений!) 
Похожая проблема и в гидре и при построении своих свечек - 
http://prnt.sc/b65zhs 
Эта проблема появляется при переходе/ не переходе на летнее/зимнее время. 
Данные - тики с биржи, могу приложить!

**Comment by evgorshkov** [comment]
[Testing.ZIP](https://github.com/StockSharp/StockSharp/files/290332/Testing.ZIP)
Протестировал еще раз на текущих исходниках, выложенных на гитхаб. Проблема воспроизводится. Подготовил пример, его нужно распаковать в папку Testing - добавятся данные для тестирования и заменятся файлы в SampleHistoryTesting.
Данные те же, что были выложены ранее.
Стратегия SmaStrategy взята из примера к багу с неправильным расчетом позиции. Также в метод OnStarted добавлена подписка на Security.WhenNewTrades.

Воспроизводить следующим образом:
1. Поставить точку прерывания в строку 82 файла SmaStrategy (срабатывание правила Security.WhenNewTrades) и в строку 92 (срабатывание метода ProcessCandle).
2. Запустить пример, отметить галкой "Тики".
3. Первая остановка произойдет в правиле WhenNewTrades. Убедиться, что время сделок в коллекции trades 9.59. (Откуда финам взял такие сделки - отдельный вопрос.)
4. Продолжать выполнение, пока не произойдет остановка на сделках, со временем более 10 часов. Убедиться, что сделки за период с 10 до 11 часов поступают корректно.
5. Убрать точку прерывания в строке 82.
6. Следующая остановка произойдет в методе ProcessCandle. Убедиться, что время свечи с 11 часов до 11.04.59. Вопрос: почему не происходило остановок в этом методе на свечах с 10 до 11 часов?

**Comment by evgorshkov** [comment]
Насколько я понимаю - проблема в неправильном формировании свойства ExchangeBoard.TimeZone у всех Российских площадок, а именно тех, которым присвоено значение переменной moscowTime, определенной в 319 строке файла ExchangeBoard_Instances.cs.
Эта переменная формируется с помощью десериализации строки, игнорируя таким образом корректные временные настройки, которые присутствуют в операционной системе.
На следующем скриншоте видна сформированная переменная moscowTime. Видно, что в этой переменной всего 3 правила корректировки времени (m_adjustmentRules):
![stocksharp](https://cloud.githubusercontent.com/assets/18752614/16179152/83ea7a12-366e-11e6-86db-d08c51d36223.PNG)
На самом деле их на данный момент должно быть 5. Вот что выдает вызов стандартного TimeZoneInfo.FindSystemTimeZoneById("Russian Standard Time"):
![windows10](https://cloud.githubusercontent.com/assets/18752614/16179241/ce90d6c2-3670-11e6-8daa-5220d7e33143.PNG)
Дополнительно информация об изменениях:
http://www.timeanddate.com/time/zone/russia/moscow

Изменение способа формирования переменной moscowTime решает описанную в issue проблему. Я предполагаю, что выбранный способ формирования этой переменной (через десериализацию) скорее всего был выбран не случайно, но тогда десериализируемая строка должна содержать все правила корректировки времени. 
Если я правильно понял проблему - исправьте, пожалуйста.

**Comment by mikasoukhov** [comment]
Актуально ли проблема на текущий день в последней версии?
