### ISSUE TITLE
Quik lua - Процесс подключения был прервал из-за неожиданного отключения

### ISSUE THREAD

**Issue by RomSunZ** [stocksharp/stocksharp#23]
Пример Quik Sample, stocksharp 4.2.64. При попытке запроса Level1 по инструменту возникает ошибка:  Процесс подключения был прервал из-за неожиданного отключения.
Логи приложена на форуме в сообщении http://stocksharp.com/forum/yaf_postsm34651_Quik--System-InvalidOperationException-occurred.aspx#post34651

**Comment by mikasoukhov** [comment]
Не воспроизводится.
