### ISSUE TITLE
Сборка проекта - does not exist ...

### ISSUE THREAD

**Issue by terpoofvikt** [StockSharp/StockSharp#232]
```
git checkout -qf 4826cbcd40d78b80e9782681fb723b9f4702ba50
msbuild.exe StockSharpAPI.sln /verbosity:minimal /m:8 /p:Configuration=Debug
```
[build-log.zip](https://github.com/StockSharp/StockSharp/files/275890/build-log.zip)

Не собирается из-за множественых "... does not exist". А такие вещи меня вообще пугают `..\..\..\..\`.

В IDE аналогично. 

C бисекциональным поиском (last good попался случайный e125173) нашел последний мне известный коммит на котором все успешно собирается это - 054e8a5b5e78710c02b5623a2073168351df2d91 - **тут все собирается ОК**

У вас есть CI сервер для непрерывной интеграции ? не может быть чтобы больше ~160 коммитов тянулись ошибки сборки для настроек по умолчанию о_О
или я такой особенный ? или есть где инфа по кастомной сборке спец. под ваш проект ?

поправьте пожалуйста, т.к. на первый взгляд тяжело с ориентироваться где тут что находиться в особенности когда ничего не работает. да и дельта очень большая

Спасибо

**Comment by terpoofvikt** [comment]
ах да, уточню вот еще что :)

почему не проще подправить все самостоятельно постороннему человеку:

* После 054e8a5 идет 762d751 он не собирается с уже другой проблемой:

```
  MainWindow.xaml(50,20): error MC3050: не удается найти тип "Theme". Имена типов вводятся с учетом регистра букв. 
```  
  
В a3b759d к нему прибавляется еще несколько проблем:

```
ChartWindow.xaml.cs(50,5): error CS0117: "ChartCandleElement" не содержит определение для "AntiAliasing". [D:\tmp\StockSharp\Samples\OpenECry\SampleOEC\SampleOECPublic.csproj]
ChartWindow.xaml.cs(50,5): error CS0117: "ChartCandleElement" не содержит определение для "AntiAliasing". [D:\tmp\StockSharp\Samples\Blackwood\SampleBlackwood\SampleBlackwoodPublic.csproj]
ChartWindow.xaml.cs(50,5): error CS0117: "ChartCandleElement" не содержит определение для "AntiAliasing". [D:\tmp\StockSharp\Samples\Rithmic\SampleRithmic\3ckhc3tb.tmp_proj]  
...
```

**В ближайших Build fix** ( 2c6dafd ) добавляются еще проблемы!

```
Microsoft.WinFx.targets(268,9): error MC1000: Неизвестная ошибка сборки, "Невозможно разрешить зависимую сборку для сборки "DevExpress.Data.v15.2, Version=15.2.7.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a", поскольку она не была предварительно загружена. При использовании API-интерфейсов ReflectionOnly зависимые сборки необходимо предварительно загружать или загружать по запросу при возникновении события ReflectionOnlyAssemblyResolve."  
```

и далее снежным комом к HEAD, за минусом имеющихся разумеется.

+ также между обозначенными 2-мя коммитами на которых все собирается (054e8a5 и e125173): есть также много аналогичных fail

Вчера тупо сидел и пытался понять что за черный юмор такой, когда уже с бисекциональным поиском проходил, те на которых собиралось нормально:

* 054e8a5, 0390fed, 8027b6d, d4a9073, e125173

Все это конечно жутко забавно, но вам просто жизнено необходим CI, чтобы контроллировать культуру коммитов -_- 

*а вот так #113 поступать некрасиво*

**Comment by terpoofvikt** [comment]
:rooster:

эх, отсутствует добрая часть вещей и сделано это намеренно.
сейчас спустился ниже к 4.3.13 проектов в решении увеличилось до 117 с 59 ( 49 из которых, уже обратил внимание, это Samples, + оставшиеся Logging, Localization,... )

шутку оценил  :laughing:  :grinning:
так бы и написали, что было принято решение, что StockSharp больше не opensource, закрываем код, оставляем в основном только Samples. Хотя был ли он таковым ? я просто этот репо первый раз в глаза вижу :) сейчас же это слишком обманчивая информация по StockSharp проекту :ghost:

по большей части интересует только реализация прослоек для программного доступа к терминалам. Все остальное ручками. И к примеру, чтобы не заморачиваться с qlua для квика, а собственный адаптер на трансляцию команд с 0 писать это доп. время, хочется быстрый старт. Тем более когда тебе предлагают унифицированный слой по работе с различными терминалами 

ладно, поковыряю ваши старые коммиты может чего интересного найду... и было ли здесь изначально что-то 

никто не знает, для StockSharp.QuikLua.dll были реализации в открытом доступе ? доступные альтернативы ?

**Comment by mikasoukhov** [comment]
Используйте официальные релизы, если есть проблемы с компиляцией.

**Comment by terpoofvikt** [comment]
только вот кроме Samples компилировать нечего :laughing: 

зря вы так, мне кажется обширный community помог бы быстро развиться в действительно классную штуку, которой бы пользовались и знали во всем мире, ну и я чем-нибудь подсобил бы (C#, Java, C++ и кое-что еще на мне уже долгие годы). Идея-то действительно шикарная, жаль конечно, но ладно, у каждой компании свои стратегии развития.

для StockSharp.QuikLua.dll были реализации в открытом доступе ?

**Comment by mikasoukhov** [comment]
Репозитарий на гите уже больше года. Ничего даже близко от обширного комьюнити не получилось. Причем англоязычные трейдеры были более отзывчивы в работе, чем русскоязычные.

Пишите на форум. Сейчас вы пишите в наш багтрекер.

**Comment by terpoofvikt** [comment]
> Репозитарий на гите уже больше года. Ничего даже близко от обширного комьюнити не получилось.

Это скорее вопрос именно в "подачи" и позиционирования продукта. Если есть потребность в том что вы предлагаете, и имеются нормальные условия для комьюнити в развитии проекта, то те кто может чем-нибудь помочь, разумеется помогут, т.к. мы все заинтересованы в улучшениях. *Это же элементарное обслуживание машины, на которой ты до работы добираешься.*

Например, самое минимальное, то как принимаются пул-реквесты, **и полностью открытый код!** а не ~ "что-то где-то открыто, и будьте благодарны что есть хоть это...". Результаты вполне очевидны, но у каждого свои планы и стратегии.

Где к примеру реализация **StockSharp.QuikLua.dll** ?! с самого первого коммита в этом репо, на исходники не было и намеков. (ничего не нашел)
как я могу работать с этим проектом, доверять ему, и уж тем более развивать его, если это ни разу не опенсурс ? Спросите ваше руководство.
просто еще одна закрытая прослойка со своим API под который также нужно подстраиваться и верить что все будет ок в будущем.

Если же предлагается сугубо специализированные комплексные компоненты такие как S# Studio и т.п. то вполне очевидно что не всем это нужно изначально, да и конкуренция в этой сфере также немаленькая, хоть и у других все закрыто изначально, но предлагать дорабатывать кусочки вашего инструментария только с частично открытым кодом, это кому как наверное.

ваш выбор, но спасибо за попытку быть хотя бы частично открытыми!


> Причем англоязычные трейдеры были более отзывчивы в работе, чем русскоязычные.

*а это повальная беда нашего сегмента, я уже давно забил на эту отзывчивость и большая часть вещей (вопросы, проекты, обсуждения) просто перешла на англоязычный сегмент, где также встречаются наши, но как-то более культурно все получается. Никто не пытается послать куда подальше, все стараются помочь друг-другу, чудеса... но как-то печально.*

**Comment by mikasoukhov** [comment]
1. Обсуждение на форуме. Если будете оффтопить, вы будете заблокированы для ишью раздела.
2. Приводите ссылки на ваши проекты, которые вы лично сами организовали. Чтобы показать, что вы не очередной советчик из интернета, а человек, за плечами которого есть реальный опыт.

**Comment by terpoofvikt** [comment]
ого, ну тогда все с вами понятно.

Информация в этом **issue** как раз **строго по теме - почему не собирается проект** и что за ошибки ! т.к. для тех кто в первый раз видит этот проект будет также озадачен, что происходит, и почему не работает, т.к. здесь ничего нет (после 4.3.13), а чего-то не было изначально - как **StockSharp.QuikLua.dll**, который просто копируется в каталог:

```
  \StockSharp\Hydra\Plugins\Quik\Quik.csproj
	Line 120: copy ..\..\..\..\..\Connectors\Quik\Lua\StockSharp.QuikLua.dll ..\..\..\..\Hydra\bin\$(ConfigurationName)\Plugins\StockSharp.QuikLua.dll
  \StockSharp\Hydra\Plugins\Quik\QuikPublic.csproj
	Line 115: copy ..\..\..\..\..\Connectors\Quik\Lua\StockSharp.QuikLua.dll ..\..\..\..\Hydra\bin\$(ConfigurationName)\Plugins\StockSharp.QuikLua.dll
```

с вами по существу, а вы задом, да и еще угрожают, и доказательства какие-то требуют, вы о чем о_о 

все, мой **вопрос окончательно решен**, спасибо, до свидания.
