### ISSUE TITLE
Неправильное запись данных в хранилище с отрицательным смещением времени 

### ISSUE THREAD

**Issue by Sergey-Dvortsov** [StockSharp/StockSharp#233]
При записи данных в хранилище с отрицательным смещением времени в хранилище неправильно создаются папки дат. Например, при записи биржевых данных с CME (смещение времени -5), данных за 23.05.2016 папка со следующей датой (24.05.2016) создается в 22:00 23.05.2016 по Москве, а должна создаваться в 8:00 следующего дня...

**Comment by mikasoukhov** [comment]
Папки создаются с временной меткой в формате UTC.
