### ISSUE TITLE
Не все сборки компилируются

### ISSUE THREAD

**Issue by stanislav-111** [StockSharp/StockSharp#234]
Пытаюсь скомпилировать проект под VC 2015 в Debug. Убрал компилирование всех Sample проектов, остались только 10 проектов API. 2 из них не хотят компилироваться выдаются следующие ошибки и warning'и:

> 3>C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.WinFx.targets(268,9): error MC1000: Unknown build error, 'Cannot resolve dependency to assembly 'DevExpress.Data.v15.2, Version=15.2.7.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a' because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.' 

> 36>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '..\..\StockSharpApps\Connectors\AlfaDirect\AlfaDirect.csproj' does not exist.
> 36>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '..\..\StockSharpApps\Connectors\BarChart\BarChart.csproj' does not exist.
> 36>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '..\..\StockSharpApps\Connectors\BitStamp\BitStamp.csproj' does not exist.
> 36>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '..\..\StockSharpApps\Connectors\Blackwood\Blackwood.csproj' does not exist.
> 36>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '..\..\StockSharpApps\Connectors\Btce\Btce.csproj' does not exist.
> 36>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '..\..\StockSharpApps\Connectors\CQG\CQG.csproj' does not exist.
> 36>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '..\..\StockSharpApps\Connectors\ETrade\ETrade.csproj' does not exist.
> 36>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '..\..\StockSharpApps\Connectors\InteractiveBrokers\InteractiveBrokers.csproj' does not exist.
> 36>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '..\..\StockSharpApps\Connectors\IQFeed\IQFeed.csproj' does not exist.
> 36>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '..\..\StockSharpApps\Connectors\LMAX\LMAX.csproj' does not exist.
> 36>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '..\..\StockSharpApps\Connectors\Oanda\Oanda.csproj' does not exist.
> 36>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '..\..\StockSharpApps\Connectors\OpenECry\OpenECry.csproj' does not exist.
> 36>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '..\..\StockSharpApps\Connectors\Rithmic\Rithmic.csproj' does not exist.
> 36>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '..\..\StockSharpApps\Connectors\Rss\Rss.csproj' does not exist.
> 36>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '..\..\StockSharpApps\Connectors\SmartCom\SmartCom.csproj' does not exist.
> 36>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '..\..\StockSharpApps\Connectors\Sterling\Sterling.csproj' does not exist.
> 36>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '..\..\StockSharpApps\Connectors\Transaq\Transaq.csproj' does not exist.
> 36>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '..\..\StockSharpApps\Xaml.Charting\Xaml.Charting.csproj' does not exist.
> 36>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '..\..\StockSharpApps\Xaml.Diagram\Xaml.DiagramPublic.csproj' does not exist.
> 36>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1611,5): warning : The referenced project '..\..\StockSharpApps\Xaml\Xaml.csproj' does not exist.
> 36>CSC : error CS0006: Metadata file 'K:\StockSharp\StockSharp\Connectors\Quik\bin\Debug\StockSharp.Quik.dll' could not be found

**Comment by stanislav-111** [comment]
Ах да забыл написать 3-ий проект это

> 3>------ Build started: Project: QuikPublic, Configuration: Debug Any CPU ------

А 36 проект это 

> 36>------ Build started: Project: ConfigurationPublic, Configuration: Debug Any CPU ------

То есть если правильно понимаю это урезанные версии. То есть урезанные версии не компилируются (ConfigurationPublic ,  QuikPublic ), а полные версии компилируются (все остальное).

**Comment by mikasoukhov** [comment]
http://stocksharp.com/forum/yaf_postst5977_Nashi-niesbyvshiiesia-Open-source-miechty.aspx

**Comment by stanislav-111** [comment]
Спасибо. А с какой версии вы урезали кол открытых проектов в solution ?

**Comment by mikasoukhov** [comment]
Вряд ли есть такой коммит. Процесс был растянут на месяцы.
