### ISSUE TITLE
Не правильно работает функция Strategy.ReRegisterOrder 

### ISSUE THREAD

**Issue by stanislav-111** [StockSharp/StockSharp#237]
Если я правильно понимаю два кода эквивалентны:

```
m_newOrder = m_Order.ReRegisterClone (dNewPrice);
base.CancelOrder (m_Order);
base.RegisterOrder (m_newOrder);
```

и  примерно такой же код содержится в примере Samples\Quik\SampleQuik\

```
m_newOrder = m_Order.ReRegisterClone (dNewPrice);		
base.ReRegisterOrder (m_Order, m_newOrder);
```

То есть создается новая заявка по цене dNewPrice, старая заявка убирается, а новая заявка регистрируется на бирже.

Но! Первый вариант работает, а второй вариант нет! Использую Quik Lua.

В log пишеться:

> Название Время	Тип	Сообщение
> myStrategy	03.06.2016 15:04:52 +03:00	Info	Стратегия Запущена. [0,-1]. Позиция 0.
> myStrategy	03.06.2016 15:04:54 +03:00	Info	Регистрация новой  (0x238866E) заявки на Buy с ценой 95,1001 и объемом 1. 
> myStrategy	03.06.2016 15:04:54 +03:00	Info	Новая позиция: (S#:SU25081RMFS9@TQOB, Native:,Type:Stock, 199999)=0.
> myStrategy	03.06.2016 15:04:54 +03:00	Info	Новая позиция: (S#:SU25081RMFS9@TQOB, Native:,Type:Stock, 199999)=0.
> myStrategy	03.06.2016 15:07:14 +03:00	Info	Перерегистрация заявки 54265917 (0x238866E) с ценой 95,1001 на цену 95,1003. 
> myStrategy	03.06.2016 15:07:17 +03:00	Error	Заявка 54265917 (0x238866E) не была отменена по причине System.InvalidOperationException:  ukazannaya tranzaktsiya po ukazannomu klassu ne naidena: "tqob"..
> myStrategy	03.06.2016 15:07:17 +03:00	Info	Заявка 54265922 (0xED43F5) больше не активна.
> myStrategy	03.06.2016 15:07:17 +03:00	Error	Заявка 54265922 (0xED43F5) не была зарегистрирована по причине ' ukazannaya tranzaktsiya po ukazannomu klassu ne naidena: "tqob".'.

а в log file lua пишется следующее:

> 2016/06/03 15:04:28.728|       |FixServer |From quik 127.0.0.1:4938: MarketDataRequest
> 2016/06/03 15:04:28.732|       |LuaServer |Request: Type = MarketData TrId = 54265916 Value =  SecId = S#:SU25081RMFS9@TQOB, Native:,Type: OrdType =  IsSubscribe = True DataType = MarketDepth
> 2016/06/03 15:04:54.141|       |FixServer |From quik 127.0.0.1:4937: NewOrderSingle
> 2016/06/03 15:04:54.143|       |LuaServer |Request: Type = OrderRegister TrId = 54265917 Value = t = {}
> t["ACCOUNT"] = "L01-00000000"
> t["CLASSCODE"] = "TQOB"
> t["SECCODE"] = "SU25081RMFS9"
> t["QUANTITY"] = "1"
> t["CLIENT_CODE"] = "199999"
> t["EXPIRY_DATE"] = "GTC"
> t["OPERATION"] = "B"
> t["TYPE"] = "L"
> t["ACTION"] = "NEW_ORDER"
> t["PRICE"] = "95,1001"
> t["EXECUTION_CONDITION"] = "PUT_IN_QUEUE"
> t["TRANS_ID"] = "54265917"
> return sendTransaction(t)
>  SecId =  OrdType = Limit IsSubscribe = False DataType = Level1
> 2016/06/03 15:05:26.623|       |FixServer |From quik 127.0.0.1:4938: TestRequest
> 2016/06/03 15:05:26.630|       |FixServer |From quik 127.0.0.1:4937: TestRequest
> 2016/06/03 15:06:26.624|       |FixServer |From quik 127.0.0.1:4938: TestRequest
> 2016/06/03 15:06:26.632|       |FixServer |From quik 127.0.0.1:4937: TestRequest
> 2016/06/03 15:07:17.704|       |FixServer |From quik 127.0.0.1:4937: OrderCancelReplaceRequest
> 2016/06/03 15:07:17.706|       |LuaServer |Request: Type = OrderReplace TrId = 54265922 Value = t = {}
> t["ACTION"] = "MOVE_ORDERS"
> t["CLASSCODE"] = "TQOB"
> t["SECCODE"] = "SU25081RMFS9"
> t["MODE"] = "1"
> t["FIRST_ORDER_NUMBER"] = "15111630571"
> t["FIRST_ORDER_NEW_PRICE"] = "95,1003"
> t["FIRST_ORDER_NEW_QUANTITY"] = "1"
> t["TRANS_ID"] = "54265922"
> return sendTransaction(t)
>  SecId =  OrdType =  IsSubscribe = False DataType = Level1
> 2016/06/03 15:07:17.709|Error  |LuaServer |Result:  Указанная транзакция по указанному классу не найдена: "TQOB".

Вот такие дела....

**Comment by risty** [comment]
на каких то площадках может не приниматься перерегистрация заявок одной транзакцией. поищите по форуму запросом RegisterOrder

**Comment by stanislav-111** [comment]
Я не знаком с протоколом биржи, но в Quik'e (функции которого фактически вызывает Lua коннектор) есть функция "Заменить заявку" которая нормально отрабатывает.

До пустим, на уровне протокола такой функции нет, а Quik ее реализовывает с помощью CancelOrder / RegisterOrder. Так что мешает также делать данному API ? Ведь библиотека рассчитана в первую очередь на трейдеров которые не являются профессиональными программистами , и скорей всего не понимают что код

```
m_newOrder = m_Order.ReRegisterClone (dNewPrice);
base.CancelOrder (m_Order);
base.RegisterOrder (m_newOrder);
```

Может привести к выполнению заявки в двойном объеме.  Поэтому было бы неплохо если бы API реализовывало правильно функцию замены заявки.

В самом крайнем случае - если данная функция не поддерживается для Quik Lua, нужно писать что функция не поддерживается при ее вызове, а не выводить кучу совершенно не связанных с проблемой ошибок.

Поймав серию ошибок в данном API резонно возникает вопрос - а у разработчиков вообще есть автоматические тесты для своего API ?!? Как вообще возможно что у библиотеке которой 5 лет, не работают ключевые функции ? Это я только попытался написать элементарного робота, и уже обнаружил 3 неработающие функции, что будет дальше я даже боюсь предположить....
