### ISSUE TITLE
Не возникает событие Connector.ConnectionError

### ISSUE THREAD

**Issue by Sergey-Dvortsov** [stocksharp/stocksharp#24]
При разрыве соединения не возникает событие Connector.ConnectionError. Тест проводился на примере Sаmple из поставки S#. Выдергивал сетевой кабель из слота. 
При восстановлении соединения событие Trader.ReConnectionSettings.ConnectionSettings.Restored также не возникает

**Comment by mikasoukhov** [comment]
И не должно. Контролируется соединение только с Квиком. С ним связь не терялась.
