### ISSUE TITLE
DevExpress refs version

### ISSUE THREAD

**Issue by risty** [StockSharp/StockSharp#240]
При запуске приложения с окном, в котором используется PortfolioGrid. Падает с inner exeption
"Could not load file or assembly 'DevExpress.Xpf.Grid.v15.2, Version=15.2.7.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"DevExpress.Xpf.Grid.v15.2, Version=15.2.7.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a"
На сколько я понимаю все ещё продолжает хотеть 15.2.7.0, хотя в текущей версии уже 15.2.10.0

**Comment by stanislav-111** [comment]
Могу добавить, что из за данного бага не запускаются множество примеров. Например при нажатии на кнопку Start в примере SampleHistoryTesting вылетает ошибка что не может найти файл какой то там версии.

**Comment by mikasoukhov** [comment]
https://github.com/StockSharp/StockSharp/commit/09a62c983bd3c72c0f90b3c4fa0477fe4df3b607
