### ISSUE TITLE
Ошибки в Hydra

### ISSUE THREAD

**Issue by stanislav-111** [StockSharp/StockSharp#242]
Очень глючная программа и достаточно сложно по шагам расписать серьезные баги. Но вот несколько на вскидку:

-  После загрузки размер программы в памяти более 850Мб. Я конечно понимаю, что она подгружает более 10К инструментов, по прожорливость превосходит все допустимые пределы.

-  Когда используешь источник Quik, то все бумаги Hydra причисляет к акциям. Хотя если использовать Finam, то она разделяет бумаги на акции , облигации и тд. Поэтому не работает фильтрация бумаг при использовании Quik.

-  Если возникает ошибка загрузки данных с сервера Finame'а программа не пытается повторить загрузку - а в данных в БД наблюдается "дыра". Вот лог:

```
Finam 06.06.2016 17:05:16 +03:00 Info Для SU25080RMFS1@MICEX загружено 22 ExecutionMessage (Tick).
Finam 06.06.2016 17:05:16 +03:00 Info Старт загрузки сделок за 02.03.2015 для SU25080RMFS1@MICEX.
Finam 06.06.2016 17:08:16 +03:00 Error System.InvalidOperationException: Ошибка загрузки сделок за 02.03.2015 для SU25080RMFS1@MICEX. ---> System.Net.WebException: Время ожидания операции истекло
   в System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   в System.Net.WebClient.DownloadString(Uri address)
   в StockSharp.Algo.History.Russian.Finam.FinamHistorySource.#=q2M2dBt1wSIA_5eupwmfmeg==(Uri #=qxmw1YDU9$q8rupcPldYlUg==)
   в StockSharp.Algo.History.BaseDumpableHistorySource.Process(Security security, DateTime from, DateTime to, Type dataType, Object arg, Func`1 download)
   в StockSharp.Algo.History.Russian.Finam.FinamHistorySource.#=qAtzhjVqlv02VpGcCDHwPgA==[T](Security #=qFCM_WgQRj7sdMBXpQ_kVUQ==, DateTime #=q02dwsDIYUCoZ2fvZCqMRZg==, DateTime #=quW5r0BSpUgYZutprpjOwqA==, Type #=qbbF_KVBxfgS8GwFequAjKA==, Object #=qrbLrHQA848jKoegpIRAA2A==, Func`1 #=qDdP0UbwnUqFm64deIyy$jg==, Func`2 #=qPizRsLkFkebjTSfQUITgmw==)
   в StockSharp.Algo.History.Russian.Finam.FinamHistorySource.GetTrades(Security security, DateTime from, DateTime to)
   в StockSharp.Hydra.Finam.FinamTask.OnProcess()
   --- Конец трассировки внутреннего стека исключений ---
Finam 06.06.2016 17:08:16 +03:00 Info Старт загрузки сделок за 03.03.2015 для SU25080RMFS1@MICEX.
Finam 06.06.2016 17:08:17 +03:00 Info Для SU25080RMFS1@MICEX загружено 6 ExecutionMessage (Tick).
Finam 06.06.2016 17:08:17 +03:00 Info Старт загрузки сделок за 04.03.2015 для SU25080RMFS1@MICEX.

```

-  Не реализована многопоточность при скачивании данных. Поэтому загрузка происходит очень долго. Я незнаю, возможно Finam банит за такие дела. Если нет - то реализовать многопоточную загрузку было бы очень неплохо.

-  После окончания загрузки, кнопка "СТОП" не переходит в "СТАРТ". А логи заканчиваются на 

`Finam	06.06.2016 17:09:29 +03:00	Info	Окончание итерации.`

 Нужно начать кнопку "СТОП" в ручную, тогда пишеться в логи:

```
Finam	06.06.2016 17:22:53 +03:00	Info	Перешел в состояние Stopping.
Finam	06.06.2016 17:22:53 +03:00	Info	Перешел в состояние Stopped.
```

Не знаю задумано так или нет. Но выглядит как ошибка - обычно после загрузки приложение должно как то уведомить пользователя что загрузка завершилась.

- После остановки, и при следующем запуске неплохо если бы в окне логов удалялись бы логи от старых объектов. А то не понятно где старый объект, где новый - их имена абсолютно одинаковы. На худой конец дать возможность пользователю очистить окно логов.

- Какая путаница с инструментами от разных источников. Например облигация загруженная с finam имеет класс MICEX, с QUIK'а - TQOB. Причем приложение позволяет добавить в список инструменов Finam'а бумаги квика (хотя их вообще не должно показывать при добавлении). И естественно при попытке запуска загрузки - вылезает ошибка.

- При загрузки тиковых данных с Finam, направление для всех сделок установлено в "Покупка". По мойму Finam не возвращает направление сделки. Ошибка скорей всего связана с тем что для направления сделки используется тип Sides у которого нет неопределенного значения.

**Comment by stanislav-111** [comment]
- При удалении данных по всем инструментам операция происходит катастрофически долго. Такое ощущение что данные по инструментам удаляются в цикле по одному. А ведь базу данных очистить так быстро, или удалить все файлы из директории.

- Я думаю самый распространенный сценарий использования Hydra это создание двух источников: первый реального времени (например Quik), второй по историческим данным (Finam). Так зачем для каждого из таких источников делать свою копию Security, только с разными классами ? Поэтому программа и занимает в памяти почти гигабайт ! Должен быть один экземпляр Security для все возможных источников. 

- Из за проблемы выше возникает следующая проблема: например для Finam'a необходимо ручками ввести шаг цены, шаг объема, и еще какой то шаг. Причем для разных бумаг он может быть реально разный. И если бумаг нужно качать много - то ввод значений может быть напрягом! А новичку вообще не понятно, что от него требуется. Если бы было объединение реал-тайм бумаг с историческими бумагами, то такой проблемы бы вообще не возникло. Все данные по шагам цены, объема и тд брались бы с биржи. И использование программы было бы на порядок понятней и удобней.

**Comment by mikasoukhov** [comment]
Я закрою ишью так как оно частично описывает аналогичный с памятью. Если здесь есть уникальные проблемы - создайте отдельный ишью.

**Comment by stanislav-111** [comment]
Видимо вы прочитали только первый пункт, и сразу посчитали что это "Dublicate". Нужно читать весь пост - там только первый пункт про использование памяти.
