### ISSUE TITLE
StatisticParameterGrid

### ISSUE THREAD

**Issue by risty** [StockSharp/StockSharp#243]
Если добавлять в нее данные так:
`StatisticParameterGrid.Parameters.AddRange(Strategy.StatisticManager.Parameters);`
То значения в таблице, обновляются только при работе с ней(сворачивание /разворачивание вкладок, изменение ширины столбцов)
Если  так:
`StatisticParameterGrid.StatisticManager = _strategy.StatisticManager;`
то падает в `public interface IStatisticParameter : IPersistable`
метод `this.Notify("Value");`
```
 Exception thrown: 'System.InvalidOperationException' in DevExpress.Xpf.Core.v15.2.dll
Additional information: Cross thread operation detected. To suppress this exception, set DevExpress.Xpf.Core.DXGridDataController.DisableThreadingProblemsDetection = true
```
И работает соответственно только только после `DevExpress.Xpf.Core.DXGridDataController.DisableThreadingProblemsDetection = true`

**Comment by lebedevsrg** [comment]
risty, обрати внимание на смысл ошибки "Cross thread operation detected" - у тебя конфликт доступа к этому элементу. Для устранения таких конфликтов объекты необходимо d ajhvs добавлять через GuiAsync. Это относится к любым формам Stocksharp.xaml.

**Comment by mikasoukhov** [comment]
https://github.com/StockSharp/StockSharp/commit/6b332866ba7f595ab18267941fcbfe8977f2c541 проверьте на этом коммите, поменялось ли поведение.

**Comment by risty** [comment]
Проверил на более позднем коммите [f64726a](https://github.com/StockSharp/StockSharp/commit/f64726abd2da615cc169c0c2744cfeeba0337c4d)
Поведение изменилось, но не в лучшую сторону.
Теперь падает и при 
`StatisticParameterGrid.Parameters.AddRange(Strategy.StatisticManager.Parameters);`
и при 
`StatisticParameterGrid.StatisticManager = _strategy.StatisticManager;`
 А добавление `DevExpress.Xpf.Core.DXGridDataController.DisableThreadingProblemsDetection = true;` устраняет проблему с падением в обоих случаях.
Так что надо открывать ишью обратно (

**Comment by mikasoukhov** [comment]
Можно и переоткрывать. Только нужен какой-то код примера. SampleHistTesting работает. Приведите код, проверим его на корректность, и тогда переоткроем.
