### ISSUE TITLE
Оптимизация использования памяти

### ISSUE THREAD

**Issue by stanislav-111** [StockSharp/StockSharp#244]
К сожалению могу константировать, что заниматься разработкой работа с помощью библиотеки StockSharp на компьютере с 4ггб ОЗУ - не возможно :(. Память съедается библиотекой просто в нереальных количествах, компьютер переходит в постоянный своп и все дико тормозит. На форумах куча постов что библиотека "вешает" достаточно мощные компьютеры. Вы теряете большую часть аудитории которая имеет 4ггб ОЗУ и не может комфортно работать с вашей библиотекой.

 Размер минимального робота в ОЗУ - 100Мб! Размер запущенной Hydra - 800Мб!

Могу предложить значительную оптимизацию использования памяти:
- Избавиться от типа decimal. Он занимает 16 байт !!! А членов с такими типом просто нереальное количество по всем классам. Я конечно понимаю что им пользоваться удобно, и он избавляет от проблем с округления дробных чисел. Возможно стоит хранить данные внутри объектов в более компактных типах, а ряду функций оставить возвращение результатов в типе decimal что бы пользователю было удобней.

Как альтернатива decimal, вы могли бы использовать типы int или long (вам видней насколько длинными могут быть цены, объемы и все кто используют у вас decimal). В случае int можно определить еще дополнительный член в структуре типа byte который бы хранил кол. цифр после точки. А в случае long - можно было задать что после точки например всегда 8 цифр, то есть цена равная 1200000000, означала бы 12. Ну или можно было бы взять готовый класс аля decimal из какой нибудь библиотеки, но который занимает меньше чем 16 байт.

**Comment by stanislav-111** [comment]
- Класс Security очень раздутый класс (Ро опциона, Доходность и многое многое другое), хотя его экземппяров может создаваться десятки тысяч (например как в Hydra). Поэтому лучше его объявить как абстрактный (с базовым набором членов которые есть у всех типов бумаг) и от него наследовать Акции, Облигации, Опционы и т.д. А в них уже определить специфические для них члены. Благодаря такому подходу потребление памяти значительно сократится.

**Comment by stanislav-111** [comment]
- Есть ряд членов и свойств, которые уже [depricated] (то есть были актуальны для старых версий, а в новой уже не используются). Эти члена занимают дополнительную память - нужно от них избавиться (удалить из проекта). Один из таких примеров:

`Security.Decimals , которое использует член _decimals `

Я думаю в проекте можно найти еще достаточное число [depricated] членов.

**Comment by stanislav-111** [comment]
- В перечислениях добавить что они являются byte 'ом. В ваших перечислениях меньше 256 значений, а по умолчанию перечисления делаются - int'ом, то есть занимают 4 байта. То есть нужно писать так: 

```
public enum Level1Fields : byte
{
}
```

**Comment by mikasoukhov** [comment]
ОЗУ не существует примерно лет 10, если не больше. То, что показывается в Диспетчере задач - это виртуальная память. Размеру физической она не соответствует.

Мы не ориентируемся на x86

**Comment by stanislav-111** [comment]
Ну зачем придираться к терминам. Вы же тоже пишете не корректно 

> ОЗУ не существует примерно лет 10, если не больше
ОЗУ - это оперативная память. Как это она не существует ? Не ужели в вашем компьютере ее уже нет 10 лет : ) ?

> То, что показывается в Диспетчере задач - это виртуальная память
В диспетчере задач как раз показывается физическая память (графиком). Если у вас Windows 8, то вы можете перейти в диспетчер задач на "Производительность"->"Память" и увидите поле "Выделено" - вот это именно виртуальная память. А на графике и на главном окне диспетчера задач рисуется именно объем занятой оперативной памяти. 

> Мы не ориентируемся на x86
А на что же вы ориентируетесь? На x64 :) ? x86 - это архитектура процессора. Вы будете наверно удивлены но все ваши dll скомпилированы как раз под x86, а не под x64. Если вы хотите скомпилировать ваш проект "не под x86", то вам необходимо в настройках проекта выбрать в VC 2015 -> "Platform Target" - "x64" , вместо "x86".

Кстати вы абсолютно правильно "_ориентируетесь_ на x86" ! Если в настройках проекта выберете x64, то библиотека станет кушать еще больше памяти, ведь в каждом объекте NET есть заголовок. А в нем 3 DWORD. Под x86 - DWORD это 4 байта, а под x64 - это 8 байт. То есть каждый  экземпляр созданный библиотекой станет на 12 байт больше! Для Hydra наверно это будет еще дополнительные пару сотнет мегабайт занимаемой памяти.

Ну а если серьезно, вы зря закрыли данный Issue, это действительно проблема что библиотекой очень не комфортно пользоваться на компьютере с 4Гб памяти, из за нереальной прожорливости. Причем вполне реально уменьшить объем занимаемой памяти в 2-3 раза потратив пару дней.

**Comment by mikasoukhov** [comment]
Смысла в оптимизации нет, так как железо является самым дешевым элементов из всех других костов в алготрейдинге. Если у пользователя нет возможности даже расширить память на компьютере, то заниматься алгоритмической торговлей (покупка сервера, маркет данных, аналитики и документов, спец. логины и т.д.) не имеет никакого смысла.

**Comment by stanislav-111** [comment]
Ну не удивляйтесь тогда постам на форумах следующего содержания:

http://smart-lab.ru/blog/229187.php

> Это станция — полный тормоз. Она просто вешает комп наглухо. Так мой процесор ещё никто не загружал ))). TSLab так систему не грузит. С S# Studio просто невозможно работать она тормозит, просто вешает Винду, забирает все ресурсы компа на себя. Я такого не встречал не в одной проге, кроме кодирования видоса и архивирования. Причем она грузит комп даже в холостом состоянии. Робот не запущен, просто открыта программа и она адцки грузит систему. Проверял на 2х компах, на двух разныйх Виндах 7 и 8 — 32 и 64 битных, результат одни — невозможность работать. Кто не верит, просто запустите прогу и потыркайте кнопки — очень удивитесь )))

 Я думаю у пользователя компьютер перешел в дикий своп памяти, потому что приложение "съело" всю свободную память.

> Смысла в оптимизации нет, так как железо является самым дешевым элементов из всех других костов в алготрейдинге.
С одной стороны вы правы. С другой стороны продвинутые пользователи не будут покупать сервер. А будут его арендовать. Если памяти нужно много - придется покупать более дорогой Instanse, а это ежемесячные увеличенные расходы. И прибыль получаемая от робота соответственно уменьшиться. 

А мой случай такой - у меня MacBook Air с 4ггб памяти. Пока не было задач которые бы требовали больше ресурсов. И я не уверен - буду я покупать новый Mac больше чем за 100К, только для того что бы начать работать с просто неоптимизированной библиотекой....

**Comment by mikasoukhov** [comment]
Я не знаю что было в том случае и гадать на мой взгляд нет смысла. Если у кого-то есть проблема - данный раздел открыт для баг репортов.

**Comment by stanislav-111** [comment]
Ну что сказать: "Хозяин - барин" :).
