### ISSUE TITLE
Plaza CGate. COMMON:INVALID_INTERFACE_VERSION

### ISSUE THREAD

**Issue by risty** [StockSharp/StockSharp#245]
COMMON:INVALID_INTERFACE_VERSION';Application 'ShellFull_0' version mismatch; router version '203'; application version '206'
Роутеры SpectraCGate_x64_v1.3.12.5 и x64_v3.14.1 , подключенный к T-полигону. Ошибка одинаковая.
[client_router.txt](https://github.com/StockSharp/StockSharp/files/304912/client_router.txt)
[StockSharp.Plaza.txt](https://github.com/StockSharp/StockSharp/files/304913/StockSharp.Plaza.txt)

Такая же ошибка в более раннем комите [e203f026fb](https://github.com/StockSharp/StockSharp/tree/e203f026fb94561df2a87fa387ce1ae0d2f5d8d3)

**Comment by risty** [comment]
Это получается есть версия роутера новее чем эта - [SpectraCGate_x64_v3.14.1.exe](http://ftp.moex.com/pub/FORTS/Plaza2/CGate/setup_SpectraCGate_x64_v3.14.1.exe)?
Где её взять?

**Comment by risty** [comment]
В релизе 4.3.14.2 такое ошибки нет, подключается.

**Comment by mikasoukhov** [comment]
Можете посмотреть на последнем релизе? И да, дистрибутив надо последний. 5.1 он вроде сейчас. Но точно не 3.14

**Comment by risty** [comment]
Релиз 4.3.15
роутер SpectraCGate x64_v3.14.1
Ошибка осталась.

**Comment by mikasoukhov** [comment]
См. комментарий выше.
