### ISSUE TITLE
В классе Security нет свойств относящихся к облигациям

### ISSUE THREAD

**Issue by stanislav-111** [StockSharp/StockSharp#246]
Так и не нашел свойств в Security специфичных для облигаций: а именно НКД, размер купон, периодичность выплаты купона и других.

**Comment by mikasoukhov** [comment]
Они не передаются через Security.

**Comment by stanislav-111** [comment]
Если использовать подключение Quik Lua - они вообще не передаются. Для Quik DDE еще возможно их экспортировать через 

Trader.SecuritiesTable.Columns.Add ()
а затем Security.ExtensionInfo ()

а вот для Quik Lua такой возможности нет....
