### ISSUE TITLE
Ошибка при десериализации SettingsStorage 

### ISSUE THREAD

**Issue by Sergey-Dvortsov** [StockSharp/StockSharp#250]
Версия s# 4.3.14.2
Ошибка при десериализации SettingsStorage. Возникает после 0:00 часов. Возможно из-за того, что часы в дате имеют одну цифру...
  
System.InvalidCastException не обработано пользовательским кодом
  HResult=-2147467262
  Message=Cannot convert 22.06.2016 1:07:54 +03:00 to System.DateTimeOffset.
  Source=Ecng.Common
  StackTrace:
       в Ecng.Common.Converter.To(Object value, Type destinationType)
       в Ecng.Serialization.XmlSerializer`1.Deserialize(Stream stream, FieldList fields, SerializationItemCollection source)
       в Ecng.Serialization.XmlSerializer`1.Deserialize(Stream stream, FieldList fields, SerializationItemCollection source)
       в Ecng.Serialization.XmlSerializer`1.Deserialize(Stream stream, FieldList fields, SerializationItemCollection source)
       в Ecng.Serialization.XmlSerializer`1.Deserialize(Stream stream, FieldList fields, SerializationItemCollection source)
       в Ecng.Serialization.Serializer`1.Deserialize(Stream stream, FieldList fields)
       в Ecng.Serialization.XmlSerializer`1.Deserialize(XElement element)
       в Ecng.Serialization.XmlSerializer`1.Ecng.Serialization.IXmlSerializer.Deserialize(XElement element)
       в Ecng.Serialization.XmlSerializer`1.Deserialize(Stream stream, FieldList fields, SerializationItemCollection source)
       в Ecng.Serialization.XmlSerializer`1.Deserialize(Stream stream, FieldList fields, SerializationItemCollection source)
       в Ecng.Serialization.XmlSerializer`1.Deserialize(Stream stream, FieldList fields, SerializationItemCollection source)
       в Ecng.Serialization.XmlSerializer`1.Deserialize(Stream stream, FieldList fields, SerializationItemCollection source)
       в Ecng.Serialization.Serializer`1.Deserialize(Stream stream, FieldList fields)
       в Ecng.Serialization.XmlSerializer`1.Deserialize(XElement element)
       в Ecng.Serialization.XmlSerializer`1.Ecng.Serialization.IXmlSerializer.Deserialize(XElement element)
       в Ecng.Serialization.XmlSerializer`1.Deserialize(Stream stream, FieldList fields, SerializationItemCollection source)
       в Ecng.Serialization.XmlSerializer`1.Deserialize(Stream stream, FieldList fields, SerializationItemCollection source)
       в Ecng.Serialization.XmlSerializer`1.Deserialize(Stream stream, FieldList fields, SerializationItemCollection source)
       в Ecng.Serialization.Serializer`1.Deserialize(Stream stream, FieldList fields)
       в Ecng.Serialization.Serializer`1.Deserialize(String fileName)
       в Synapse.SynapseShell.Root.<OnConnect>b__56_8(IEnumerable`1 securities) в D:\GitRepo\Synapse\SynapseShell\General\Root.cs:строка 371
       в StockSharp.Algo.Connector.ProcessSecurityLookupResultMessage(SecurityLookupResultMessage message)
       в StockSharp.Algo.Connector.OnProcessMessage(Message message)
  InnerException: 
       HResult=-2146233033
       Message=Строка не распознана как действительное значение DateTime.
       Source=mscorlib
       StackTrace:
            в System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles, TimeSpan& offset)
            в System.DateTimeOffset.Parse(String input)
            в Ecng.Common.Converter.To(Object value, Type destinationType)
       InnerException:

**Comment by mikasoukhov** [comment]
Это значит что данные записаны одной культурой, а читаются другой.
