### ISSUE TITLE
QuikTerminal.IsConnected кидает исключение, если терминал закрыт

### ISSUE THREAD

**Issue by OlegFedko** [StockSharp/StockSharp#251]
На мой взгляд IsConnected == false, когда IsLaunched == false.
Ну или как минимум следует задокументировать, что бросается исключение, если терминал закрыт, и что сначала нужно проверять IsLaunched.
При этом существует гонка, что когда я проверяю IsLaunched, он ещё true, а когда проверяю IsConnected, терминал уже закрылся, и я получаю исключение.

**Comment by mikasoukhov** [comment]
Мы не поддерживаем ДДЕ функции коннектора Квик. Переходите на Луа
