### ISSUE TITLE
Ошибка в FractalsPainter и методе draw чарта

### ISSUE THREAD

**Issue by suglosta** [StockSharp/StockSharp#252]
Ошибка не тривиальная, т.к. во-первых находится в закрытом коде, а во-вторых их две.
## Ошибка первая:

FractalsPainter не учитывает параметр Shift при рисовании графика.
### Как воспроизвести:

Чтобы убедиться, что проблема существует нужно запустить без модификаций штатный пример SampleChart и добавить на график индикатор Fractals.
Стрелками я обозначил где на самом деле должны быть точки индикатора
![9ada8c84591e4ee0a2d1801ef83b598e](https://cloud.githubusercontent.com/assets/10158904/16380841/08cb283a-3c82-11e6-920b-22b69635df6d.png)

Проблема в коде FractalsPainter. Вот кусок из рефлектора:

```
        IIndicatorValue indicatorValue2 = dictionary[fractals.Down];
        draw(this.#=qgZK8KV1WYmTlDcO3tc1VFQ==, 0, new double[]
        {
            indicatorValue2.IsEmpty ? double.NaN : indicatorValue2.GetValue<double>()
        });
```

в методе draw, вторым параметром передается 0, а там должен быть сдвиг из ShiftedIndicatorValue, которым на самом деле является indicatorValue2.

Код должен быть примерно такой:

```
        IIndicatorValue downValue = dictionary[(IIndicator)fractals.Down];
        ShiftedIndicatorValue downValueShifted = (ShiftedIndicatorValue)downValue;

        draw(this.downElement, downValueShifted.Shift, new double[1]
        {
            downValue.IsEmpty ? double.NaN : downValue.GetValue<double>()
        });
```
## Ошибка вторая:

Внутри метода draw есть ошибка, неправильно считается сдвиг.
Эта ошибка накапливается в процессе отрисовки точек индикатора при использовании сдвига и не проявляется, если рисовать без сдвига.
### Как проверить:

Решить проблему с FractalPainter и повторить тест на штатном примере.
Альтернативные вариант - написать простой пэинтер, который будет делать фиксированный сдвиг на 1 или любое другое число свечей и использовать его для отрисовки простого индикатора хаев свечек.
На графике будет наблюдаться накапливаемое отставание точек от графика.

**Comment by suglosta** [comment]
Решил добавить пример фракталов здорового человека :)
![image](https://cloud.githubusercontent.com/assets/10158904/17087207/6ae34c46-520d-11e6-87d0-84220c6f74a5.png)

**Comment by mikasoukhov** [comment]
Пока не совсем понятно, что именно не так работает

**Comment by suglosta** [comment]
На первом графике видно, что точки нарисованы на тех свечах где фрактал считался, а должны были там, где стрелки указывают.
Пример правильной отрисовки я вчера приложил - точки на своих хвостах, а не сдвинуты вправо.

**Comment by mikasoukhov** [comment]
А что используется в качестве эталона?

**Comment by mikasoukhov** [comment]
https://github.com/StockSharp/StockSharp/commit/66bebdcd5c5130385240ebabeed43cf134b6c935
