### ISSUE TITLE
Неожиданный приход старых свечей из candleManager или HistoryEmulationConnector

### ISSUE THREAD

**Issue by suglosta** [StockSharp/StockSharp#253]
### Проблема:

При срабатывании дочерних защитных стратегий, из candleManager начинают снова сыпаться свечи с начала эмуляции, при этом у HistoryEmulationConnector CurrentTime не сбрасывается.
### Как воспроизвести:

В стандартном примере SampleHistoryTesting меняем в коде основной стратегии код создания ордеров так, чтобы он добавлял для сделок защитную стратегию.
В ProcessCandle вместо:

```
            if (!SafeGetConnector().RegisteredMarketDepths.Contains(Security))
            {
                var price = Security.GetMarketPrice(Connector, direction);

                // register "market" order (limit order with guaranteed execution price)
                if (price != null)
                    RegisterOrder(this.CreateOrder(direction, price.Value, volume));
            }
```

пишем:

```
            if (!SafeGetConnector().RegisteredMarketDepths.Contains(Security))
            {
                var price = Security.GetMarketPrice(Connector, direction);

                // register "market" order (limit order with guaranteed execution price)
                if (price != null)
                {
                    var order = this.CreateOrder(direction, price.Value, volume);
                    order
                        .WhenNewTrades(this.SafeGetConnector())
                        .Do(trades => {
                            // для каждой сделки добавляем защитную пару стратегии
                            foreach (var t in trades)
                            {
                                // выставляет тейк-профит
                                var takeProfit = new TakeProfitStrategy(t, 1);
                                ChildStrategies.Add(takeProfit);
                            }
                        })
                        .Apply(this);
                    RegisterOrder(order);
                }
            }
```

Запускаем тестирование на свечах и получаем:

> An exception of type 'System.InvalidOperationException' occurred in StockSharp.Xaml.Charting.dll >but was not handled in user code
> Additional information: Невозможно изменить значение для свечи для даты 10/01/2012 10:00:00 >+03:00 последнее добавленное значение для даты 10/01/2012 23:50:00.

на строке:
`_chart.Draw(data);`

Если закоментировать эту строку, то в логе найдется косяк:

2012/10/01 22:20:00.000|       |SS_RIZ2@FORTS_test account|Новая свеча 10/01/2012 22:20:00 +03:00: RIZ2@FORTS 149800;149940;149700;149850; объем 4147
2012/10/01 22:25:00.000|       |SS_RIZ2@FORTS_test account|Новая свеча 10/01/2012 22:25:00 +03:00: RIZ2@FORTS 149870;149920;149710;149850; объем 3520
2012/10/01 22:30:00.000|       |SS_RIZ2@FORTS_test account|Новая свеча 10/01/2012 22:30:00 +03:00: RIZ2@FORTS 149870;149940;149670;149780; объем 4916
2012/10/01 22:35:00.000|       |SS_RIZ2@FORTS_test account|Новая свеча 10/01/2012 22:35:00 +03:00: RIZ2@FORTS 149780;150190;149780;150080; объем 5628
2012/10/01 22:40:00.000|       |SS_RIZ2@FORTS_test account|Новая свеча 10/01/2012 22:40:00 +03:00: RIZ2@FORTS 150070;150230;150010;150160; объем 2942
2012/10/01 22:45:00.000|       |SS_RIZ2@FORTS_test account|Новая свеча 10/01/2012 22:45:00 +03:00: RIZ2@FORTS 150170;150250;150020;150160; объем 3825
2012/10/01 22:50:00.000|       |SS_RIZ2@FORTS_test account|Новая свеча 10/01/2012 22:50:00 +03:00: RIZ2@FORTS 150170;150200;150040;150070; объем 1991
2012/10/01 22:50:00.000|       |SS_RIZ2@FORTS_test account|Регистрация новой  (0x113BD24) заявки на Sell с ценой 88330 и объемом 1. 
2012/10/01 22:50:00.000|       |HistoryEmulationConnector|RegisterOrder: 0/ Продажа Цена=88330 Объем=1 Сост=None Бал=0 
2012/10/01 22:50:00.000|       |HistoryEmulationConnector|New order: 4/ Продажа Цена=88330 Объем=1 Сост=Pending Бал=1 
2016/06/27 10:32:53.670|       |SecurityMarketEmulator|Заявка 4 зарегистрирована.
2016/06/27 10:32:53.686|       |SecurityMarketEmulator|Заявка 4. Исполнение объема 1 по цене 150068.
2016/06/27 10:32:53.688|       |SecurityMarketEmulator|Заявка 4 полностью исполнена.
2016/06/27 10:32:53.691|       |SecurityMarketEmulator|Сделка 1 заявки 4 P=150068 V=1.
2012/10/01 19:50:01.000|       |HistoryEmulationConnector|Order changed: 4/1 Продажа Цена=88330 Объем=1 Сост=Done Бал=0 
2012/10/01 19:50:01.000|       |SS_RIZ2@FORTS_test account|Заявка 4 (0x113BD24) больше не активна.
2012/10/01 19:50:01.000|       |SS_RIZ2@FORTS_test account|Новая позиция: (S#:RIZ2@FORTS, Native:,Type:, test account)=-1.
2012/10/01 19:50:01.000|       |TPS_RIZ2@FORTS_test account|Стратегия Запущена. [0,1]. Позиция 0.
2012/10/01 19:50:01.000|       |TPS_RIZ2@FORTS_test account|Защита позиции Sell/150068 с объемом 1. Уровень=1, Скользящий=False, Маркет-заявки=False, Котирование=False, Проскальзывание=0
2012/10/01 19:50:01.000|       |TPS_RIZ2@FORTS_test account|Котирование на Buy объема 1.
2012/10/01 19:50:01.000|       |SS_RIZ2@FORTS_test account|Новая Sell сделка 1 по цене 150068 на 1 заявки 4.
2012/10/01 19:50:03.000|       |TPS_RIZ2@FORTS_test account|Защита активирована. Закрытие позиции по 206090.
2012/10/01 19:50:03.000|       |TPS_RIZ2@FORTS_test account|Цена текущей NULL и лучшей 206090.
2012/10/01 19:50:03.000|       |TPS_RIZ2@FORTS_test account|Лучший бид 147210 и лучший аск 147260.
2012/10/01 19:50:03.000|       |TPS_RIZ2@FORTS_test account|Регистрация новой  (0x6C47BE) заявки на Buy с ценой 206090 и объемом 1. 
2012/10/01 19:50:03.000|       |HistoryEmulationConnector|RegisterOrder: 0/ Покупка Цена=206090 Объем=1 Сост=None Бал=0 
2012/10/01 19:50:03.000|       |HistoryEmulationConnector|New order: 9/ Покупка Цена=206090 Объем=1 Сост=Pending Бал=1 
2012/10/01 19:50:03.000|       |SS_RIZ2@FORTS_test account|Новая свеча 10/01/2012 10:00:00 +03:00: RIZ2@FORTS 147210;147210;145920;146240; объем 20336

Это происходит потому, что в стратегию вновь приходит самая первая свеча^^^^^^^^^^
Пробовал пускать стратегию дальше, там дальше - день сурка.
Каждый раз когда срабатывает защитная стратегия, свечи начинают идти сначала.
Проверялось и на **TakeProfitStrategy** и на **StopLossStrategy**
Лог:
https://dl.dropboxusercontent.com/u/13095001/sample.log

Линк на модифицированую версию стратегии:
https://dl.dropboxusercontent.com/u/13095001/SmaStrategy.cs

**Comment by suglosta** [comment]
Решил копнуть рефлектором код защитных стратегий.
Внутри `ProtectiveStrategy` нашел строку после которой все ломается:
`this.Connector.RegisterTrades(this.Security);`
Проблема, похоже, не в стратегиях а где-то в эмуляторе.

Как воспроизвести на примере SampleHistoryTesting.
Коментируем строку:
`_chart.Draw(data);`
и после нее добавляем:
```
if (candle.OpenTime.LocalDateTime == new System.DateTime(2012, 10, 1, 15, 0, 0))
{
            Connector.RegisterTrades(Security);
}
```
Запускаем приложение, включаем debug log, ставим галку на свечи и запускаем.
В логе видем цирк с конями:
![image](https://cloud.githubusercontent.com/assets/10158904/16652369/e3b39f9a-4452-11e6-9be7-e722cbb25b36.png)

Отчетливо видно, что после `SecurityLookupResult` за 2012.10.01 14:00:00
прилетает `MarketData` за 2012.10.01 11:03:00 
а потом вообще начинают идти свечи начиная с 2012.10.01 10:00:00

**Comment by mikasoukhov** [comment]
А зачем комменттировать отрисовку на график?

**Comment by suglosta** [comment]
Если отрисовку не комментировать, то на ней вываливается ошибка
An exception of type 'System.InvalidOperationException' occurred in StockSharp.Xaml.Charting.dll >but was not handled in user code
Additional information: Невозможно изменить значение для свечи для даты X последнее добавленное значение для даты Y.

А комментирование позволяет получить в лог всю картину сбоя времени

**Comment by lebedevsrg** [comment]
Старые свечи могут приходить и с начала старта некоторых коннекторов, н-р у Transaq-коннектора. 
Соответственно приведенную выше проблему можно решить тем, что метод ProcessCandle   всегда начинать следующим образом:   
  private void ProcessCandle(Candle candle)
        {
            var timeFrame = (TimeSpan)candle.Arg;
            var time = Connector.CurrentTime - timeFrame;
            var timediff = time - candle.OpenTime;

            if (candle.OpenTime < time)
            {   return;
            }
....... <тут реальный код обработки свечи> ........
}
