### ISSUE TITLE
Добавить в OrderGrid доп. столбецы из объекта Order

### ISSUE THREAD

**Issue by lebedevsrg** [StockSharp/StockSharp#257]
Прошу добавить в OrderGrid столбцы "Код брокера" (BrokerCode), "Код клиента"(ClientCode) и в самый конец "Комментарий" (Comment) из объекта Order.
Необходимо для универсализации использования существующего OrderGrid.

**Comment by mikasoukhov** [comment]
Комментарий уже есть.
