### ISSUE TITLE
Missing projects from solution

### ISSUE THREAD

**Issue by sun2rise** [StockSharp/StockSharp#258]
Hi,
I am trying to use Samples/Testing/SampleHistoryTestingsample from 4.3.14.1 but the stocksharp project is not complete: for example projects like Algo.HistoryPublic or Xaml or Xaml.ChartingPublic are missing.
I noticed that all the missing projects are present in the 'Terminal' branch of stocksharp.
Which is the correct way to go?
Use Terrminal branch as starting point and update the files with the ones from the latest projects?

Thanks

**Comment by mikasoukhov** [comment]
We support only the master branch. Some of sources distributed only by special license http://stocksharp.com/products/pricing/
