### ISSUE TITLE
Could not load file or assembly 'DevExpress.Xpf.Core

### ISSUE THREAD

**Issue by sun2rise** [StockSharp/StockSharp#259]
While I was running my app based on stocksharp 4.3.14.1 referenced from NuGet, I got the following error:

```
Exception thrown: 'System.Windows.Markup.XamlParseException' in PresentationFramework.dll

Additional information: Could not load file or assembly 'DevExpress.Xpf.Core.v15.2, PublicKeyToken=b88d1754d700e49a' or one of its dependencies. The system cannot find the file specified.
```

What is the problem with DevExpress? And why has it never happened with previous versions?
Thanks

**Comment by mikasoukhov** [comment]
You need to make an refs to DevExp libs in cased on Xaml editor support.
