### ISSUE TITLE
Lua - не приходят события OrderChanged, NewMyTrades для акций 

### ISSUE THREAD

**Issue by Sergey-Dvortsov** [stocksharp/stocksharp#26]
Lua. Не при приходят события OrderChanged, NewMyTrades для акций - площадка TQBR для игровых серверов Церих, для  Квик Джуниор - акции, площадка QJSIM все работает нормально...

**Comment by mikasoukhov** [comment]
https://github.com/stocksharp/stocksharp/commit/625c9433c8982a58410bfe2f1b5e80e2c889740a
