### ISSUE TITLE
Transaq - Ошибка получения  рыночных данных по новой бумаге через GetLevel1Fields

### ISSUE THREAD

**Issue by lebedevsrg** [StockSharp/StockSharp#264]
**Описание ошибки**
Ошибка диагностирована при подключении через  TransaqConnector.
Если в стратегии появляется необходимость использовать новый инструмент (security),  и он до этого не регистрировался (соответственно поля BestBid, BestAsk пустые ) , после регистрации при запросе   рыночных данных через функцию GetLevel1Fields.

**Код вызывающий ошибку**
Код является частью стратегии которая ловит заявки, выполненные в ручном режиме в терминале и занимается их обработкой. Поэтому в общем случае newSecurity – новая бумага, которая получена от TransaqConnector через объект Order.Security и которая не была ранее зарегистрирована в коннекторе через RegisterSecurity.
var res = Connector.RegisteredSecurities.FirstOrDefault(src => src.Id == newSecurity.Id);
if (res == null) Connector.RegisterSecurity(newSecurity);
qtPrice = (decimal)Connector.GetSecurityValue(newSecurity, Level1Fields.BestAskPrice);

**Stack Trace**
TransaqTrader	29.08.2016 21:53:05 +03:00	Error	System.InvalidOperationException: Сообщение 'Execution,T(L)=2016/08/29 21:53:05.449,T(S)=2016/08/29 21:53:11.288,(Transaction),Sec=S#:@, Native:19291,Type:,Ord=22636835618/0/154191,Fail=,Price=1.1465,OrdVol=1,TrVol=,Bal=0,TId=,Pf=76182d0,TPrice=,UId=,State=Done' привело к ошибке обработки. ---> System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в Shell.Strategies.CmnStrategy.FollowSignal(Order order) в D:\SH\ShellAdvanced\ShellAE\Strategies\CmnStrategy.cs:строка 517
   в Shell.Strategies.CmnStrategy.OnNewOrders(IEnumerable`1 NewOrders) в D:\SH\ShellAdvanced\ShellAE\Strategies\CmnStrategy.cs:строка 403
   в System.Action`1.Invoke(T obj)
   в StockSharp.Algo.Connector.RaiseNewOrder(Order order) в D:\SH\StockSharp-4.3.14.2-sc\StockSharp-4.3.14.2\Algo\Connector_Raise.cs:строка 310
   в StockSharp.Algo.Connector.ProcessOrderMessage(Order o, Security security, ExecutionMessage message, Int64 transactionId) в D:\SH\StockSharp-4.3.14.2-sc\StockSharp-4.3.14.2\Algo\Connector_ProcessMessage.cs:строка 1523
   в StockSharp.Algo.Connector.ProcessTransactionMessage(Order order, Security security, ExecutionMessage message, Int64 transactionId) в D:\SH\StockSharp-4.3.14.2-sc\StockSharp-4.3.14.2\Algo\Connector_ProcessMessage.cs:строка 1642
   в StockSharp.Algo.Connector.<>c__DisplayClass76_0.<ProcessExecutionMessage>b__1(Security s, ExecutionMessage m) в D:\SH\StockSharp-4.3.14.2-sc\StockSharp-4.3.14.2\Algo\Connector_ProcessMessage.cs:строка 1670
   в StockSharp.Algo.Connector.ProcessSecurityAction[TMessage](TMessage message, Func`2 getId, Action`2 action, Boolean ignoreIfNotExist) в D:\SH\StockSharp-4.3.14.2-sc\StockSharp-4.3.14.2\Algo\Connector_ProcessMessage.cs:строка 753
   в StockSharp.Algo.Connector.ProcessExecutionMessage(ExecutionMessage message) в D:\SH\StockSharp-4.3.14.2-sc\StockSharp-4.3.14.2\Algo\Connector_ProcessMessage.cs:строка 1669
   в StockSharp.Algo.Connector.OnProcessMessage(Message message) в D:\SH\StockSharp-4.3.14.2-sc\StockSharpStockSharp.Algo.Connector.OnProcessMessage-4.3.14.2\Algo\Connector_ProcessMessage.cs:строка 570
   --- Конец трассировки внутреннего стека исключений ---

**Вывод**
Судя по анализу ошибок в открытых кодах функции StockSharp.Algo.Connector.OnProcessMessage выводится значение Message, которое вызывает ошибку : это Message типа Execution, в котором поле Sec заполнено неверными данными. Так как коды библиотеки Stocksharp.Transaq в открытом доступе отсутствуют, то восстановить всю цепочку  и разобраться где же создается неполноценный объект  Message не представляется возможным.

**Comment by mikasoukhov** [comment]
По стрек-трейсу видно, что ошибка в пользовательском коде
Shell.Strategies.CmnStrategy.FollowSignal(Order order) в D:\SH\ShellAdvanced\ShellAE\Strategies\CmnStrategy.cs:строка 517

**Comment by lebedevsrg** [comment]
??? Указанное место в пользовательскои кода - это как раз вызов qtPrice = (decimal)Connector.GetSecurityValue(newSecurity, Level1Fields.BestAskPrice);
А дальше управление передается в функцию GetLevel1Fields. библиотеки Stocksharp.Transaq

**Comment by mikasoukhov** [comment]
Если бы дальше передавалось, то стэк трейс был бы другой.
