### ISSUE TITLE
Массовые ошибки в Ecng.ComponentModel (API 4.3.16.1)

### ISSUE THREAD

**Issue by lebedevsrg** [StockSharp/StockSharp#267]
Сегодня при обновлении с версии API 4.3.14.2 на API 4.3.16.1 получил громадное количество ошибок типа: "Метод не найден: "System.String Ecng.ComponentModel.Extensions.GetDisplayName(System.Reflection.ICustomAttributeProvider, System.String)".

Ругается буквально на все. Ниже два примера.

Кейс 1: "Инициализатор типа \"StockSharp.Logging.LogManager\" выдал исключение."
Стек-трейс:    в StockSharp.Logging.BaseLogSource..ctor()
   в StockSharp.Logging.BaseLogReceiver..ctor() в D:\SH\StockSharp-4.3.16.1_sc\StockSharp-4.3.16.1\Logging\ILogReceiver.cs:строка 38
   в StockSharp.Logging.LogManager.ApplicationReceiver..ctor() в D:\SH\StockSharp-4.3.16.1_sc\StockSharp-4.3.16.1\Logging\LogManager.cs:строка 47
   в StockSharp.Logging.LogManager.DisposeLogMessage..ctor() в D:\SH\StockSharp-4.3.16.1_sc\StockSharp-4.3.16.1\Logging\LogManager.cs:строка 92
   в StockSharp.Logging.LogManager..cctor() в D:\SH\StockSharp-4.3.16.1_sc\StockSharp-4.3.16.1\Logging\LogManager.cs:строка 108

В конечном счет нашел что ошибка порождается в BaseLogSource в вызовом GetType().GetDisplayName();

Кейс2: "Инициализатор типа \"StockSharp.Algo.Statistics.BaseStatisticParameter\" выдал исключение."
   в StockSharp.Algo.Statistics.BaseStatisticParameter`1..ctor()
   в StockSharp.Algo.Statistics.MaxProfitParameter..ctor()
   в StockSharp.Algo.Statistics.StatisticManager..ctor()
   в StockSharp.Algo.Strategies.Strategy..ctor()
   в Shell.BaseStrategy..ctor() в D:\SH\ShellAdvanced\ShellAE\Strategies\Base\BaseStrategy.cs:строка 218
   в Shell.BaseShellStrategy..ctor() в D:\SH\ShellAdvanced\ShellAE\Strategies\Base\BaseShellStrategy.cs:строка 471
   в Shell.TLSStrategy..ctor() в D:\SH\ShellAdvanced\ShellAE\Strategies\TLSStrategy.cs:строка 274
   в Shell.MainWindow.AddTLSStrategy(TLSStrProp properties) в D:\SH\ShellAdvanced\ShellAE\Xaml\MainWindow.xaml.cs:строка 1679
   в Shell.MainWindow.InitializeConfiguration() в D:\SH\ShellAdvanced\ShellAE\Xaml\MainWindow.xaml.cs:строка 547
   в Shell.MainWindow..ctor() в D:\SH\ShellAdvanced\ShellAE\Xaml\MainWindow.xaml.cs:строка 217

Проблема также порождена вызовом GetType().GetDisplayName();

**Comment by mikasoukhov** [comment]
Что-то не так распаковали, где-то старые файлы.
