### ISSUE TITLE
Lua - не транслируется направление сделки для фьючерсов 

### ISSUE THREAD

**Issue by Sergey-Dvortsov** [stocksharp/stocksharp#27]
Lua. На реальном сервере брокер "Открытие" не транслируется направление сделки для фьючерсов (=null) , при использовании DDE - все нормально..

**Comment by mikasoukhov** [comment]
Какая версия?

**Comment by Sergey-Dvortsov** [comment]
4.2.43

**Comment by mikasoukhov** [comment]
Скорее всего старая версия.
