### ISSUE TITLE
Отложенное вычисление StatisticParameter

### ISSUE THREAD

**Issue by mustaev-ruslan** [StockSharp/StockSharp#276]
Статистические параметры предназначенные для отображения в StrategiesStatisticsPanel рассчитаны на постоянный пересчет в ходе выполнения стратегии, но если этого не требуется, а вычисления ресурсоемкие, необходимо выполнить расчет только после остановки стратегии.
В связи с этим предлагаю внести следующие изменения:
1) Метод Update() для StrategiesStatisticsPanel. Причина: если вычислить значение какого-то параметра после выполнения стратегий, то в таблице параметр не обновляется.
2)DisplayName в IStatisticParameter сделать не статическим. Причина: если пользователь параметра зачем-то вводит в свой код два параметра одного класса, то их нужно как-то различить в таблице, а этого никак не сделать. Например такое может понадобиться при отложенном вычислении параметра, создается интерфейс
```
ILateCalcStatisticParameter : IStatisticParameter 
{
public Value{get;set;} 
}
```
Чтобы в коде использовать 
`strategy.WhenStopped().Do(()=> MyParameter.Value = VeryHardCalc())`

**Comment by mikasoukhov** [comment]
Данные раздел предназначен для обозначения каких-то проблем. Если у вас пожелания-предложения, то лучше используйте форум. Или сразу пул реквест.

Данный ишью я закрываю.
