### ISSUE TITLE
отсутствует ссылка на DevExpress.Xpf.LayoutControl.v15.2 в некоторых Samples

### ISSUE THREAD

**Issue by risty** [StockSharp/StockSharp#278]
Например в SamplePlaza и SampleQuik падают во время выполнения с ошибкой
` Could not load file or assembly 'DevExpress.Xpf.LayoutControl.v15.2, PublicKeyToken=b88d1754d700e49a' or one of its dependencies. Не удается найти указанный файл.`

**Comment by alexandr-golubev** [comment]
Добавь reference DevExpress.Data

**Comment by risty** [comment]
Пасиб, я более чем в курсе как это поправить ;)
