### ISSUE TITLE
SecurityPicker filter

### ISSUE THREAD

**Issue by risty** [StockSharp/StockSharp#281]
Крайний релиз 4.3.19.5.
Любой пример с SecurityPicker. Пусть SampleQuik.
Если начать забивать ID инструмента в строку поиска в тот момент,
когда в SecurityPicker ещё грузятся инструменты получаем эксепшн. 
![sec_pic_exc](https://cloud.githubusercontent.com/assets/16439647/21073190/770b5cfe-bee9-11e6-814f-45dff396ccf6.jpg)

**Comment by mikasoukhov** [comment]
https://github.com/StockSharp/StockSharp/commit/3d0aa75ea9a6d2cddd2d342995e3b6a2fe2551aa
