### ISSUE TITLE
Приход сделок в RealTimeEmulationTrader на Квике

### ISSUE THREAD

**Issue by risty** [StockSharp/StockSharp#282]
Суть проблемы, что после регистрации изменений по инструменту и регистрации сделок по нему приходит случайное количество непонятных(неопознанных) сделок, затем через случайное время приходят или не приходят сделки из терминала.
Выглядит так:
![trade](https://cloud.githubusercontent.com/assets/16439647/21102231/57cd3e2e-c08e-11e6-91bb-ca57445571bb.jpg)

Подробности:
Квик 7.5.0.72
Релиз 4.3.19.5
Берем пример SampleQuik и меняем коннектор на 
```
var quikMd = new LuaFixMarketDataMessageAdapter(new MillisecondIncrementalIdGenerator())
	{
		Address = Address.Text.To<EndPoint>(),
		Login = Login.Text,
		Password = Password.Password.To<SecureString>(),
		RequestAllSecurities = AllSecurities.IsChecked == true
	};

Trader = new RealTimeEmulationTrader<IMessageAdapter>(quikMd);
```
Собираем. Запускаем. Подключаемся. Открываем окно с инструментами, ждем когда они подгрузятся. Выбираем инструмент. Нажимаем кнопку "Level1" тем самым вызывая методы
```
trader.RegisterSecurity(security);
trader.RegisterTrades(security);
```
для выбранного инструмента.
Открываем окно с тиками и видим некие сделки. см. скриншот выше и этот
![tr2](https://cloud.githubusercontent.com/assets/16439647/21102082/8976583a-c08d-11e6-8683-239cbf4cd049.jpg)
Далее после случайного количества времени из терминала начинают поступать уже сделки, которые видны в нем в таблице всех сделок. А могут и вообще не поступить.
Если все же сделки из терминала приходят, после прихода основной массы( когда время последней сделки в терминале сравнялось с временем в таблицах с тиками) загрузка всех ядер процессора все равно остается близкой к 100% и утекает память. Если оставить на длительное время, то outOfMemory эксепшн. 

В релизе 4.3.18 все было нормально. Сделки поступали из коннектора сразу же после регистрации инструмента и сделок и в нормальном порядке. На поздних релизах сломалось.

**Comment by mikasoukhov** [comment]
https://github.com/StockSharp/StockSharp/commit/d03522fc33f9d5c0f4387e86d77206bf82098aac
