### ISSUE TITLE
Рассинхрон свечей, коннектора, стакана и сделок в HistoryEmulationConnector

### ISSUE THREAD

**Issue by suglosta** [StockSharp/StockSharp#283]
### Проблему можно описать по-разному, в зависимости от того, что для вас первично:
- фальстарт события закрытия свечи
или
- несоответствие времени коннектора, параметров стакана (свечи на основе которой генерится) и цены/времени исполнения сделки.

### Проблематика:
После прихода новой закрытой свечи ордера исполняются в диапазоне цен и времени закрытой свечи.
Это категорически не корректное поведение.

### Как воспроизвести:
Запустить стандартный пример SampleHistoryTesting и прогнать на свечах.
После этого открываем лог и видим:
![image](https://cloud.githubusercontent.com/assets/10158904/21370982/c07c7d1c-c71f-11e6-8b02-b20f2ea21e81.png)

### Что не так:
Приходит новая свеча: "Новая свеча 10/01/2012 22:50:00 +04:00" - это время открытия свечи, т.е. закрылась она в 22:55
При этом время коннектора - 22:50:01 (без учета зоны - 18:50:01)
Время исполнения заявки и цена исполнения берется из этой закрытой свечки.
В реальности это невозможно и такой подход нарушает логику работы эмулятора.

Судя по количеству завязанных друг на друга объектов и событий, скорее всего проще присылать событие закрытия свечи позже, чем переписывать все остальное.

**Comment by mikasoukhov** [comment]
Заявки исполняются не по свече, а по стакану. Заявка исполнилась потому, что была соответствующая ситуация в стакане. При чем тут свечи - не понятно.

Пока закрываю ишью. Если что-то будет новое - переоткрою.

Рекомендую посмотреть на поток сообщения непосредственно от эмулятора. Там процедурный однопоточный подход, поэтому не должно быть сложностей в анализе.

**Comment by suglosta** [comment]
Заявка исполняется по стакану, но стакан в эмуляторе формируется на основе параметров свечи.
При текущей реализации берутся параметры уже закрытой свечи.
Кроме того, время в коннекторе в этот момент находится в диапазоне закрытой свечи.
Вот причем тут свечи.
