### ISSUE TITLE
Корректировка времени торговых сессий

### ISSUE THREAD

**Issue by gem81** [StockSharp/StockSharp#284]
Небольшая корректировка в FORTS
-----------------------------------------------
			Forts = new ExchangeBoard
			{
				Code = "FORTS",
				WorkingTime = new WorkingTime
				{
					Periods = new List<WorkingTimePeriod>
					{
						new WorkingTimePeriod
						{
							Till = DateTime.MaxValue,
							Times = new List<Range<TimeSpan>>
							{
								new Range<TimeSpan>("10:00:00".To<TimeSpan>(), "14:00:00".To<TimeSpan>()),
								new Range<TimeSpan>("14:03:00".To<TimeSpan>(), "18:45:00".To<TimeSpan>()),
								new Range<TimeSpan>("19:00:00".To<TimeSpan>(), "23:50:00".To<TimeSpan>())
							},
						}
					},
					SpecialWorkingDays = new List<DateTime>(russianSpecialWorkingDays),
					SpecialHolidays = new List<DateTime>(russianSpecialHolidays),
				},
				ExpiryTime = new TimeSpan(18, 45, 00),
				//IsSupportAtomicReRegister = true,
				Exchange = Exchange.Moex,
				TimeZone = moscowTime,
			};
Перерыв с 14:00 до 14:05
----------------------------------------------
-----------------------------------------------
			MicexCets = new ExchangeBoard
			{
				Code = "CETS",
				WorkingTime = micexWorkingTime.Clone(),
				//IsSupportMarketOrders = true,
				//IsSupportAtomicReRegister = true,
				Exchange = Exchange.Moex,
				TimeZone = moscowTime,
			};
необходимо внести новый тип для CETS cetsWorkingTime
new Range<TimeSpan>("10:00:00".To<TimeSpan>(), "23:50:00".To<TimeSpan>())
---------------------------------------

**Comment by mikasoukhov** [comment]
Для таких вещей используются пул реквесты.
