### ISSUE TITLE
Transaq: Ошибка при обработке сделок по отложенной заявке

### ISSUE THREAD

**Issue by lebedevsrg** [StockSharp/StockSharp#288]
Стал применять в торговле отложенные лимитные заявки, размещенные  на сервере Transaq. 
При исполнении заквки Transaq-коннектор (S.API  4.3.19.5 ) выдает следующее (реальный сегодняшний пример):

1) вначале 9 подряд одинаковых информационных сообщений :
My trade delayed: Execution,T(L)=2017.02.06 13:19:42.977,T(S)=2017.02.06 13:19:47.777,(Transaction),Sec=S#:MXH7@FORTS, Native:,Type:Future,Ord=24864069975/0/0,Fail=,Price=0,OrdVol=,TrVol=2,Bal=,TId=1704589429,Pf=7640xkl,TPrice=223000,UId=,State=

2) затем нормальное подтверждение что заяка выполнилась и балас равен 0,

3) затем выдает ошибку:
SettingsEngine	06.02.2017 14:01:58	Error	"System.InvalidOperationException: Операция является недопустимой из-за текущего состояния объекта.
   в StockSharp.Algo.SecurityNativeIdMessageAdapter.ProcessMessage[TMessage](SecurityId securityId, TMessage message, Func`3 processSuspend)
   в StockSharp.Algo.SecurityNativeIdMessageAdapter.OnInnerAdapterNewOutMessage(Message message)
   в StockSharp.Messages.MessageAdapter.SendOutMessage(Message message)
   в StockSharp.Transaq.TransaqMessageAdapter.#=qIGHW9wX6Y5PWajfHNSzbr9zUrt3gCKo_vU9Tn4xF2x8=(#=q0Q_mZVILWjwwtafw6GuPNWXTtejkU$eyDddjCCVRCVppp5uugXGFMhnY41yN3gRPDJNpCigXIqGJwVYf_PY_Og== #=qBAxfBdCGCrVYc9WtJ0MhXw==)
   в StockSharp.Transaq.TransaqMessageAdapter.#=q9HSB_mZ0G6CWQORL2D9GCceWFH7cF7RQSh8YwcPc72M=.#=qRbAU2YIl4tz8m2Bc$Iom1ZcyNuL1wR4inkVsTK5M5HE=(#=qaZXq7iLLjPRITtNkTcAyC37un0CUf7PHuMamIMDE_mBU$2pVOdHdw8UTj4cHQsd0 #=qBAxfBdCGCrVYc9WtJ0MhXw==)
   в StockSharp.Transaq.TransaqMessageAdapter.#=qk7lV4uyzM42zj3eHDIWs9w==(String #=q2uPggOt7PwJIeVTgh94$WA==)"

Ошибка не критическая, после ошибки работа коннектора продолжается в нормальном режиме. Однако в целях поддержания платформы в рабочем состоянии прошу вас ее исправить.

**Comment by mikasoukhov** [comment]
Необходим код формирования отложенных заявок.

**Comment by lebedevsrg** [comment]
Ошибка проявляется как при срабатывании лимитных ордеров, созданных программно, так и при срабатывании ордеров, установленных в FinamTrade в ручном режиме. Так что от кода не зависит.

**Comment by mikasoukhov** [comment]
Создание заявки через пример не приводит к ошибке. Попробуйте через пример. Возможно, у вас есть какая-то специфика, которую вы не указали.

**Comment by mikasoukhov** [comment]
Ишью закрываем?

**Comment by lebedevsrg** [comment]
Как выяснилось была специфика, но не в моем коде, а в том что я перевел средства с обычного счета на счет единой денежной позиции (ЕДП) и стал работать на нем. С этого понедельника вернулся на обычный счет срочного рынка и на нем такх ошибок нет! Видимо это API Транзак-коннектора неверно обрабатывет события по счетам ЕДП, т.е. Финам еще не доработал его для работы с такими счетами.
Полагаю что ишью можно закрыть.

**Comment by mikasoukhov** [comment]
Буквально вчера чуть поковырялись, и нашли причину. Поэтому будет фикс.
