### ISSUE TITLE
RealTimeEmulationTrader не открывается позиция

### ISSUE THREAD

**Issue by Prival1** [StockSharp/StockSharp#291]
Программу показывающие это прилагаю. Возможно я что то просто не так делаю, но на форуме написали что это возможно баг http://stocksharp.ru/forum/8078/realtimeemulationtrader-/#m39265

После нажатия кнопки Buy в окне вывода следующие сообщения.
---Start---RealTimeEmulationTrader`1---RIH7@FORTS---test---1000000---1000000---0
Событие регистрации заявки 1
Изменение позы 0

Т.е. все вроде бы все есть, заявка зарегистрирована, но вот поза не открывается.

https://yadi.sk/d/3qY_O6cZ3EDdxt

**Comment by mikasoukhov** [comment]
Проверьте на последней версии.
