### ISSUE TITLE
Не подключается QUIK по адресам заданным пользователем в Lua файле

### ISSUE THREAD

**Issue by Pelmen32** [StockSharp/StockSharp#293]
1. Устанавливаю переменные в файле настроек Lua на значения по умолчанию
TransactionAddress="127.0.0.1:5001" и для MarketDataAddress="127.0.0.1:5001"

Подключаю Quik - все подключается.

Прилагаю начало лог-файла
2017/03/03 00:04:53.079| |LuaServer |OnInit
2017/03/03 00:04:53.093| |FixServer |Server 0.0.0.0:5001 started.
2017/03/03 00:04:53.094| |FixServer |FixServer started.
2017/03/03 00:04:53.095| |LuaServer |OnInit done
2017/03/03 00:04:53.095| |FixServer |FixServer outgoing thread started.
2017/03/03 00:04:53.100| |LuaServer |Main
2017/03/03 00:04:57.977| |FixServer |Connected '127.0.0.1:4829' to '0.0.0.0:5001'.
2017/03/03 00:04:57.988| |FixServer |Received first byte from '127.0.0.1:4829'.
2017/03/03 00:04:57.990| |FixServer |Connected '127.0.0.1:4830' to '0.0.0.0:5001'.
2017/03/03 00:04:57.990| |FixServer |Received first byte from '127.0.0.1:4830'.
2017/03/03 00:04:57.994| |FixServer |From : Logon
2017/03/03 00:04:57.994| |FixServer |From : Logon
2017/03/03 00:04:58.001| |FixServer |Клиент quik (127.0.0.1:4829) авторизован.
2017/03/03 00:04:58.001| |FixServer |Клиент quik (127.0.0.1:4830) авторизован.
2017/03/03 00:04:59.298| |FixServer |Отправка Logon клиенту.
2017/03/03 00:04:59.298| |FixServer |Отправка Logon клиенту.
2017/03/03 00:04:59.304|Debug |FixServer |To client quik (127.0.0.1:4830): 8=FIX.4.4^9=59^35=A^49=quik^56=StockSharpMD^52=20170302-21:04:59.300^34=1^10=047^
2017/03/03 00:04:59.304| |FixServer |Сессия запущена.
2017/03/03 00:04:59.304|Debug |FixServer |To client quik (127.0.0.1:4829): 8=FIX.4.4^9=59^35=A^49=quik^56=StockSharpTS^52=20170302-21:04:59.300^34=1^10=069^
2017/03/03 00:04:59.304| |FixServer |Сессия запущена.
2017/03/03 00:04:59.304|Debug |FixServer |Сессия ''. Получено: 'FIX.4.4^9=94^35=A^49=quik^56=StockSharpMD^52=20170302-21:04:57.990^34=1^98=0^108=0^141=Y^553=quik^554=quik^10=121^'

2. Закрываю QUIK, меняю в этом же файле настроек Lua порт на 5002
TransactionAddress="127.0.0.1:5002" и для MarketDataAddress="127.0.0.1:5002"

При подключении к Quik в программе также заменяю адрес подключения:
Trader = new QuikTrader(_quikPath)
{
IsDde = false,
LuaFixServerAddress = "127.0.0.1:5002".To<EndPoint>(),
};

Запускаю подключение - подключение не происходит, не приходит событие Connected

Прилагаю часть лог-файла:
2017/03/03 00:32:08.256| |LuaServer |OnInit
2017/03/03 00:32:08.270| |FixServer |Server 0.0.0.0:5002 started.
2017/03/03 00:32:08.271| |FixServer |FixServer started.
2017/03/03 00:32:08.271| |LuaServer |OnInit done
2017/03/03 00:32:08.272| |FixServer |FixServer outgoing thread started.
2017/03/03 00:32:08.276| |LuaServer |Main
2017/03/03 00:32:24.847|Debug |LuaServer |OnParam
2017/03/03 00:32:24.852|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.852|Debug |LuaServer |OnParam
2017/03/03 00:32:24.852|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.852|Debug |LuaServer |OnParam
2017/03/03 00:32:24.852|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.855|Debug |LuaServer |OnParam
2017/03/03 00:32:24.855|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.857|Debug |LuaServer |OnParam
2017/03/03 00:32:24.857|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.859|Debug |LuaServer |OnParam
2017/03/03 00:32:24.859|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.860|Debug |LuaServer |OnParam
2017/03/03 00:32:24.860|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.862|Debug |LuaServer |OnParam
2017/03/03 00:32:24.862|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.863|Debug |LuaServer |OnParam
2017/03/03 00:32:24.863|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.864|Debug |LuaServer |OnParam
2017/03/03 00:32:24.864|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.866|Debug |LuaServer |OnParam
2017/03/03 00:32:24.866|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.867|Debug |LuaServer |OnParam
2017/03/03 00:32:24.867|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.868|Debug |LuaServer |OnParam
2017/03/03 00:32:24.868|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.869|Debug |LuaServer |OnParam
2017/03/03 00:32:24.869|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.871|Debug |LuaServer |OnParam
2017/03/03 00:32:24.871|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.872|Debug |LuaServer |OnParam
2017/03/03 00:32:24.872|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.873|Debug |LuaServer |OnParam
2017/03/03 00:32:24.873|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.875|Debug |LuaServer |OnParam
2017/03/03 00:32:24.875|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.875|Debug |LuaServer |OnParam
2017/03/03 00:32:24.875|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.875|Debug |LuaServer |OnParam
2017/03/03 00:32:24.875|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam
2017/03/03 00:32:24.876|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam
2017/03/03 00:32:24.877|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam
2017/03/03 00:32:24.878|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam
2017/03/03 00:32:24.879|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.880|Debug |LuaServer |OnParam
2017/03/03 00:32:24.880|Debug |LuaServer |OnParam done
2017/03/03 00:32:24.916|Debug |LuaServer |OnQuote
2017/03/03 00:32:24.923|Debug |LuaServer |Out. QuoteChange,T(L)=0001.01.01 00:00:00.000,T(S)=2017.03.03 00:32:24.918

3. Если изменить порт только для адреса TransactionAddress="127.0.0.1:5002",
а для другого адреса оставить адрес по умолчанию MarketDataAddress="127.0.0.1:5001"

В программе адрес оставляем 127.0.0.1:5002".To<EndPoint>()
То событие Connected приходит, приходят инструменты, портфели, строятся свечки

Лог следующий:
2017/03/03 00:37:51.890| |LuaServer |OnInit
2017/03/03 00:37:51.904| |FixServer |Server 0.0.0.0:5002 started.
2017/03/03 00:37:51.904| |FixServer |Server 0.0.0.0:5001 started.
2017/03/03 00:37:51.905| |FixServer |FixServer started.
2017/03/03 00:37:51.905| |LuaServer |OnInit done
2017/03/03 00:37:51.906| |FixServer |FixServer outgoing thread started.
2017/03/03 00:37:51.911| |LuaServer |Main
2017/03/03 00:38:02.304| |FixServer |Connected '127.0.0.1:6164' to '0.0.0.0:5001'.
2017/03/03 00:38:02.315| |FixServer |Received first byte from '127.0.0.1:6164'.
2017/03/03 00:38:02.317| |FixServer |Connected '127.0.0.1:6165' to '0.0.0.0:5001'.
2017/03/03 00:38:02.317| |FixServer |Received first byte from '127.0.0.1:6165'.
2017/03/03 00:38:02.322| |FixServer |From : Logon
2017/03/03 00:38:02.323| |FixServer |From : Logon
2017/03/03 00:38:02.332| |FixServer |Клиент quik (127.0.0.1:6165) авторизован.
2017/03/03 00:38:02.332| |FixServer |Клиент quik (127.0.0.1:6164) авторизован.
2017/03/03 00:38:03.618| |FixServer |Отправка Logon клиенту.
2017/03/03 00:38:03.618| |FixServer |Отправка Logon клиенту.
2017/03/03 00:38:03.622|Debug |FixServer |To client quik (127.0.0.1:6165): 8=FIX.4.4^9=59^35=A^49=quik^56=StockSharpMD^52=20170302-21:38:03.619^34=1^10=056^
2017/03/03 00:38:03.622| |FixServer |Сессия запущена.
2017/03/03 00:38:03.622|Debug |FixServer |To client quik (127.0.0.1:6164): 8=FIX.4.4^9=59^35=A^49=quik^56=StockSharpTS^52=20170302-21:38:03.619^34=1^10=078^
2017/03/03 00:38:03.622| |FixServer |Сессия запущена.
2017/03/03 00:38:03.622|Debug |FixServer |Сессия ''. Получено: 'FIX.4.4^9=94^35=A^49=quik^56=StockSharpMD^52=20170302-21:38:02.317^34=1^98=0^108=0^141=Y^553=quik^554=quik^10=111^'
2017/03/03 00:38:03.622|Debug |FixServer |Сессия ''. Получено: 'FIX.4.4^9=94^35=A^49=quik^56=StockSharpTS^52=20170302-21:38:02.314^34=1^98=0^108=0^141=Y^553=quik^554=quik^10=130^'

**Comment by mikasoukhov** [comment]
Просьба задать ваш вопрос на форуме http://stocksharp.ru/community/
