### ISSUE TITLE
Не работает автоматическая прокрутка графика, свойство IsAutoScroll=True

### ISSUE THREAD

**Issue by Pelmen32** [StockSharp/StockSharp#294]
Добрый день,

Установлено Windows 8.1
Visual Studio 2012 Ultimate, Net Framework 4.5.2

Использую последнюю версию библиотеки StockSharp 4.3.19.5

В коде вывода на график свечек из Quik, не работает свойство IsAutoScroll=True

Свечи на график выводятся, доходят до конца видимой области графика, далее их не видно, только метки видно изменение значений меток на оси.

Еще маркер на оси Y отображает только значение закрытия последней сформированной свечи, по изменению текущей (несформированной) свечи, маркер не изменяет своего значения.

Код следующий:
private void CandlesBtn_Click(object sender, RoutedEventArgs e)
{
_chart.ClearAreas();
_area = new ChartArea();

_area.YAxises.First().AutoRange = true;

_chart.IsAutoScroll = true;

_chart.ShowOverview = true;

_chart.ChartTheme = "BlackSteel";

_shortMA = new SimpleMovingAverage{Length = 10};
_indElement = new ChartIndicatorElement();
_chart.AddElement(_area,_indElement);

//создаем элемент графика
_candleElem = new ChartCandleElement();
_area.Elements.Add(_candleElem);

if (QuikConnection.IsConnected)
{
_candleManager = new CandleManager(ConnectionInterface.Trader); //для Quik

_candleSeries5 = new CandleSeries(typeof (TimeFrameCandle), ConnectionInterface.SelectedSecurity, _candleTimeFrame);

//устанавливаем расписание для демо QUIK
_candleSeries5.WorkingTime.Periods = new List<WorkingTimePeriod>();
_candleSeries5.WorkingTime.Periods.Add(new WorkingTimePeriod()
{
Times =
{
new Range<TimeSpan>(new TimeSpan(0, 0, 0), new TimeSpan(2, 0, 0)),
new Range<TimeSpan>(new TimeSpan(04, 05, 0), new TimeSpan(23, 59, 59)),
}
});

_candleManager.Processing += DrawElement;

_candleManager.Start(_candleSeries5);

private void DrawElement(CandleSeries series, Candle candle)
{
this.GuiAsync(() =>
{
lock (_locker)
{
var smaValue = _shortMA.Process(candle);

// вычисляем время начала и окончания текущей свечки в реальном времени
var openbounds = _candleTimeFrame.GetCandleBounds(DateTime.Now).Min.LocalDateTime;
var closebounds = _candleTimeFrame.GetCandleBounds(DateTime.Now).Max.LocalDateTime;

if ((candle.State == CandleStates.Finished) && (candle.CloseTime > _previosCloseCandleTime) &&
(candle.OpenTime < openbounds)) //исторические свечки
{
_previosCloseCandleTime = candle.CloseTime;

var data = new ChartDrawData();
data.Group(candle.OpenTime) .Add(_candleElem, candle)
.Add(_indElement,smaValue);
_chart.Draw(data);

}
else if ((candle.State != CandleStates.Finished) &&
(candle.OpenTime >= openbounds) && (candle.CloseTime <= closebounds))
{
//не закрытая свеча реального времени
var data = new ChartDrawData();
data.Group(candle.OpenTime) .Add(_candleElem, candle);
_chart.Draw(data);
}
}
});
}

В ChartPanel свойство IsAutoScroll также не работает, как логически должно быть.

Если установить свойство IsAutoRange = true, то график просто сжимается.
При выводе на него большого количества свечек их становится не видно на графике, т.к. они сливаются между собой.

При установленном свойстве IsAutoRange = true, свойство IsAutoScroll никак не влияет на вывод графика.

При свойствах IsAutoRange = false и _IsAutoScroll = true график не скорллирует.
Ползунок вручную перемещать можно, но хотелось бы, перемещать ползунок из программы.

**Comment by mikasoukhov** [comment]
Просьба задать ваш вопрос на форуме http://stocksharp.ru/community/
