### ISSUE TITLE
Ошибка в marketDepth.GetTheoreticalTrades()...

### ISSUE THREAD

**Issue by Sergey-Dvortsov** [stocksharp/stocksharp#3]
версия S# API 4.2.43.0

Исходный код:

        private void ProcessQuotes(IEnumerable<MarketDepth> marketDepths)
        {
            if (NeededVolume <= 0)
                return;

            lock (_locker)
            {
                foreach (var marketDepth in marketDepths.Where(m => m.Security == Security))
                {
                    if (!marketDepth.Bids.Any() || !marketDepth.Asks.Any()) return;
                    //Суммарный объем
                    _bid.SumVolumes = marketDepth.TotalBidsVolume;
                    _ask.SumVolumes = marketDepth.TotalAsksVolume;
                    //сам сигнал
                    if (_bid.SumVolumes > _ask.SumVolumes)
                    {
                        _bid.Name = "Buy";
                        _ask.Name = "";
                    }
                    else
                    {
                        _bid.Name = "";
                        _ask.Name = "Sell";
                    }
                    //находим среднюю цену исполнения стакана
                  
                    _bid.AverageMarketPrice = marketDepth.GetTheoreticalTrades(Sides.Sell, NeededVolume).Average(t => t.Trade.Price);//.GetAveragePrice(OrderDirections.Sell, NeededVolume);

		_ask.AverageMarketPrice = marketDepth.GetTheoreticalTrades(Sides.Buy, NeededVolume).Average(t => t.Trade.Price);
                    //присваиваем лучшую цену
                    _bid.BestPrice = marketDepth.BestBid.Price;
                    _ask.BestPrice = marketDepth.BestAsk.Price;
                    //находим максимальный объем и цену у него 
                    var maxbidvolume = marketDepth.Bids.Max(s => s.Volume);
                    _bid.MaxVolume = maxbidvolume;
                    _bid.Price = marketDepth.Bids.FirstOrDefault(b => b.Volume == maxbidvolume).Price;

                    var maxaskvolume = marketDepth.Asks.Max(s => s.Volume);
                    _ask.MaxVolume = maxaskvolume;
                    _ask.Price = marketDepth.Asks.FirstOrDefault(b => b.Volume == maxaskvolume).Price;
                    //зажигаем событие
                    OnQuotesChanged();
                }
            }
        }

Ошибка возникает при вызове:

_bid.AverageMarketPrice = marketDepth.GetTheoreticalTrades(Sides.Sell, NeededVolume).Average(t => t.Trade.Price);

System.ArgumentOutOfRangeException was unhandled by user code
  HResult=-2146233086
  Message=Время в формате UTC, представленное при применении смещения, должно находиться в диапазоне от 0 до 10 000 лет.
Имя параметра: offset
  Source=mscorlib
  ParamName=offset
  StackTrace:
       в System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
       в System.DateTimeOffset..ctor(DateTime dateTime)
       в System.DateTimeOffset.op_Implicit(DateTime dateTime)
       в #=qIPGgI$_ZPks9$2M0ef8SuLZqul514QxMBmK_WPmc9zcLO6wWeTCy$EnsBN$NJ7U9.#=qS89uczvUgxx6BkhxmQgoXttNvG5g9J4JIYSDqocpan4=.MoveNext()
       в StockSharp.Algo.Testing.MarketEmulator.#=qhaDw3u2OKwPRZ4GTeEcYhloszQZeybELWSJLOr8_KqA=.#=qP1IMnGXLYKvyBDcqGHR6tw==(Message #=q86qu1d$WRuj0UbfFIEyTrQ==, ICollection`1 #=qdiM0_lufB2EINU0EZ0_vww==)
       в StockSharp.Algo.Testing.MarketEmulator.#=qhaDw3u2OKwPRZ4GTeEcYhloszQZeybELWSJLOr8_KqA=.#=qQscVwekIzHYONhMvC9enTA==(Message #=q4UALlqXuRbQxpSfAujIYHQ==)
       в StockSharp.Algo.Testing.MarketEmulator.SendInMessage(Message message)
       в StockSharp.Algo.TraderHelper.GetTheoreticalTrades(MarketDepth depth, Order order)
       в StockSharp.Algo.TraderHelper.GetTheoreticalTrades(MarketDepth depth, Sides orderDirection, Decimal volume, Decimal price)
       в StockSharp.Algo.TraderHelper.GetTheoreticalTrades(MarketDepth depth, Sides orderDirection, Decimal volume)
       в StrategyRules.Signal.ProcessQuotes(IEnumerable`1 marketDepths) в c:\Users\Sergey\Source\Workspaces\StockSharp\StockSharp\Edu\StockSharp.Edu\03_lesson (Strategy)\StrategyRule\Signal.cs:строка 68
       в Ecng.Common.DelegateHelper.SafeInvoke[T](Action`1 handler, T arg)
       в StockSharp.Algo.Connector.#=qJ0i1MC8mPteL8A7RgIeR90HV9KqZ5X4taXULrbp1pK4=(IEnumerable`1 #=qiqH28yRXsZgeWoGT4gEXNw==)
       в StockSharp.Algo.Connector.#=qipcwupzLR7R5pypfI1iZcUOIJxRQkz8GFBvniaEQj7c=(Security #=qLtnv8$haHFfqANZ2iExQ0w==, QuoteChangeMessage #=qh8_P_Mw$XcnovQxROHNnJw==)
       в StockSharp.Algo.Connector.#=qETOePoBid_elfAn2vzbvyHFcM$_EyhSgJo3qoi$nxUQ=[TMessage](TMessage #=qE9HJVP_xcazKp6qoWNpmRw==, Func`2 #=qcbjPid7EOf5Lfb7YPwJMEg==, Action`2 #=qT5N5KfJWf6ctgLaDe55_$Q==, Boolean #=qzZfvIKuG2TIlLWRPh16CnoiRaUaF2pSCya6cYr$VMis=, String #=qWmSGrZrY_ul3FuezMhdzOuQPeLLyVvnbZ8cWUAoC8Eo=)
       в StockSharp.Algo.Connector.OnProcessMessage(Message message, MessageAdapterTypes adapterType, MessageDirections direction)
  InnerException: 

Информация из отладочного окна Locals:. 
![err_locals](https://cloud.githubusercontent.com/assets/10364235/5637272/f019cce8-960a-11e4-9b63-c8c15ff55cc0.png)

**Comment by mikasoukhov** [comment]
https://github.com/stocksharp/stocksharp/commit/63ea6e131fc501d5d54ca7c2d7d8f253f8a1f64f
