### ISSUE TITLE
 Проблемы QuikLua с Level1 

### ISSUE THREAD

**Issue by MozGangster** [stocksharp/stocksharp#30]
Приходят недостоверные данные по ценам лучшей пары котировок.
подробности http://stocksharp.com/forum/yaf_postst5546_Probliemy-QuikLua-s-Level1.aspx

**Comment by mikasoukhov** [comment]
Скорее всего ошибка из-за коммита с проверкой дубликатов https://github.com/stocksharp/stocksharp/blob/master/Connectors/Quik/Lua/LuaFixServer.cs

**Comment by mikasoukhov** [comment]
Ошибка не воспроизводится.
