### ISSUE TITLE
QuotingStrategy не отрабатывает отмену котируемой заявки

### ISSUE THREAD

**Issue by RomSunZ** [StockSharp/StockSharp#32]
Коннектор Quik Lua, АПИ 4.2.68.
В стратегии QuotingStrategy если котируемая заявка была снята в ручную или системой (например на вечернем клиринге), то стратегия никак не отрабатывает этот момент.
В логе по этой заявке только такие строки:

16:12:35.712| |LQS_SBER@TQBR_10182|Заявка 58272625 (0xF5B24E) принята биржей.
...
16:12:57.155|Debug |LQS_SBER@TQBR_10182|Правило 'Отмена заявки 58272625/811066918 (0xEF627A) OR Полное исполнение 58272625/811066918 (0x311387F) OR Все сделки заявки 58272625/811066918 (0x1C20C5F) OR Ошибка регистрации заявки 58272625/811066918 (0x31E27EC)'. Активация.
16:12:57.155| |LQS_SBER@TQBR_10182|Заявка 58272625 (0xF5B24E) больше не активна.
...
16:13:06.165| |LQS_SBER@TQBR_10182|Отмена заявки 58272625 (0xF5B24E).
16:13:06.165| |LQS_SBER@TQBR_10182|Отмена заявки 58272625 (0xF5B24E).
16:13:06.165|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0xC06E73) OR Изменение стакана инструмента LKOH@TQBR (0x1CC831B)'. Активация.
16:13:16.176|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0x3F19E1D) OR Изменение стакана инструмента LKOH@TQBR (0x25EE953)'. Активация.
16:13:16.176|Debug |LQS_SBER@TQBR_10182|Заявка 58272625 (0xF5B24E) в процессе снятия.
16:13:16.176|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0xC06E73) OR Изменение стакана инструмента LKOH@TQBR (0x1CC831B)'. Активация.
16:13:16.186|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0x3F19E1D) OR Изменение стакана инструмента LKOH@TQBR (0x25EE953)'. Активация.
16:13:16.186|Debug |LQS_SBER@TQBR_10182|Заявка 58272625 (0xF5B24E) в процессе снятия.
16:13:16.186|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0xC06E73) OR Изменение стакана инструмента LKOH@TQBR (0x1CC831B)'. Активация.
16:13:16.191|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0x3F19E1D) OR Изменение стакана инструмента LKOH@TQBR (0x25EE953)'. Активация.
16:13:16.191|Debug |LQS_SBER@TQBR_10182|Заявка 58272625 (0xF5B24E) в процессе снятия.
16:13:16.191|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0xC06E73) OR Изменение стакана инструмента LKOH@TQBR (0x1CC831B)'. Активация.
16:13:16.194|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0x3F19E1D) OR Изменение стакана инструмента LKOH@TQBR (0x25EE953)'. Активация.
16:13:16.194|Debug |LQS_SBER@TQBR_10182|Заявка 58272625 (0xF5B24E) в процессе снятия.
16:13:16.194|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0xC06E73) OR Изменение стакана инструмента LKOH@TQBR (0x1CC831B)'. Активация.
16:13:16.198|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0x3F19E1D) OR Изменение стакана инструмента LKOH@TQBR (0x25EE953)'. Активация.
16:13:16.198|Debug |LQS_SBER@TQBR_10182|Заявка 58272625 (0xF5B24E) в процессе снятия.
16:13:16.198|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0xC06E73) OR Изменение стакана инструмента LKOH@TQBR (0x1CC831B)'. Активация.
16:13:16.211|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0x3F19E1D) OR Изменение стакана инструмента LKOH@TQBR (0x25EE953)'. Активация.
16:13:16.211|Debug |LQS_SBER@TQBR_10182|Заявка 58272625 (0xF5B24E) в процессе снятия.
16:13:16.211|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0xC06E73) OR Изменение стакана инструмента LKOH@TQBR (0x1CC831B)'. Активация.
16:13:16.217|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0x3F19E1D) OR Изменение стакана инструмента LKOH@TQBR (0x25EE953)'. Активация.
16:13:16.217|Debug |LQS_SBER@TQBR_10182|Заявка 58272625 (0xF5B24E) в процессе снятия.
16:13:16.217|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0xC06E73) OR Изменение стакана инструмента LKOH@TQBR (0x1CC831B)'. Активация.
...
16:16:49.933|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0x3F19E1D) OR Изменение стакана инструмента LKOH@TQBR (0x25EE953)'. Активация.
16:16:49.933|Debug |LQS_SBER@TQBR_10182|Заявка 58272625 (0xF5B24E) в процессе снятия.
16:16:49.933|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0xC06E73) OR Изменение стакана инструмента LKOH@TQBR (0x1CC831B)'. Активация.
16:16:52.980|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0x3F19E1D) OR Изменение стакана инструмента LKOH@TQBR (0x25EE953)'. Активация.
16:16:52.980|Debug |LQS_SBER@TQBR_10182|Заявка 58272625 (0xF5B24E) в процессе снятия.
16:16:52.980|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0xC06E73) OR Изменение стакана инструмента LKOH@TQBR (0x1CC831B)'. Активация.
16:16:53.968|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0x3F19E1D) OR Изменение стакана инструмента LKOH@TQBR (0x25EE953)'. Активация.
16:16:53.968|Debug |LQS_SBER@TQBR_10182|Заявка 58272625 (0xF5B24E) в процессе снятия.
16:16:53.968|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0xC06E73) OR Изменение стакана инструмента LKOH@TQBR (0x1CC831B)'. Активация.
16:16:58.015|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0x3F19E1D) OR Изменение стакана инструмента LKOH@TQBR (0x25EE953)'. Активация.
16:16:58.015|Debug |LQS_SBER@TQBR_10182|Заявка 58272625 (0xF5B24E) в процессе снятия.
16:16:58.015|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0xC06E73) OR Изменение стакана инструмента LKOH@TQBR (0x1CC831B)'. Активация.
16:17:00.090|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0x3F19E1D) OR Изменение стакана инструмента LKOH@TQBR (0x25EE953)'. Активация.
16:17:00.090|Debug |LQS_SBER@TQBR_10182|Заявка 58272625 (0xF5B24E) в процессе снятия.
16:17:00.090|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0xC06E73) OR Изменение стакана инструмента LKOH@TQBR (0x1CC831B)'. Активация.
16:17:02.904|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0x3F19E1D) OR Изменение стакана инструмента LKOH@TQBR (0x25EE953)'. Активация.
16:17:02.904|Debug |LQS_SBER@TQBR_10182|Заявка 58272625 (0xF5B24E) в процессе снятия.
16:17:02.904|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0xC06E73) OR Изменение стакана инструмента LKOH@TQBR (0x1CC831B)'. Активация.
16:17:04.136|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0x3F19E1D) OR Изменение стакана инструмента LKOH@TQBR (0x25EE953)'. Активация.
16:17:04.136|Debug |LQS_SBER@TQBR_10182|Заявка 58272625 (0xF5B24E) в процессе снятия.
16:17:04.136|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0xC06E73) OR Изменение стакана инструмента LKOH@TQBR (0x1CC831B)'. Активация.
16:17:05.122|Debug |LQS_SBER@TQBR_10182|Правило 'Изменение стакана инструмента SBER@TQBR (0x3F19E1D) OR Изменение стакана инструмента LKOH@TQBR (0x25EE953)'. Активация.
16:17:05.122|Debug |LQS_SBER@TQBR_10182|Заявка 58272625 (0xF5B24E) в процессе снятия.
и т.д . до бесконечности...
Логичнее было-бы сделать остановку стратегии.

**Comment by mikasoukhov** [comment]
Потому что не выставлена настройка у стратегии.
