### ISSUE TITLE
Ошибка метода StorageRegistry.GetMarketDepthStorage(Security)

### ISSUE THREAD

**Issue by Sergey-Dvortsov** [stocksharp/stocksharp#34]
Версия s# 4.2.70

При повторном запуске метода StorageRegistry.GetMarketDepthStorage(Security) возникает "Ошибка чтения файла"..

При первом запуске функции в каталоге хранилища создается quotesDates.bin нулевой длины (очевидно ошибка при сериализации)..

Код функции:   (пример MarketDepthAnalyzer для группы обучения)

private void GetDataClick(object sender, RoutedEventArgs e)
{
	try
	{
	//создаем хранилище
	var storage = new StorageRegistry();
	//указать напрямую расположение файла. по умолчанию находится в папке дебаг
	((LocalMarketDataDrive)storage.DefaultDrive).Path = @"C:\Users\Sergey\Documents\StockSharp\4.2.43";
	var security = new Security
	{
		Code = "RIZ2",
		Board = ExchangeBoard.Forts,
		Id = "RIZ2@FORTS",
	};
	var quotesStorage = storage.GetMarketDepthStorage(security);
	//загружаем все данные
	DrawData(quotesStorage.Load());
	}
	catch (System.Exception ex)
	{
		Debug.WriteLine(ex.Message + " " + ex.StackTrace);
	}
}

Текст ошибки:

Ошибка чтения файла C:\Users\Sergey\Documents\StockSharp\4.2.43\R\RIZ2@FORTS\quotesDates.bin.    в StockSharp.Algo.Storages.LocalMarketDataDrive.LocalMarketDataStorageDrive.LoadDates()
   в StockSharp.Algo.Storages.LocalMarketDataDrive.LocalMarketDataStorageDrive.<.ctor>b__11()
   в System.Lazy`1.CreateValue()
   в System.Lazy`1.LazyInitValue()
   в System.Lazy`1.get_Value()
   в StockSharp.Algo.Storages.LocalMarketDataDrive.LocalMarketDataStorageDrive.get_DatesDict()
   в StockSharp.Algo.Storages.LocalMarketDataDrive.LocalMarketDataStorageDrive.get_Dates()
   в StockSharp.Algo.Storages.MarketDataStorage`2.StockSharp.Algo.Storages.IMarketDataStorage.get_Dates()
   в StockSharp.Algo.Storages.StorageHelper.GetRange(IMarketDataStorage storage, Nullable`1 from, Nullable`1 to)
   в StockSharp.Algo.Storages.StorageHelper.Load[TData](IMarketDataStorage`1 storage, Nullable`1 from, Nullable`1 to)
   в MarketDepthAnalyzer.MainWindow.GetDataClick(Object sender, RoutedEventArgs e) в c:\Users\Sergey\Source\Workspaces\StockSharp\StockSharp\Edu\StockSharp.Edu\Strategies\Public\MarketDepthAnalyzer\MainWindow.xaml.cs:строка 81

**Comment by mikasoukhov** [comment]
http://stocksharp.com/forum/yaf_postst5556_S--Api.aspx
