### ISSUE TITLE
Не правильное значение лучшей цены в стакане (повторно)

### ISSUE THREAD

**Issue by RomSunZ** [StockSharp/StockSharp#36]
АПИ 4.2.72, коннектор Quik lua.
Периодически получаю неверное значение лучшей цены в стакане, которая находится в середине противоположных котировок:
Код:
            var md = this.Connector.GetFilteredMarketDepth(this.Security);

			Sides? badside = null;
			//проверим, есть ли "плохая" лучшая цена
			if (md.Asks.Count() > 1 && md.Bids.Count() > 1)
			{
				if (md.Asks[0].Price<md.Bids[0].Price)
				{
					//есть попандос
					if (md.Asks[0].Price < md.Bids[1].Price) badside = Sides.Sell;
					else if (md.Bids[0].Price > md.Asks[1].Price) badside = Sides.Buy;
				}
			}
			if (badside != null) this.AddErrorLog("В стакане не верная лучшая цена по направлению {0}", badside);

Вместо Asks и Bids можно использовать GetQuotes, GetFilteredQuotes, вместо GetFilteredMarketDepth использовать GetMarketDepth - результат одинаковый. Закономерность появления "плохой" лучшей цены выявить не удалось. Может выскочить с утра, может к вечеру, а может и вообще несколько дней не появляться.

**Comment by RomSunZ** [comment]
Стакан в ЛУА формируется вообще не правильно. Мало того, что вместо лучшей цены "зависает" какая-то старая цена (думаю, что не удаляются какие-то цены или заявки из стакана), так еще эти "левые" цены могут быть на любом уровне стакана (0, 1, и т.п.). Для тех, кому важен стакан - не советую использовать коннектор ЛУА. Мне это стоило реальных денег.

**Comment by mikasoukhov** [comment]
1. Ваши деньги - это ваши деньги.
2. Комментарий был дан месяц назад еще на форуме.

**Comment by RomSunZ** [comment]
А вы уверены, что проблема в квике, а не в логике вашего коннектора? Я случайно нашел сайт, на котором представлены скрипты LUA для Quik. Вот один из них, который формирует стакан: http://forum.qlua.org/topic344.html, так вот в момент, когда стокшарп выдает неправильный стакан, стакан из луа-скрипта формируется без каких-либо артефактов. Посмотрите, если ваша религия позволит это...

**Comment by mikasoukhov** [comment]
Религия тут только одна - опен сорс. Если вы не понимаете что это такое, то не нужно строчить ишью больше.

**Comment by RomSunZ** [comment]
Где в опен соурс исходники StockSharp.QuikLua.dll?

**Comment by mikasoukhov** [comment]
Я уже все месяц назад отписал на форуме, что и как. Не буду повторяться.
