### ISSUE TITLE
Ошибка в GetFilteredQuots

### ISSUE THREAD

**Issue by RomSunZ** [stocksharp/stocksharp#4]
Периодически сталкиваюсь с ошибкой при вызове GetFilteredQuotes. На скриншоте данные GetFilteredQuots(Sides.Buy), на которых элемент с индексом 0 взят неизвестно от куда, а вторым идет Best Bid. В результате заявка на покупку ставится не относительно лучшей цены в стакане, а в самый хвост стакана. Для продажи ситуация симметричная, элемент с индексом 0 выдается непонятное значение из хвоста стакана, а вторым идет лучшая цена.
В какие моменты возникает так и не понял, сначала несколько часов работает нормально, потом сталкиваюсь с этой проблемой.

Для Михаила Сухова в двух предложениях:
Через несколько часов работы робота при вызове в стратегии функции GetFilteredQuotes вместо наилучшей цены по индексу 0 выдается непонятное значение цены. На скриншоте приведен скрин из вижуал студио со значениями переменной, в которую положены результаты вызова функции GetFilteredQuotes (левая часть) и значения лучшей цены, которые выдает функция GetFilteredMarketDepth (правая часть скриншота)
![getfilteredquotes1](https://cloud.githubusercontent.com/assets/10460695/5677870/23e9fcf2-9816-11e4-8a79-400c6b90cd61.jpg)

**Comment by mikasoukhov** [comment]
Они и не должны быть синхронизованы, так как берутся из разных источников.
