### ISSUE TITLE
Alpha Vantage Not Pulling Intraday Data?

### ISSUE THREAD

**Issue by windowshopr** [StockSharp/StockSharp#429]
Wondering what needs to be done to get intraday data from AV? I don't have a premium API key, just their free one, so I imagine the limit of 500 calls per day, and less than 5 calls per minute, apply here which is why I set the work interval parameter to 20 seconds (ensures 4 calls per minute).

The rows say finished, but no actual data is downloaded?

![image](https://github.com/StockSharp/StockSharp/assets/40477419/2e499e2b-f7c9-447a-9e29-4151c0bcafbe)

**Comment by mikasoukhov** [comment]
Finished means - no more data. Cause Hydra is client side tool only please feel free contain AV directly.

**Comment by windowshopr** [comment]
No more data? Pretty certain Alpha Vantage would have plenty of intraday data for the ticker symbol "SPY" :P I do know that they have recently changed their API structure for the intraday data, and not daily/weekly/monthly, which might explain this issue from StockSharp's side. Can someone confirm if this is correct by reviewing their updated intraday endpoint here to ensure StockSharp's logic is still accurate:

https://www.alphavantage.co/documentation/#intraday

**Comment by mikasoukhov** [comment]
Yes, you are right. They made some changes. We will update Hydra next week and try put the fixes into upcoming release. You will get the notification via our Installer when the update will be available (or track our blog).
