### ISSUE TITLE
Ошибка при закачке маркетдаты Гирдой, источник Quik

### ISSUE THREAD

**Issue by Sergey-Dvortsov** [StockSharp/StockSharp#43]
Hydra 4.2.71, Lua 4.2.71, Quik 6.17.0,58, брокер Уралсиб

При закачке данных при помощи Гидры (сделки, стаканы) с источником Quik постоянно возникают нижеследующие ошибки:

3:23:58.945|Error  |Quik      |System.ArgumentException: 3:23:58.945|Error  |Quik      |System.ArgumentException: Элемент с тем же ключом уже был добавлен.
   в System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   в System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   в System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   в StockSharp.Algo.TraderHelper.GetDelta(IEnumerable`1 from, IEnumerable`1 to, Sides side)
   в StockSharp.Algo.TraderHelper.GetDelta(QuoteChangeMessage from, QuoteChangeMessage to)
   в StockSharp.Algo.Storages.QuoteSerializer.OnSave(BitArrayWriter writer, IEnumerable`1 messages, QuoteMetaInfo metaInfo)
   в StockSharp.Algo.Storages.BinaryMarketDataSerializer`2.Serialize(IEnumerable`1 data, IMarketDataMetaInfo metaInfo)
   в StockSharp.Algo.Storages.MarketDataStorage`2.Save(Stream stream, IMarketDataMetaInfo metaInfo, TData[] data, Boolean isOverride)
   в StockSharp.Algo.Storages.MarketDataStorage`2.Save(IEnumerable`1 data)
   в StockSharp.Algo.Storages.StorageRegistry.ConvertableStorage`3.StockSharp.Algo.Storages.IMarketDataStorage<TEntity>.Save(IEnumerable`1 data)
   в StockSharp.Hydra.Core.BaseHydraTask.SafeSave[T](Security security, Type messageType, Object arg, IEnumerable`1 values, Func`2 getTime, IEnumerable`1 getErrors, Func`4 getStorage)
13:23:58.945|       |Quik      |Для GAZP@TQBR загружено 2 QuoteChangeMessage ().
   в System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   в System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   в System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   в StockSharp.Algo.TraderHelper.GetDelta(IEnumerable`1 from, IEnumerable`1 to, Sides side)
   в StockSharp.Algo.TraderHelper.GetDelta(QuoteChangeMessage from, QuoteChangeMessage to)
   в StockSharp.Algo.Storages.QuoteSerializer.OnSave(BitArrayWriter writer, IEnumerable`1 messages, QuoteMetaInfo metaInfo)
   в StockSharp.Algo.Storages.BinaryMarketDataSerializer`2.Serialize(IEnumerable`1 data, IMarketDataMetaInfo metaInfo)
   в StockSharp.Algo.Storages.MarketDataStorage`2.Save(Stream stream, IMarketDataMetaInfo metaInfo, TData[] data, Boolean isOverride)
   в StockSharp.Algo.Storages.MarketDataStorage`2.Save(IEnumerable`1 data)
   в StockSharp.Algo.Storages.StorageRegistry.ConvertableStorage`3.StockSharp.Algo.Storages.IMarketDataStorage<TEntity>.Save(IEnumerable`1 data)
   в StockSharp.Hydra.Core.BaseHydraTask.SafeSave[T](Security security, Type messageType, Object arg, IEnumerable`1 values, Func`2 getTime, IEnumerable`1 getErrors, Func`4 getStorage)

18:06:10.840|Warning|Quik      |Для ROSN@TQBR невозможно сохранить 1 QuoteChangeMessage по причине 'Цена лучшего бида больше цены лучшего офера.'.
18:06:11.842|       |Quik      |Для GAZP@TQBR загружено 3 QuoteChangeMessage ().

**Comment by Sergey-Dvortsov** [comment]
Приоритет высокий... 
У меня эта ошибка не воспроизводится..

**Comment by mikasoukhov** [comment]
Надо проверить на Гидре 4.3. Если воспроизведется, то открою заново.
