### ISSUE TITLE
Исполнение рыночных ордеров при тестировании на свечах.

### ISSUE THREAD

**Issue by mazlov1989** [StockSharp/StockSharp#439]
Сейчас рыночные ордера при тестировании на свечах исполняются по средней цене свечи. Я долго искал причину этого и нашел метод MatchOrderByCandle в классе StockSharp.Algo.Testing.MarketEmulator. Там цена исполнения определяется методом GetMiddlePrice. 

Хотелось бы в данном контексте иметь некоторую степень свободы в выборе цены исполнения. Этот выбор можно разместить настройках эмулятора (StockSharp.Algo.Testing.MarketEmulatorSettings). Пусть в этом файле будет пункт регламентирующий по какой цене исполняется рыночный ордер в рамках тестирования на свечах: Middle/Open/High/Low/Close.

**Comment by mikasoukhov** [comment]
https://github.com/StockSharp/StockSharp/commit/a0c7e79c9279e24d29457766f8ead0ebfab0f2c3
