### ISSUE TITLE
IQFeed Futures data request

### ISSUE THREAD

**Issue by jasonnator** [StockSharp/StockSharp#44]
English:
Sample -> IQFeed -> HistoryCandlesWindow.xaml.cs

var candles = MainWindow.Instance.Trader.GetHistoricalCandles(_security, typeof(TimeFrameCandle), (TimeSpan)TimeFramePicker.SelectedValue, (DateTime)DateFromPicker.Value, (DateTime)DateToPicker.Value, out isSuccess);

problem: _security includes "@xxxx" where xxxx is the exchange (ALL, NYMEX, etc.)

solution (hack)
// HACK: remove exchange from future contract
if (_security.Id.Substring(0, 1) == "@" || _security.Id.Substring(0, 1) == "+")
		        _security.Id = _security.Code;

Verified to work with M6E#, 6N#, ES#, etc.

Russian:
Sample -> IQFeed -> HistoryCandlesWindow.xaml.cs

var candles = MainWindow.Instance.Trader.GetHistoricalCandles(_security, typeof(TimeFrameCandle), (TimeSpan)TimeFramePicker.SelectedValue, (DateTime)DateFromPicker.Value, (DateTime)DateToPicker.Value, out isSuccess);

Проблема: _security включает в себя "xxxx", где ХХХХ обмен (ALL, NYMEX, и т.д.)

решение (хак)
// Код: удалить обмена из будущего контракта
if (_security.Id.Substring(0, 1) == "@" || _security.Id.Substring(0, 1) == "+")
		        _security.Id = _security.Code;

Проверенные работать с M6E #, 6 н #, Е. С. #, и т.д.

**Comment by mikasoukhov** [comment]
Hi Jason

1. Please use one lang in bug reports.
2. Can you clarify the problem? Because Security.Id should to include exchange code (electronic board code from where market data were received). Security.Id = Symbol@Board

**Comment by jasonnator** [comment]
1.  Ok, no problem.
2.  below:

When trying to pull futures data in hydra or studio (used precompiled binaries from web), no information would ever get pulled in using IQFeed as the connector.  So then I pulled the latest Github source and tried the sample IQFeed project and AAPL will pull data fine but still not any futures.  I inserted a break point at HistoryCandlesWindow.xaml.cs and looked at the _security parameter.  Since @ES#@ALL is an invalid id at IQFeed, I always got an invalid security error from the sample program.

I used the hack above to parse off the @ALL and the sample program worked fine and was able to pull the candles in to populate the chart.

**Comment by jasonnator** [comment]
IQFeed ES symbol lookup:
http://www.iqfeed.net/symbolguide/index.cfm?symbolguide=lookup&displayaction=support&section=guide&web=iqfeed&alpha=1&start=1

StockSharp appears to be querying IQFeed with @ES@ALL which is invalid

**Comment by mikasoukhov** [comment]
Jason

Just to check. For other symbols that didn't have **@** symbol you look same problem?

**Comment by jasonnator** [comment]
+CL# gave me a permissions error which is not correct because I can get quotes to Crude Oil with NinjaTrader so I know I have permissions.  I can screen share on skype if you'd like.

**Comment by mikasoukhov** [comment]
http://stocksharp.com/forum/yaf_profile44.aspx my contacts

**Comment by jasonnator** [comment]
Fix has been identified and check in.
