### ISSUE TITLE
Неправильное время свечи при использовании SubsribeCandles в Транзак

### ISSUE THREAD

**Issue by Sergey-Dvortsov** [StockSharp/StockSharp#46]
При запросе исторических свечей посредством метода SubsribeCandles, в коннекторе Transaq время открытия свечи сдвинуто на один интервал в прошлое. Например, должна быть свеча с открытием 20-50, а приходит свеча 20-45.
Ниже приведены записи свечей из Транзак и Финам за аналогичный период:

S# Transaq
Date Time:Open,High,Low,Close.
04/10/2015 18:30:00 +03:00:7126,7129,7116,7129
04/10/2015 18:35:00 +03:00:7129,7157,7122,7147
04/10/2015 18:55:00 +03:00:7155,7168,7133,7137
04/10/2015 19:00:00 +03:00:7138,7148,7133,7137
04/10/2015 19:05:00 +03:00:7138,7141,7130,7141
04/10/2015 19:10:00 +03:00:7141,7141,7112,7124
04/10/2015 19:15:00 +03:00:7123,7140,7114,7132
04/10/2015 19:20:00 +03:00:7132,7140,7127,7131
04/10/2015 19:25:00 +03:00:7130,7140,7129,7129
04/10/2015 19:30:00 +03:00:7128,7132,7122,7131
04/10/2015 19:35:00 +03:00:7130,7138,7129,7132
04/10/2015 19:40:00 +03:00:7132,7138,7132,7137
04/10/2015 19:45:00 +03:00:7132,7175,7123,7135
04/10/2015 19:50:00 +03:00:7135,7142,7132,7138
04/10/2015 19:55:00 +03:00:7138,7150,7138,7145
04/10/2015 20:00:00 +03:00:7144,7149,7140,7143
04/10/2015 20:05:00 +03:00:7144,7147,7136,7140
04/10/2015 20:10:00 +03:00:7142,7144,7137,7144
04/10/2015 20:15:00 +03:00:7144,7145,7136,7136
04/10/2015 20:20:00 +03:00:7136,7139,7132,7139

Финам:
<DATE>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>
20150410,183000,7122,7138,7120,7124,5018
20150410,183500,7126,7129,7116,7129,2878
20150410,184000,7129,7157,7122,7147,9401
20150410,190000,7155,7168,7133,7137,8957
20150410,190500,7138,7148,7133,7137,2555
20150410,191000,7138,7141,7130,7141,1356
20150410,191500,7141,7141,7112,7124,3228
20150410,192000,7123,7140,7114,7132,3288
20150410,192500,7132,7140,7127,7131,1073
20150410,193000,7130,7140,7129,7129,1099
20150410,193500,7128,7132,7122,7131,937
20150410,194000,7130,7138,7129,7132,520
20150410,194500,7132,7138,7132,7137,815
20150410,195000,7132,7175,7123,7135,8887
20150410,195500,7135,7142,7132,7138,1420
20150410,200000,7138,7150,7138,7145,2037
20150410,200500,7144,7149,7140,7143,667
20150410,201000,7144,7147,7136,7140,795
20150410,201500,7142,7144,7137,7144,339
20150410,202000,7144,7145,7136,7136,620

**Comment by Sergey-Dvortsov** [comment]
Приоритет средний.

**Comment by mikasoukhov** [comment]
https://github.com/StockSharp/StockSharp/commit/ab5f11db40bb7cc8ed0c20df5a517b5546e1a397
