### ISSUE TITLE
Ошибка в CommissionTurnOverRule

### ISSUE THREAD

**Issue by OlegFedko** [StockSharp/StockSharp#50]
Если я правильно понял, то суть **CommissionTurnOverRule** в том, чтобы начислять 1 *Value* за каждый 1 *TurnOver*.
Если так, то в **CommissionTurnOverRule.OnProcessExecution** ошибка.

1) *_currentTurnOver* должен сбрасываться на остаток от деления на *TurnOver* (сейчас не сбрасывается вообще и следовательно комиссия далее будет начисляться на каждую сделку, даже если оборот она не превышает)
2) комиссия должна быть *Value * Целое(_currentTurnOver / TurnOver)* (сейчас просто Value, т.е. если за 1 сделку сделать два оборота, то будет 1 комиссия, а не 2).

Возможно в других *OnProcessExecution* с накоплением такая же ошибка.

**Comment by mikasoukhov** [comment]
Будет продуктивнее, если вы предложите свой вариант.

**Comment by mikasoukhov** [comment]
Закрываю таску, так как вариантов не последовало.
