### ISSUE TITLE
Не заполняется  AverageDirectionalIndex.MovingAverage

### ISSUE THREAD

**Issue by rogonke** [StockSharp/StockSharp#52]
Насколько я понял,  проблема в том, что DirectionalIndex.OnProcess на выходе дает DecimalIndicatorValue.
BaseIndicator.Process, получающий это значение, устанавливает флаг IsFinal = true только результатам, которые можно привести к типу ComplexIndicatorValue 
либо SingleIndicatorValue < TResult > (TResult у DirectionalIndex равен ComplexIndicatorValue).

**Comment by mikasoukhov** [comment]
А как вы это проверяли?

Mikhail Sukhov,
StockSharp LLC, http://stocksharp.com

19 апреля 2015 г., 21:52 пользователь rogonke <notifications@github.com>
написал:

**Comment by rogonke** [comment]
Скармливал экземпляру AverageDirectionalIndex.Process() свечи, в дебагере видно, что  
averageDirectionalIndex.Dx.Minus (и Plus) формируются, значения, в их скользящих средних копятся. 
А когда DX сформирован - AverageDirectionalIndex.MovingAverage значения принимать не начинал.
Я посмотрел - DX выдавал значения  IsFinal = false.
С костылем вида:
```
public class DirectionalIndex : BaseComplexIndicator
{
...
	protected override IIndicatorValue OnProcess(IIndicatorValue input)
	{
		...
		var result = value.SetValue(this, diSum != 0m ? (100 * diDiff / diSum) : 0m);
		((DecimalIndicatorValue)result).IsFinal = input.IsFinal;
		return result;
	}
...
}
```
...он работать стал, но я сомневаюсь что это кошерное решение.

**Comment by mikasoukhov** [comment]
Да, это неверное решение. У меня ADX рисуется и нормально заполняется. Видимо проблема тут в том, что вы что-то не так заполняете. Можете привести мини код, воспроизводящий проблему?

**Comment by rogonke** [comment]
Скорее всего, и заранее извиняюсь за то что отнял ваше время. Но меня смущает, что не заполняется только часть составного индикатора, а остальные ведут себя нормально. 
Пример того, что я делаю:

```
    class Program
    {
        static void Main(string[] args)
        {
            String      securityName = "SBER@FORTS";
            var         secIdParts = securityName.Split('@');
            String      historyPath = @"D:\StockSharp\HydraData\";
            TimeSpan    timeFrameHistoryRead = TimeSpan.FromMinutes(1);
            DateTime    dateFrom = new DateTime(2013, 7, 15);
            DateTime    dateTo = new DateTime(2013, 7, 16);

            var security = new Security
            {
                Id = securityName,
                Code = secIdParts[0],
                Board = ExchangeBoard.GetOrCreateBoard(secIdParts[1]),
            };

            var storageRegistry = new StorageRegistry
            {
                DefaultDrive = new LocalMarketDataDrive(historyPath)
            };

            var marketDataStorage = storageRegistry.GetCandleStorage(
                typeof(TimeFrameCandle),
                security,
                timeFrameHistoryRead,
                null,
                StorageFormats.Binary);

            var candles = marketDataStorage.Load(dateFrom, dateTo).ToList();


            Console.WriteLine("candles.Count = " + candles.Count);

            var adx = new AverageDirectionalIndex();
            var di = new DirectionalIndex {Length = 14};

            Console.WriteLine("Candle OpenTime;                  Adx val;              Di val;");
            foreach (var candle in candles.GetRange(0,50))
            {
                candle.State = CandleStates.Finished;

                adx.Process(candle);
                di.Process(candle);

                Console.WriteLine(string.Format("{0};       {1};         {2};",
                    candle.OpenTime,
                    adx.IsFormed ? adx.GetCurrentValue<decimal>().ToString("##.##") : "isn't formed",
                    di.IsFormed ? di.GetCurrentValue<decimal>().ToString("##.##") : "isn't formed"));
            }


            Console.ReadLine();
        }
    }
```

Скриншоты с моими результатами:
https://docs.google.com/document/d/14FmI9WYtM2woCsENYRYY4DxWmXmQPYp0ZUDtSbVma_E/edit?pli=1

**Comment by mikasoukhov** [comment]
Я порефакторил немного классы общие. Но мне кажется что конктрено для ADX стало еще хуже. Вообщем, общую проблему я устранил, но вам немного нужно еще поработать с формулами этого индикатора. Ишью не закрываю.

**Comment by mikasoukhov** [comment]
Таску закрывать?
