### ISSUE TITLE
Ошибка при соединении к Quik в  s# 4.2.75

### ISSUE THREAD

**Issue by Sergey-Dvortsov** [StockSharp/StockSharp#54]
Версия s# 4.2.75, Квик 6.17.1.17
Не коннектится...

Лог Lua:
2015/04/20 18:32:48.155|       |LuaServer |OnInit
2015/04/20 18:32:48.181|       |FixServer |Server 0.0.0.0:5001 started.
2015/04/20 18:32:48.205|       |FixServer |FixServer (outgoing) stopped.
2015/04/20 18:32:48.205|       |FixServer |FixServer started.
2015/04/20 18:32:48.206|       |LuaServer |OnInit done
2015/04/20 18:32:48.251|       |LuaServer |Main
2015/04/20 18:34:00.144|       |FixServer |Connected '127.0.0.1:5903' to '0.0.0.0:5001'.
2015/04/20 18:34:01.133|       |FixServer |Received first byte from '127.0.0.1:5903'.
2015/04/20 18:34:01.160|       |FixServer |From : Logon
2015/04/20 18:34:01.198|       |FixServer |Клиент quik (127.0.0.1:5903) авторизован.
2015/04/20 18:34:05.742|       |FixServer |Отправка Logon клиенту.
2015/04/20 18:34:05.749|       |FixServer |Сессия запущена.
2015/04/20 18:34:16.064|Error  |FixServer |System.IO.IOException: Не удается прочитать данные из транспортного соединения: Удаленный хост принудительно разорвал существующее подключение. ---> System.Net.Sockets.SocketException: Удаленный хост принудительно разорвал существующее подключение
   в System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   в System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- Конец трассировки внутреннего стека исключений ---
   в System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   в System.IO.Stream.ReadByte()
   в StockSharp.Fix.Native.BaseFixReader.ReadByte()
   в StockSharp.Fix.Native.TextFixReader.ReadTag()
   в #=qJublOOhstNGuOqciA4pO0IxEbqusgq8AzTUZ$z4_I7QdDamhxix_6xIpo0q08gJs.#=qFSkNH1E6ksrvdnmrGezbbA==(IFixReader #=qyHB14XScGdVE06FHEgMxZQ==, FixTags #=qHKHjSlBEl8dJccjTaFV94Q==)
   в #=qJublOOhstNGuOqciA4pO0IxEbqusgq8AzTUZ$z4_I7QdDamhxix_6xIpo0q08gJs.#=qYxLyRp9D4RLNmE615p0bhg==(IFixReader #=qjMUDTw7SUe_0KRt5Hr3OIw==, Boolean #=qeHLVtncL2jAcnczVF92hWEFOYnbsI6LNDKA14vzcvxE=, String #=qnp5_Jgq80L$XMFuCxSTvbuW9g7dT2OzNoyyy4yKpxiY=, ILogReceiver #=qLy6FlbS2B0nlLuQVBJrlLA==, String #=qqHxlCuzlbwviGaQ3NdXv5Q==, Func`3 #=qByjHri7T4qfIYiyMbykVjQ==, Action`1 #=qIoFIKYpJwlJ6XnjSBMM1Mg==)
2015/04/20 18:34:16.065|       |FixServer |Disconnect quik (127.0.0.1:5903)

**Comment by Sergey-Dvortsov** [comment]
Приоритет высокий

**Comment by mikasoukhov** [comment]
А лог клиента?

**Comment by dmDen** [comment]
Варианты лога разные:
1) 0001/01/01 00:00:00.000|       |QuikTrader|Connect

2) 0001/01/01 00:00:00.000|Warning|QuikTrader|Невозможно подключиться, так как подключение находится в состоянии Connecting.

3) 2015/04/20 16:57:13.054|Warning|QuikTrader|Невозможно выполнить запуск экспорта, так как экспорт находится в состоянии Connecting.
2015/04/20 16:57:14.690|Error  |QuikTrader|System.InvalidOperationException: Tags should be BodyLength but received BeginString.
   в #=qJublOOhstNGuOqciA4pO0IxEbqusgq8AzTUZ$z4_I7QdDamhxix_6xIpo0q08gJs.#=qFSkNH1E6ksrvdnmrGezbbA==(IFixReader #=qyHB14XScGdVE06FHEgMxZQ==, FixTags #=qHKHjSlBEl8dJccjTaFV94Q==)
   в #=qJublOOhstNGuOqciA4pO0IxEbqusgq8AzTUZ$z4_I7QdDamhxix_6xIpo0q08gJs.#=qYxLyRp9D4RLNmE615p0bhg==(IFixReader #=qjMUDTw7SUe_0KRt5Hr3OIw==, Boolean #=qeHLVtncL2jAcnczVF92hWEFOYnbsI6LNDKA14vzcvxE=, String #=qnp5_Jgq80L$XMFuCxSTvbuW9g7dT2OzNoyyy4yKpxiY=, ILogReceiver #=qLy6FlbS2B0nlLuQVBJrlLA==, String #=qqHxlCuzlbwviGaQ3NdXv5Q==, Func`3 #=qByjHri7T4qfIYiyMbykVjQ==, Action`1 #=qIoFIKYpJwlJ6XnjSBMM1Mg==)
2015/04/20 16:57:14.697|Error  |QuikTrader|System.InvalidOperationException: Процесс подключения был прервал из-за неожиданного отключения. ---> System.InvalidOperationException: Операция является недопустимой из-за текущего состояния объекта.
   в StockSharp.Fix.Native.TextFixReader.ReadTag()
   в #=qJublOOhstNGuOqciA4pO0IxEbqusgq8AzTUZ$z4_I7QdDamhxix_6xIpo0q08gJs.#=qAwQ4Mk7SmxZBE489f$8AYw==(IFixReader #=q_SUGe7pB6o3QcjnHeB$KbA==)
   в #=qJublOOhstNGuOqciA4pO0IxEbqusgq8AzTUZ$z4_I7QdDamhxix_6xIpo0q08gJs.#=qYxLyRp9D4RLNmE615p0bhg==(IFixReader #=qjMUDTw7SUe_0KRt5Hr3OIw==, Boolean #=qeHLVtncL2jAcnczVF92hWEFOYnbsI6LNDKA14vzcvxE=, String #=qnp5_Jgq80L$XMFuCxSTvbuW9g7dT2OzNoyyy4yKpxiY=, ILogReceiver #=qLy6FlbS2B0nlLuQVBJrlLA==, String #=qqHxlCuzlbwviGaQ3NdXv5Q==, Func`3 #=qByjHri7T4qfIYiyMbykVjQ==, Action`1 #=qIoFIKYpJwlJ6XnjSBMM1Mg==)
   в StockSharp.Fix.FixMessageAdapter.#=qweWyZG2wUXWzJVnEXBUa6D4B7JRUWOmx0potxShlbL0=()
   --- Конец трассировки внутреннего стека исключений ---

У меня получается подключиться/отключиться пару раз, затем начинают появляться обозначенные выше ошибки. Снова удается подключиться только после перезагрузки квика. Версии квика и S# те же.

**Comment by mikasoukhov** [comment]
Я не понимаю. Вообще не подключается или не подключается после каких-то действий?

**Comment by mikasoukhov** [comment]
Надо проверить на вот этом коммите https://github.com/StockSharp/StockSharp/commit/70f5516899719a19289ef1c7af171d250b169012
