### ISSUE TITLE
Гидра не находит данные по транзакциям

### ISSUE THREAD

**Issue by Sergey-Dvortsov** [StockSharp/StockSharp#62]
Hydra 4.3.0.0, Quik 6.17.17
При экспорте транзакций гидра не находит данные. 
![exec_err](https://cloud.githubusercontent.com/assets/10364235/7411668/d4e604a0-ef42-11e4-92ce-2edd3078b3de.png)
![exec_err2](https://cloud.githubusercontent.com/assets/10364235/7411669/d4e6a96e-ef42-11e4-9f80-8d8da8c5778a.png)

**Comment by mikasoukhov** [comment]
А что в самом папке с данными? Данные есть?

**Comment by Sergey-Dvortsov** [comment]
Файла execution в папке с данными нет.. При этом в окне источника показывает, что загружено 6 транзакций..
![transaction](https://cloud.githubusercontent.com/assets/10364235/7413125/c502a372-ef51-11e4-9188-854e095a1cb1.png)
