### ISSUE TITLE
Не вызывается событие NewSecurities

### ISSUE THREAD

**Issue by Sergey-Dvortsov** [StockSharp/StockSharp#64]
Версия s# 4.3.0.0,  Quik 6.17.1.17

Не вызывается событие connector.NewSecurities

015/04/30 19:41:18.942|       |LuaServer |OnInit
2015/04/30 19:41:18.967|       |FixServer |Server 0.0.0.0:5001 started.
2015/04/30 19:41:18.968|       |FixServer |FixServer started.
2015/04/30 19:41:18.970|       |LuaServer |OnInit done
2015/04/30 19:41:19.011|       |LuaServer |Main
2015/04/30 19:42:01.937|       |FixServer |Connected '127.0.0.1:9868' to '0.0.0.0:5001'.
2015/04/30 19:42:02.105|       |FixServer |Received first byte from '127.0.0.1:9868'.
2015/04/30 19:42:02.116|       |FixServer |From : Logon
2015/04/30 19:42:02.253|       |FixServer |Клиент quik (127.0.0.1:9868) авторизован.
2015/04/30 19:42:07.646|       |FixServer |Отправка Logon клиенту.
2015/04/30 19:42:07.679|       |FixServer |Сессия запущена.
2015/04/30 19:42:07.684|       |FixServer |From quik 127.0.0.1:9868: OrderMassStatusRequest
2015/04/30 19:42:07.734|       |FixServer |From quik 127.0.0.1:9868: RequestForPositions
2015/04/30 19:42:07.735|       |LuaServer |Request: Type = OrderStatus TrId = 70920167 Value =  SecId =  OrdType =  IsSubscribe = False DataType = Level1
2015/04/30 19:42:07.736|       |LuaServer |LookupStopOrders
2015/04/30 19:42:07.738|       |LuaServer |Stop orders count: 0
2015/04/30 19:42:07.738|       |LuaServer |LookupStopOrders done
2015/04/30 19:42:07.739|       |LuaServer |LookupOrders
2015/04/30 19:42:07.740|       |LuaServer |Orders count: 31
2015/04/30 19:42:07.753|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.764|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.819|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.819|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.819|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.819|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.819|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.819|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.820|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.820|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.821|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.821|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.821|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.821|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.821|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.821|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.821|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.821|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.821|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.821|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.821|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.821|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.822|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.822|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.822|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.822|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.822|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.822|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.822|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.822|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.822|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.822|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.822|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.822|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.823|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.823|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.823|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.823|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.823|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.823|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.825|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.825|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.825|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.825|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.825|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.825|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.826|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.826|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.826|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.826|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.826|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.826|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.826|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.826|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.826|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.826|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.826|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.826|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.827|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.827|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.827|       |FixServer |Added trans id 70920167 mapping.
2015/04/30 19:42:07.827|       |FixServer |Added trans id 0 mapping.
2015/04/30 19:42:07.827|       |LuaServer |LookupOrders done
2015/04/30 19:42:07.829|       |LuaServer |LookupTrades
2015/04/30 19:42:07.829|       |LuaServer |Own trades count: 19
2015/04/30 19:42:07.836|       |LuaServer |LookupTrades done
2015/04/30 19:42:07.836|       |LuaServer |Request: Type = PortfolioLookup TrId = 70920169 Value =  SecId =  OrdType =  IsSubscribe = False DataType = Level1
2015/04/30 19:42:07.838|       |LuaServer |LookupPortfolios
2015/04/30 19:42:07.861|       |LuaServer |LookupPortfolios done
2015/04/30 19:42:08.034|       |LuaServer |LookupPositions
2015/04/30 19:42:08.038|       |LuaServer |LookupPositions done
2015/04/30 19:42:09.268|       |FixServer |Connected '127.0.0.1:9869' to '0.0.0.0:5001'.
2015/04/30 19:42:09.268|       |FixServer |Received first byte from '127.0.0.1:9869'.
2015/04/30 19:42:09.268|       |FixServer |From : Logon
2015/04/30 19:42:09.268|       |FixServer |Клиент quik (127.0.0.1:9869) авторизован.
2015/04/30 19:42:09.273|       |FixServer |Отправка Logon клиенту.
2015/04/30 19:42:09.273|       |FixServer |Сессия запущена.
2015/04/30 19:42:09.573|       |FixServer |From quik 127.0.0.1:9869: SecurityListRequest
2015/04/30 19:42:09.578|       |LuaServer |Request: Type = SecurityLookup TrId = 70920170 Value =  SecId = S#:@, Native:,Type: OrdType =  IsSubscribe = False DataType = Level1
2015/04/30 19:42:09.596|       |LuaServer |LookupSecurities
2015/04/30 19:42:10.402|Error  |LuaServer |Пустой код инструмента для класса EQRP_INFO.
2015/04/30 19:42:10.417|       |LuaServer |LookupSecurities done
2015/04/30 19:43:07.992|       |FixServer |From quik 127.0.0.1:9868: TestRequest
2015/04/30 19:43:08.000|Error  |FixServer |System.ArgumentNullException: Ссылка на строку не ссылается на экземпляр String.
Имя параметра: s
   в System.Text.Encoding.GetBytes(String s)
   в StockSharp.Fix.Native.TextFixWriter.Write(String value)
   в StockSharp.Fix.Native.FixMessageWriter.#=qvr21IQpDN0fNWmWSMaNs5o6nI_yzKk5A0uJ0vbIwq_g=.#=qDnOV6h5ZsKDAX773KrR6y9q1CGn9FQojAJGC8aBGMk4=(IFixWriter #=qW0Wl$QNr6r$$WHYfWoUtBA==)
   в StockSharp.Fix.Native.FixMessageWriter.#=qOxFuPeuiQBj$x9k1ihwWp7d68BZjsc_cA48TMUsH3oM=(String #=qJEbb3y8Ghbn0noG7daJlQQ==, Action`1 #=qx5oDRqplkkNekySJcZ0paw==)
   в StockSharp.Fix.Native.FixMessageWriter.WriteHeartbeat(String requestId)
   в StockSharp.Fix.FixServer.#=qOKFQgjX75wf6Q1SotI$_UoI$VsDWznBgHwxIrwTBF7M=.#=qD5pkFmuJD5MHQHREQEMTW79v43Pp6bE4q6JFn6LmLKs=(FixMessageWriter #=qQMX9VtzOQEE7Te2GNeEogw==, String #=q6Flqv4q7rCWPJqcX10hJvA==)
   в StockSharp.Fix.FixServer.#=qZwQhnfkybKm_AfysNcmbkQ==(#=qrILpXoK52RYxA6UcNEwi7kA8dy32Nw3FcrZbUgXKE5xNmJe0$gQesgm4okFO1dW7 #=qXZR6ng8E_dF3wzJL$PLssQ==, String #=qLn7m3_kWgcko0c0KeCF5aw==, Action`2 #=q7Nl5avcHw8IwAq1QRmsfXQ==)
2015/04/30 19:43:09.607|       |FixServer |From quik 127.0.0.1:9869: TestRequest
2015/04/30 19:43:09.608|Error  |FixServer |System.ArgumentNullException: Ссылка на строку не ссылается на экземпляр String.
Имя параметра: s
   в System.Text.Encoding.GetBytes(String s)
   в StockSharp.Fix.Native.TextFixWriter.Write(String value)
   в StockSharp.Fix.Native.FixMessageWriter.#=qvr21IQpDN0fNWmWSMaNs5o6nI_yzKk5A0uJ0vbIwq_g=.#=qDnOV6h5ZsKDAX773KrR6y9q1CGn9FQojAJGC8aBGMk4=(IFixWriter #=qW0Wl$QNr6r$$WHYfWoUtBA==)
   в StockSharp.Fix.Native.FixMessageWriter.#=qOxFuPeuiQBj$x9k1ihwWp7d68BZjsc_cA48TMUsH3oM=(String #=qJEbb3y8Ghbn0noG7daJlQQ==, Action`1 #=qx5oDRqplkkNekySJcZ0paw==)
   в StockSharp.Fix.Native.FixMessageWriter.WriteHeartbeat(String requestId)
   в StockSharp.Fix.FixServer.#=qOKFQgjX75wf6Q1SotI$_UoI$VsDWznBgHwxIrwTBF7M=.#=qD5pkFmuJD5MHQHREQEMTW79v43Pp6bE4q6JFn6LmLKs=(FixMessageWriter #=qQMX9VtzOQEE7Te2GNeEogw==, String #=q6Flqv4q7rCWPJqcX10hJvA==)
   в StockSharp.Fix.FixServer.#=qZwQhnfkybKm_AfysNcmbkQ==(#=qrILpXoK52RYxA6UcNEwi7kA8dy32Nw3FcrZbUgXKE5xNmJe0$gQesgm4okFO1dW7 #=qXZR6ng8E_dF3wzJL$PLssQ==, String #=qLn7m3_kWgcko0c0KeCF5aw==, Action`2 #=q7Nl5avcHw8IwAq1QRmsfXQ==)

**Comment by mikasoukhov** [comment]
Нужно логи под Debug клиента и сервера.

Mikhail Sukhov,
StockSharp LLC, http://stocksharp.com

2015-04-30 19:48 GMT+03:00 Сергей <notifications@github.com>:

**Comment by vfreeeman** [comment]
аналогично - не вызывается NewSecurities в версиях s# 4.3.0 и s# 4.3.3, Quik 6.17.1.17

**Comment by mikasoukhov** [comment]
https://github.com/StockSharp/StockSharp/issues/64#issuecomment-97879389

**Comment by vfreeeman** [comment]
а их можно записать используя nuget-овскую установку? если можно, то как?
то, что приложил топикстартер - не то?

**Comment by mikasoukhov** [comment]
http://stocksharp.com/forum/yaf_postst5139_Nastroika-konniektora-QuikLua.aspx

**Comment by Sergey-Dvortsov** [comment]
Quik 6.17.1.17, S#4.3.0.0

Код теста:

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Threading;
using System.Net;
using System.Diagnostics;
using System.Security;
using Ecng.Common;
using Ecng.Security;

using StockSharp.Messages;
using StockSharp.Algo;
using StockSharp.Algo.Candles;
using StockSharp.Algo.Indicators;
using StockSharp.BusinessEntities;
using StockSharp.Localization;
using StockSharp.Quik;
using StockSharp.Logging;

namespace QuikCrash
{
    class Program
    {
        private static Connector trader;

        static void Main(string[] args)
        {

            trader = new QuikTrader();

            LogManager log = new LogManager();
            log.Sources.Add(trader);
            log.Listeners.Add(new FileLogListener("log.txt"));
            log.Sources.Add(trader);
            log.Listeners.Add(new DebugLogListener());

            trader.NewSecurities += securities =>
             {
                  Debug.WriteLine("NewSecurities");
             };

            trader.NewPortfolios += portfolios =>
            {
                 Debug.WriteLine("NewPortfolios");
            };


            trader.Connected += () =>
            {
                Debug.WriteLine("Соединение установлено");
            };

            trader.Disconnected += () =>
            {
                trader.Dispose();
                Debug.WriteLine("Соединение разорвано");
            };

            trader.Connect();
            Debug.WriteLine("Вызван trader.Connect()");
            Console.Read();
            trader.Disconnect();
        }

    }
}

Лог QuikTrader:

0001/01/01 00:00:00.000|       |QuikTrader|Connect
0001/01/01 00:00:00.000|       |QuikTrader|Connect
2015/05/08 12:57:57.334|Error  |QuikTrader|QuickFix.GroupDelimiterTagException: Group 753's first entry does not start with delimiter 707
   в QuickFix.Message.SetGroup(StringField grpNoFld, String msgstr, Int32 pos, FieldMap fieldMap, IGroupSpec dd, DataDictionary sessionDataDictionary, DataDictionary appDD, IMessageFactory msgFactory)
   в QuickFix.Message.FromString(String msgstr, Boolean validate, DataDictionary sessionDD, DataDictionary appDD, IMessageFactory msgFactory)
   в StockSharp.Fix.FixSession.ToMessage[T](String msgStr)
   в StockSharp.Fix.FixMessageAdapter.ProcessTransactionMessage(String fixMessage)
   в StockSharp.Quik.Lua.LuaFixTransactionMessageAdapter.ProcessTransactionMessage(String fixMessage)
   в StockSharp.Fix.FixMessageAdapter.#=qK9STqWwoUndFCKB1DRJsWO8mOCkwUesCd_CErNej0kk=()
2015/05/08 12:57:57.334|Error  |QuikTrader|QuickFix.GroupDelimiterTagException: Group 753's first entry does not start with delimiter 707
   в QuickFix.Message.SetGroup(StringField grpNoFld, String msgstr, Int32 pos, FieldMap fieldMap, IGroupSpec dd, DataDictionary sessionDataDictionary, DataDictionary appDD, IMessageFactory msgFactory)
   в QuickFix.Message.FromString(String msgstr, Boolean validate, DataDictionary sessionDD, DataDictionary appDD, IMessageFactory msgFactory)
   в StockSharp.Fix.FixSession.ToMessage[T](String msgStr)
   в StockSharp.Fix.FixMessageAdapter.ProcessTransactionMessage(String fixMessage)
   в StockSharp.Quik.Lua.LuaFixTransactionMessageAdapter.ProcessTransactionMessage(String fixMessage)
   в StockSharp.Fix.FixMessageAdapter.#=qK9STqWwoUndFCKB1DRJsWO8mOCkwUesCd_CErNej0kk=()
2015/05/08 12:57:57.351|Error  |QuikTrader|QuickFix.GroupDelimiterTagException: Group 753's first entry does not start with delimiter 707
   в QuickFix.Message.SetGroup(StringField grpNoFld, String msgstr, Int32 pos, FieldMap fieldMap, IGroupSpec dd, DataDictionary sessionDataDictionary, DataDictionary appDD, IMessageFactory msgFactory)
   в QuickFix.Message.FromString(String msgstr, Boolean validate, DataDictionary sessionDD, DataDictionary appDD, IMessageFactory msgFactory)
   в StockSharp.Fix.FixSession.ToMessage[T](String msgStr)
   в StockSharp.Fix.FixMessageAdapter.ProcessTransactionMessage(String fixMessage)
   в StockSharp.Quik.Lua.LuaFixTransactionMessageAdapter.ProcessTransactionMessage(String fixMessage)
   в StockSharp.Fix.FixMessageAdapter.#=qK9STqWwoUndFCKB1DRJsWO8mOCkwUesCd_CErNej0kk=()
2015/05/08 12:57:57.351|Error  |QuikTrader|QuickFix.GroupDelimiterTagException: Group 753's first entry does not start with delimiter 707
   в QuickFix.Message.SetGroup(StringField grpNoFld, String msgstr, Int32 pos, FieldMap fieldMap, IGroupSpec dd, DataDictionary sessionDataDictionary, DataDictionary appDD, IMessageFactory msgFactory)
   в QuickFix.Message.FromString(String msgstr, Boolean validate, DataDictionary sessionDD, DataDictionary appDD, IMessageFactory msgFactory)
   в StockSharp.Fix.FixSession.ToMessage[T](String msgStr)
   в StockSharp.Fix.FixMessageAdapter.ProcessTransactionMessage(String fixMessage)
   в StockSharp.Quik.Lua.LuaFixTransactionMessageAdapter.ProcessTransactionMessage(String fixMessage)
   в StockSharp.Fix.FixMessageAdapter.#=qK9STqWwoUndFCKB1DRJsWO8mOCkwUesCd_CErNej0kk=()
2015/05/08 12:57:57.379|       |QuikTrader|Создан новый портфель SPBFUT00FJA.
2015/05/08 12:57:57.379|       |QuikTrader|Создан новый портфель SPBFUT00FJA.
2015/05/08 12:57:57.650|       |QuikTrader|Создан новый портфель 22921.
2015/05/08 12:57:57.650|       |QuikTrader|Создан новый портфель 22921.


Лог Lua:

2015/05/08 12:57:57.068|       |FixServer |Connected '127.0.0.1:4356' to '0.0.0.0:5001'.
2015/05/08 12:57:57.136|       |FixServer |Received first byte from '127.0.0.1:4356'.
2015/05/08 12:57:57.136|       |FixServer |From : Logon
2015/05/08 12:57:57.136|       |FixServer |Клиент quik (127.0.0.1:4356) авторизован.
2015/05/08 12:57:57.139|       |FixServer |Отправка Logon клиенту.
2015/05/08 12:57:57.139|       |FixServer |Сессия запущена.
2015/05/08 12:57:57.197|       |FixServer |From quik 127.0.0.1:4356: OrderMassStatusRequest
2015/05/08 12:57:57.197|       |FixServer |From quik 127.0.0.1:4356: RequestForPositions
2015/05/08 12:57:57.198|       |LuaServer |Request: Type = OrderStatus TrId = 46674501 Value =  SecId =  OrdType =  IsSubscribe = False DataType = Level1
2015/05/08 12:57:57.198|       |LuaServer |LookupStopOrders
2015/05/08 12:57:57.198|       |LuaServer |Stop orders count: 0
2015/05/08 12:57:57.198|       |LuaServer |LookupStopOrders done
2015/05/08 12:57:57.198|       |LuaServer |LookupOrders
2015/05/08 12:57:57.198|       |LuaServer |Orders count: 0
2015/05/08 12:57:57.198|       |LuaServer |LookupOrders done
2015/05/08 12:57:57.198|       |LuaServer |LookupTrades
2015/05/08 12:57:57.198|       |LuaServer |Own trades count: 0
2015/05/08 12:57:57.198|       |LuaServer |LookupTrades done
2015/05/08 12:57:57.198|       |LuaServer |Request: Type = PortfolioLookup TrId = 46674503 Value =  SecId =  OrdType =  IsSubscribe = False DataType = Level1
2015/05/08 12:57:57.198|       |LuaServer |LookupPortfolios
2015/05/08 12:57:57.199|       |LuaServer |LookupPortfolios done
2015/05/08 12:57:57.199|       |LuaServer |LookupPositions
2015/05/08 12:57:57.202|       |LuaServer |LookupPositions done
2015/05/08 12:58:02.929|Error  |FixServer |System.IO.IOException: Не удается прочитать данные из транспортного соединения: Удаленный хост принудительно разорвал существующее подключение. ---> System.Net.Sockets.SocketException: Удаленный хост принудительно разорвал существующее подключение
   в System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   в System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- Конец трассировки внутреннего стека исключений ---
   в System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   в System.IO.Stream.ReadByte()
   в StockSharp.Fix.Native.BaseFixReader.ReadByte()
   в StockSharp.Fix.Native.TextFixReader.ReadTag()
   в #=qFPfYiHZ8Woz54XOKx_m0TnnkTniKJ9HBFOx$XdXcXIWuENEkFV3iUY_sGjBS0KVh.#=qmiqQGouxyiZRb5E6kT_TFA==(IFixReader #=qtHBJuSPbrmvJSdmY3nfX4Q==, FixTags #=qa9I3IuXYM5aIKJCoztJ51g==)
   в #=qFPfYiHZ8Woz54XOKx_m0TnnkTniKJ9HBFOx$XdXcXIWuENEkFV3iUY_sGjBS0KVh.#=qdHjwDstIHdWWlnNzkQB2kw==(IFixReader #=qcaJHkzSq3RHpd0y0wOavJQ==, Boolean #=qGSWpivhh0twoE9h12iVUjaVMui87y$iewKujV6T4eBE=, String #=qcXlON_caXV9FVA2qt0ThtfdK3aYpt10l4rOADcMtHkQ=, ILogReceiver #=qlKb2kSSVGWt8ch8_rKCZbw==, String #=quITBNEsg0PYrBl8rsaOEXg==, Func`3 #=qMlc7cEMRS_3oWKOKdmJ1Cw==, Action`1 #=q0kEjKcsql3S7aQN26xSLVA==)
2015/05/08 12:58:02.929|       |FixServer |Disconnect quik (127.0.0.1:4356)

**Comment by mikasoukhov** [comment]
Какая-то ерунда в логе. QuickFix.GroupDelimiterTagException - от QuickFix отказались месяц назад. Тоесть этой компоненты даже нет теперь в дистрибутиве. У вас точно все из одной версии?

**Comment by Sergey-Dvortsov** [comment]
Да, были референсы из старого дистрибутива... Сейчас все нормально работает...
