### ISSUE TITLE
v4.3.0 (feature) IConnector. Removed Start/Stop export

### ISSUE THREAD

**Issue by vfreeeman** [StockSharp/StockSharp#65]
Quik 6.17.1.17

StartExport убран, а как теперь инициировать экспорт?
Автоматом этого не происходит

**Comment by mikasoukhov** [comment]
https://translate.google.ru/#en/ru/issue Данный раздел сделан для репортов об ошибках. Если у вас вопрос, как что-то сделать, используйте форум/техподдержку/документацию.

Топик закрываю.
