### ISSUE TITLE
Формат хранения истории StorageFormats.Csv не работает.

### ISSUE THREAD

**Issue by OlegFedko** [StockSharp/StockSharp#68]
При сохранении вместо даты пустое значение, а при считывании исключение при парсинге даты.

Чтобы воспроизвести достаточно в **\Samples\Common\SampleStorage\Program.cs** добавить
```cs
var tradeStorage = storage.GetTradeStorage(security, format: StorageFormats.Csv);
```

Какая-то магия сериализатора Ecng не работает, чей код отсутствует.

PS Также замечу, что в *SampleStorage* по факту удаляются не все данные. Какая-то проблема с часовыми поясами.

**Comment by mikasoukhov** [comment]
Какая версия?

**Comment by OlegFedko** [comment]
4.2.75

**Comment by mikasoukhov** [comment]
Посмотрите на последней версии. Эта версия у меня не сохранилась.

**Comment by OlegFedko** [comment]
На 4.3.3 проблемы с CSV нет.
Проблема с тем, что не все данные удалены сохранилась.
