### ISSUE TITLE
FixServer System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by vfreeeman** [StockSharp/StockSharp#69]
Примерно через 30 минут работы приложения в лог валятся одни и те же сообщения об ошибке.
При этом события по изменениям стаканов и новым сделкам не вызываются.

Quik 6.17.1.17, lua, S# 4.2.75 (nuget)

2015/05/05 11:07:09.618|Error  |FixServer |System.ArgumentOutOfRangeException: Заданный аргумент находится вне диапазона допустимых значений.
Имя параметра: value
   в StockSharp.Fix.Native.FixBase.set_CheckSum(Int32 value)
   в StockSharp.Fix.Native.BaseFixWriter.WriteByte(Byte value)
   в StockSharp.Fix.Native.TextFixWriter.#=qPOHyoWrEQVSRUPJe2KXOJg==(Int64 #=qEjh5jFLxkeuJopk4g$gGVg==)
   в StockSharp.Fix.Native.TextFixWriter.Write(FixTags tag)
   в StockSharp.Fix.Native.FixMessageWriter.#=qKfz5t4OSETxM6cV7JCV9dJDcdcUPVpCtRvOHAtIVm8Y=(String #=qJt3v_mdqbC4Uix8TJ07Mew==, Action`1 #=qpG4UJDY2qzbCSjQ10a$Cfg==)
   в StockSharp.Fix.FixServer.#=qlSu0L306Twxrco_4AL$T0Z$nS4AvCby7hcSNjOdwUeM=.#=qdXKaCmZAvLzmhSscBmJ25jinBIq_27xDGk5oMjq9pNc=(FixMessageWriter #=qqtqqrUHhWcdr$xNrcAi8yA==, String #=qAHtG9QKtsv5dV1zVZORDMA==)
   в StockSharp.Fix.FixServer.#=qx$WTxIummwZ0pR30krYFYQ==(#=qQJjLeLS$zbkA7JkFgiQY0fNH1xCFRd5Hr3sXT$H9nyoz7eJVI8eTowHrAPqGGwm2 #=qzBXp6HUEcEUjKeoAEQL3dg==, String #=qqqjIRmEDfraIEGH$W_ATYA==, Action`2 #=qsSiMfFCwFGpagGRTR4ojxg==)

**Comment by mikasoukhov** [comment]
Надо проверить на последней версии.

**Comment by RomSunZ** [comment]
версия 4.3.2:
2015/05/05 20:29:52.211|Error  |FixServer |System.ArgumentOutOfRangeException: Заданный аргумент находится вне диапазона допустимых значений.
Имя параметра: value
   в StockSharp.Fix.Native.FixBase.set_CheckSum(Int32 value)
   в StockSharp.Fix.Native.BaseFixWriter.WriteBytes(Byte[] bytes)
   в StockSharp.Fix.Native.TextFixWriter.Write(String value)
   в StockSharp.Fix.Native.FixMessageWriter.#=qG3KdHpAP1pbfvCb3fgjAJakNy0ymjzHzuqTkbr8oV1w=(String #=qQuNqhDFl4__XOxaXZoYCQw==, Action`1 #=qbfNPREvhu3y9Y$Kg73G_hg==)
   в StockSharp.Fix.FixServer.#=qNK7iu4Sm4dv0lELVQDheYpmv4oy8k9oDyvNyh5axYWE=.#=qPmageDEmocX4yYTV6$3HRVdinNRq0Vw6YSFcJio6Vw4=(FixMessageWriter #=q7p$$Rm0mjMVoqBt6wEESxQ==, String #=qKIIWftJ4rny27D2ueUuXrg==)
   в StockSharp.Fix.FixServer.#=qS1o74dF$BTNZ16WvgAOoRg==(#=qIYh8GaiXjmlMYcGMAIDzdU2q3qnOil3Wr8DtMCz8cxYrFzv_a5GIyH2_mssF3kMe #=qiFCD0f7wDiH$rRj9a4CBuw==, String #=qtsLJpgioexYlanOriakoDg==, Action`2 #=qM6BdD$1eIjl7n2lPOPI2sw==)

**Comment by mikasoukhov** [comment]
Дебаг лог клиента и сервера за этот промежуток времени.

**Comment by RomSunZ** [comment]
В клиенте пусто, ошибок и записей нет, т.к. после появления этой ошибки в логе сервера - сервер отваливается.

**Comment by mikasoukhov** [comment]
Можете прислать полный лог? Как файл.

**Comment by vfreeeman** [comment]
я могу прислать. а куда отправить?

**Comment by RomSunZ** [comment]
На форуме стокшарпа выложи, а здесь ссылку оставь

**Comment by mikasoukhov** [comment]
Напомню, что лог файлы клиента и сервера должны быть под Debug уровнем. Это ключевое.

**Comment by vfreeeman** [comment]
"лог сервера" == StockSharp.QuikLua.log, как там Debug уровень включить понятно
а что такое "лог клиента"? и как у него уровень Debug включить?
подскажите, плз.

**Comment by mikasoukhov** [comment]
Посмотрите документацию про логирование
09.05.2015 16:08 пользователь "vfreeeman" <notifications@github.com>
написал:
