### ISSUE TITLE
Методы Connector.UnRegister.... не останавливают получение информации

### ISSUE THREAD

**Issue by Sergey-Dvortsov** [stocksharp/stocksharp#7]
Версии S# 4.2.43.0, 4.2.55.0
Терминал QUIK 6.16.0.42 Lua 

1. Вызов методов connector.UnRegisterSecurity, connector.UnRegisterMarketDepth, connector.UnRegisterTrades, connector.UnSubscribeMarketData не останавливает поступление информации в соответствующих событиях.
2. Если после вызова connector.UnRegisterSecurity для одного инструмента, попытаться зарегистрировать (connector.RegisterSecurity) другой инструмент, то информация по второму инструменту не поступает.

Код теста:

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using StockSharp.Algo;
using StockSharp.BusinessEntities;
using StockSharp.Quik;
using StockSharp.Messages;
using System.Threading;

namespace ConnectorRegister
{
    class Program
    {

        private static Security lkoh;
        private static Security sber;

        static void Main(string[] args)
        {
            var autoreset = new AutoResetEvent(false);

            var connector = new QuikTrader(QuikTerminal.GetDefaultPath());
            connector.Connected += () => connector.StartExport();
            connector.NewSecurities += securties => 
                                        {
                                            foreach (var sec in securties)
                                            {
                                                if (sec.Code == "SBER") sber = sec;
                                                if (sec.Code == "LKOH") lkoh = sec;
                                                if (lkoh != null && sber != null)
                                                {
                                                    autoreset.Set();
                                                }
                                            }
                                        };

            connector.Connect();

            connector.ValuesChanged += connector_ValuesChanged;
            connector.SecuritiesChanged += connector_SecuritiesChanged;
            connector.MarketDepthsChanged += connector_MarketDepthsChanged;
            connector.NewTrades += connector_NewTrades;

            autoreset.WaitOne();

            Console.WriteLine("RegisterSecurity SBER");
            connector.RegisterSecurity(sber);

            //Console.WriteLine("RegisterSecurity LKOH");
            //connector.RegisterSecurity(lkoh);

            //Console.WriteLine("RegisterMarketDepth SBER");
            //connector.RegisterMarketDepth(sber);

            //Console.WriteLine("RegisterTrades SBER");
            //connector.RegisterTrades(sber);

            Console.ReadLine();

            Console.WriteLine("UnRegisterSecurity SBER");
            connector.UnRegisterSecurity(sber);

            //Console.WriteLine("RegisterSecurity LKOH");
            //connector.RegisterSecurity(lkoh);

            //Console.WriteLine("UnRegisterMarketDepth SBER");
            //connector.UnRegisterMarketDepth(sber);

            //Console.WriteLine("UnRegisterTrades SBER");
            //Console.WriteLine("-------------------------");
            //connector.UnRegisterTrades(sber);

            //

            //connector.UnSubscribeMarketData(sber, MarketDataTypes.MarketDepth);

            Console.ReadLine();
            

        }

        private static void connector_SecuritiesChanged(IEnumerable<Security> obj)
        {
            Console.WriteLine("SecuritiesChanged: {0}", obj.FirstOrDefault<Security>().Code);
        }

        private static void connector_MarketDepthsChanged(IEnumerable<MarketDepth> obj)
        {
            Console.WriteLine("MarketDepthsChanged: {0}", obj.FirstOrDefault<MarketDepth>().Security.Code);
        }

        private static void connector_NewTrades(IEnumerable<Trade> obj)
        {
            Console.WriteLine("NewTrades: {0}", obj.FirstOrDefault<Trade>().Security.Code);
        }

        private static void connector_ValuesChanged(Security security, IEnumerable<KeyValuePair<Level1Fields, object>> fields, DateTimeOffset timeOffset, DateTime time)
        {
            Console.WriteLine("ValuesChanged: {0}", security.Code);
        }

    }
}

**Comment by mikasoukhov** [comment]
https://github.com/stocksharp/stocksharp/commit/63ea6e131fc501d5d54ca7c2d7d8f253f8a1f64f
