### ISSUE TITLE
Котирование

### ISSUE THREAD

**Issue by MozGangster** [stocksharp/stocksharp#8]
При использовании котирования, при перестановке заявки на покупку на повышение в Квике появляется сообщение "Количество в заявке должно быть положительное"
Более подробно и лог http://stocksharp.com/forum/yaf_postsm34413_Kotirovaniie.aspx#post34413

**Comment by mikasoukhov** [comment]
Не является ошибкой, так как Квик не поддерживает атомарную перерегистрацию на ММВБ.
