### ISSUE TITLE
Ошибка в Гидре при склеивании данныз 

### ISSUE THREAD

**Issue by Sergey-Dvortsov** [StockSharp/StockSharp#85]
Hydra 4.3.2.0

При выборе инструмента для склеивания возникает "Ошибка обработки запроса обновления таблицы"

22:45:39.154|Error  |S#.Data (Hydra)|System.InvalidOperationException: Ошибка обработки запроса обновления таблицы. ---> System.InvalidCastException: Cannot convert StockSharp.Algo.Candles.TimeFrameCandleMessage, StockSharp.Algo, Version=4.3.2.0, Culture=neutral, PublicKeyToken=null to System.Type. ---> System.ArgumentException: Type StockSharp.Algo.Candles.TimeFrameCandleMessage, StockSharp.Algo, Version=4.3.2.0, Culture=neutral, PublicKeyToken=null doesn't exists.
Имя параметра: value
   в Ecng.Common.Converter.To(Object value, Type destinationType)
   --- Конец трассировки внутреннего стека исключений ---
   в Ecng.Common.Converter.To(Object value, Type destinationType)
   в Ecng.Common.Converter.To[T](Object value)
   в StockSharp.Algo.Storages.LocalMarketDataDrive.<GetCandleTypes>b__4(String fileName)
   в System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   в System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   в System.Linq.GroupedEnumerable`3.GetEnumerator()
   в System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   в System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   в System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   в StockSharp.Algo.Storages.LocalMarketDataDrive.GetCandleTypes(SecurityId securityId, StorageFormats format)
   в StockSharp.Xaml.MarketDataGrid.Process(IStorageRegistry storageRegistry, Security security, StorageFormats format, IMarketDataDrive drive)
   в StockSharp.Xaml.MarketDataGrid.OnFlush()
   --- Конец трассировки внутреннего стека исключений ---

![fut_glue](https://cloud.githubusercontent.com/assets/10364235/7597285/1b3e1476-f8fb-11e4-8bca-8b18c773628f.png)

**Comment by mikasoukhov** [comment]
Ошибка воспроизводится на последней версии из Гита?

**Comment by Sergey-Dvortsov** [comment]
Да..

**Comment by mikasoukhov** [comment]
Последняя версия гидры, которая собрана из исходников на ГитХабе.

**Comment by Sergey-Dvortsov** [comment]
Да, версия собрана из исходников s# 4.3.4.0 + добавлены fix#79 и fix#83

**Comment by mikasoukhov** [comment]
У исходников нет версий. Есть последняя версия или по какой-то коммит. Так же не понятно как можно к исходникам что-то добавлять.

Нужно перекомпилировать Гидру с нуля. На последних исходных кодах.

**Comment by Sergey-Dvortsov** [comment]
На самых последних у меня не получается собрать: ошибку с лицензией Actipro получаю..

**Comment by mikasoukhov** [comment]
Тогда так и пишите. Не нужно вводить в заблуждения, что вы проверили на последних исходных кодах.

**Comment by Sergey-Dvortsov** [comment]
С версией Гидры  4.3.5.0 ошибка сохраняется

**Comment by mikasoukhov** [comment]
Вы же не можете перекомпилировать. С чего вы взяли что она есть в неопубликованной версии?

**Comment by Sergey-Dvortsov** [comment]
Почему, гидра из S#  4.3.5.0 компилируется

**Comment by mikasoukhov** [comment]
Как вы можете скомпилировать, если у вас ошибка лицензии https://github.com/StockSharp/StockSharp/issues/85#issuecomment-101736509

**Comment by Sergey-Dvortsov** [comment]
![hydra](https://cloud.githubusercontent.com/assets/10364235/7660389/26d62946-fb52-11e4-8b83-e170e97ac2d7.png)

**Comment by mikasoukhov** [comment]
На картинке видно, что ошибка теперь другая.

**Comment by Sergey-Dvortsov** [comment]
22:28:21.553|Error  |S#.Data (Hydra)|System.InvalidOperationException: Ошибка обработки запроса обновления таблицы. ---> System.InvalidCastException: Cannot convert StockSharp.Messages.TimeFrameCandleMessageMessage, StockSharp.Messages, Version=4.3.5.0, Culture=neutral, PublicKeyToken=null to System.Type. ---> System.ArgumentException: Type StockSharp.Messages.TimeFrameCandleMessageMessage, StockSharp.Messages, Version=4.3.5.0, Culture=neutral, PublicKeyToken=null doesn't exists.
Имя параметра: value
   в Ecng.Common.Converter.To(Object value, Type destinationType)
   --- Конец трассировки внутреннего стека исключений ---
   в Ecng.Common.Converter.To(Object value, Type destinationType)
   в Ecng.Common.Converter.To[T](Object value)
   в StockSharp.Algo.Storages.LocalMarketDataDrive.<GetCandleTypes>b__4(String fileName)
   в System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   в System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   в System.Linq.GroupedEnumerable`3.GetEnumerator()
   в System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   в System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   в System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   в StockSharp.Algo.Storages.LocalMarketDataDrive.GetCandleTypes(SecurityId securityId, StorageFormats format)
   в StockSharp.Xaml.MarketDataGrid.Process(IStorageRegistry storageRegistry, Security security, StorageFormats format, IMarketDataDrive drive)
   в StockSharp.Xaml.MarketDataGrid.OnFlush()
   --- Конец трассировки внутреннего стека исключений ---
   в StockSharp.Xaml.MarketDataGrid.<>c__DisplayClassa.<OnFlush>b__7()
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by mikasoukhov** [comment]
На диске лежат файлы с названием candles_TimeFrameCandleMessage_xxx Эти файлы созданы по всемй видимости ошибочной версией. Удалите их, и заново закачайте.
