### ISSUE TITLE
Ошибка в Гидре при запуске Quik

### ISSUE THREAD

**Issue by Sergey-Dvortsov** [StockSharp/StockSharp#90]
Hydra 4.3,5,0, Quik 6.17.1.17 

Возникает ошибка в Гидре при запуске источника Quik

Лог Гидры:
22:00:47.242|       |Quik      |Инициализируется.
22:00:47.250|       |Quik      |Перешел в состояние Starting.
00:00:00.000|       |QuikTrader|Connect
22:00:48.085|Error  |Quik      |System.ArgumentOutOfRangeException: Заданный аргумент находится вне диапазона допустимых значений.
Имя параметра: version
   в #=qqFaVLCaFrw3RUZSNlX3v6GpGMnxDJsndfEbP_W1bA4DycGT0_t5raYDZaHYJDOzd.#=qB2bPxjlkXvuJKsyQR6B6_Q==(FixVersions #=qqvCWSbVyVHeYfptiGu78vw==)
   в StockSharp.Fix.Native.FixMessageWriter..ctor(IFixWriter writer, FixVersions version, FixFormats format, IncrementalIdGenerator idGenerator, String senderCompId, String targetCompId)
   в StockSharp.Fix.FixMessageAdapter.#=qdhzXEj2GsD2znfZSdnnk3g==(Int64 #=qNfeTiAdXt3ZLE23dflnmMg==)
   в StockSharp.Fix.FixMessageAdapter.OnSendInMessage(Message message)
   в StockSharp.Messages.MessageAdapter.SendInMessage(Message message)
22:00:48.085|       |Quik      |Перешел в состояние Stopping.
22:00:48.110|       |Quik      |Перешел в состояние Stopped.
22:01:16.090|       |Quik      |Инициализируется.
22:01:16.096|       |Quik      |Перешел в состояние Starting.
22:01:16.169|Error  |Quik      |System.ArgumentOutOfRangeException: Заданный аргумент находится вне диапазона допустимых значений.
Имя параметра: version
   в #=qqFaVLCaFrw3RUZSNlX3v6GpGMnxDJsndfEbP_W1bA4DycGT0_t5raYDZaHYJDOzd.#=qB2bPxjlkXvuJKsyQR6B6_Q==(FixVersions #=qqvCWSbVyVHeYfptiGu78vw==)
   в StockSharp.Fix.Native.FixMessageWriter..ctor(IFixWriter writer, FixVersions version, FixFormats format, IncrementalIdGenerator idGenerator, String senderCompId, String targetCompId)
   в StockSharp.Fix.FixMessageAdapter.#=qdhzXEj2GsD2znfZSdnnk3g==(Int64 #=qNfeTiAdXt3ZLE23dflnmMg==)
   в StockSharp.Fix.FixMessageAdapter.OnSendInMessage(Message message)
   в StockSharp.Messages.MessageAdapter.SendInMessage(Message message)
22:01:16.169|       |Quik      |Перешел в состояние Stopping.
22:01:16.169|       |Quik      |Перешел в состояние Stopped.
22:02:17.435|       |Quik      |Инициализируется.
22:02:17.443|       |Quik      |Перешел в состояние Starting.
22:02:17.520|Error  |Quik      |System.ArgumentOutOfRangeException: Заданный аргумент находится вне диапазона допустимых значений.
Имя параметра: version
   в #=qqFaVLCaFrw3RUZSNlX3v6GpGMnxDJsndfEbP_W1bA4DycGT0_t5raYDZaHYJDOzd.#=qB2bPxjlkXvuJKsyQR6B6_Q==(FixVersions #=qqvCWSbVyVHeYfptiGu78vw==)
   в StockSharp.Fix.Native.FixMessageWriter..ctor(IFixWriter writer, FixVersions version, FixFormats format, IncrementalIdGenerator idGenerator, String senderCompId, String targetCompId)
   в StockSharp.Fix.FixMessageAdapter.#=qdhzXEj2GsD2znfZSdnnk3g==(Int64 #=qNfeTiAdXt3ZLE23dflnmMg==)
   в StockSharp.Fix.FixMessageAdapter.OnSendInMessage(Message message)
   в StockSharp.Messages.MessageAdapter.SendInMessage(Message message)
22:02:17.520|       |Quik      |Перешел в состояние Stopping.
22:02:17.526|       |Quik      |Перешел в состояние Stopped.
22:04:42.192|       |Quik      |Инициализируется.
22:04:42.205|       |Quik      |Перешел в состояние Starting.
22:04:42.473|Error  |Quik      |System.ArgumentOutOfRangeException: Заданный аргумент находится вне диапазона допустимых значений.
Имя параметра: version
   в #=qqFaVLCaFrw3RUZSNlX3v6GpGMnxDJsndfEbP_W1bA4DycGT0_t5raYDZaHYJDOzd.#=qB2bPxjlkXvuJKsyQR6B6_Q==(FixVersions #=qqvCWSbVyVHeYfptiGu78vw==)
   в StockSharp.Fix.Native.FixMessageWriter..ctor(IFixWriter writer, FixVersions version, FixFormats format, IncrementalIdGenerator idGenerator, String senderCompId, String targetCompId)
   в StockSharp.Fix.FixMessageAdapter.#=qdhzXEj2GsD2znfZSdnnk3g==(Int64 #=qNfeTiAdXt3ZLE23dflnmMg==)
   в StockSharp.Fix.FixMessageAdapter.OnSendInMessage(Message message)
   в StockSharp.Messages.MessageAdapter.SendInMessage(Message message)
22:04:42.473|       |Quik      |Перешел в состояние Stopping.
22:04:42.500|       |Quik      |Перешел в состояние Stopped.

Lua
2015/05/15 22:02:39.415|       |LuaServer |OnInit
2015/05/15 22:02:39.433|       |FixServer |Server 0.0.0.0:5001 started.
2015/05/15 22:02:39.434|       |FixServer |FixServer started.
2015/05/15 22:02:39.435|       |LuaServer |OnInit done
2015/05/15 22:02:39.452|       |LuaServer |Main
2015/05/15 22:04:42.444|       |FixServer |Connected '127.0.0.1:5065' to '0.0.0.0:5001'.
2015/05/15 22:04:42.449|       |FixServer |Connected '127.0.0.1:5066' to '0.0.0.0:5001'.

**Comment by mikasoukhov** [comment]
https://github.com/StockSharp/StockSharp/commit/2d61ea649f5bf3f70d3a329de52758e1d187f424
