### ISSUE TITLE
Склеивание данных Hydra 4.3.6.0

### ISSUE THREAD

**Issue by Sergey-Dvortsov** [StockSharp/StockSharp#94]
Hydra Version=4.3.6.0

13:09:32.355|Error  |S#.Data (Hydra)|System.InvalidOperationException: Ошибка обработки запроса обновления таблицы. ---> System.InvalidCastException: Cannot convert StockSharp.Messages.TimeFrameCandleMessageMessage, StockSharp.Messages, Version=4.3.6.0, Culture=neutral, PublicKeyToken=null to System.Type. ---> System.ArgumentException: Type StockSharp.Messages.TimeFrameCandleMessageMessage, StockSharp.Messages, Version=4.3.6.0, Culture=neutral, PublicKeyToken=null doesn't exists.
Имя параметра: value
   в Ecng.Common.Converter.To(Object value, Type destinationType)
   --- Конец трассировки внутреннего стека исключений ---
   в Ecng.Common.Converter.To(Object value, Type destinationType)
   в Ecng.Common.Converter.To[T](Object value)
   в StockSharp.Algo.Storages.LocalMarketDataDrive.<GetCandleTypes>b__4(String fileName)
   в System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   в System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   в System.Linq.GroupedEnumerable`3.GetEnumerator()
   в System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   в System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   в System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   в StockSharp.Algo.Storages.LocalMarketDataDrive.GetCandleTypes(SecurityId securityId, StorageFormats format)
   в StockSharp.Xaml.MarketDataGrid.Process(IStorageRegistry storageRegistry, Security security, StorageFormats format, IMarketDataDrive drive)
   в StockSharp.Xaml.MarketDataGrid.OnFlush()
   --- Конец трассировки внутреннего стека исключений ---
   в StockSharp.Xaml.MarketDataGrid.<>c__DisplayClassa.<OnFlush>b__7()
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by mikasoukhov** [comment]
https://github.com/StockSharp/StockSharp/issues/85
