### ISSUE TITLE
S# 4.3.6 не вызывается событие WhenStopped в дочерних стратегиях

### ISSUE THREAD

**Issue by RomSunZ** [StockSharp/StockSharp#97]
Периодически в дочерних стратегиях при остановке перестают завершаться правила, из-за чего перестает вызываться событие WhenStopped, и стратегии "зависают" со статусом "stopping".
Ссылка на лог из примера quik SampleSMA:
http://stocksharp.com/forum/yaf_postst5640_S--4-3-6-nie-vyzyvaietsia-sobytiie-WhenStopped-v-dochiernikh-stratieghiiakh.aspx

**Comment by mironovpro** [comment]
Подтверждаю. Такая же ситуация и для InterectiveBrokers. Причем зависают только стратегии со стоп заявками. OrderTypes.Conditional. так же из-за не завершенных правил.

**Comment by mikasoukhov** [comment]
В данном случае ошибку придется устранять самостоятельно, так как не стоит в планах разработки на этот год.

**Comment by RomSunZ** [comment]
Не собираетесь в этом году закрывать проблему, а зачем удалили из багов?

**Comment by mikasoukhov** [comment]
Потому что этот раздел сделан для разработчиков. Ваша ошибка касается только вас, и она мешает в трекинге нужных сообщений. Вы можете писать про ошибки в своем личном репозитарии. Как это делать - смотрите документацию https://help.github.com/

**Comment by RomSunZ** [comment]
Михаил, я вами поражаюсь.
Этот баг меня вообще не касается, он касается пользователей вашего проекта, и знать про баг должны пользователи в том числе, а не только разработчики.

**Comment by mikasoukhov** [comment]
Объясняю еще раз. Этот раздел НЕ для пользователей, а для разработчиков.

**Comment by RomSunZ** [comment]
1. Адекватные пользователи в первую очередь просматривают какие баги присутствуют
2. Вы сделали проект стокшарпа с открытым исходным кодом, это значит, что не только вы, но и кто-нибудь другой может найти решение данной конкретной проблемы, но переместив проблему в раздел закрытых вы не будете ее решать, и другие тоже. Это мое мнение.
3. Вообще не понимаю, каким образом "она мешает в трекинге нужных сообщений", если тупо висит в нерешенных проблемах. Глаз мозолит?

**Comment by mikasoukhov** [comment]
Потому что это раздел для разработчиков. И здесь пишутся только актуальные ошибки (от клиентов). Если вы хотите вести ошибки, касающиеся только вас, вы можете это делать в своем личном баг трекере.

**Comment by RomSunZ** [comment]
Михаил, с чего вы взяли что эта ошибка касается только меня???  Как кто-то писал на сайте - начните уже пользоваться своим продуктом! Ошибка проявляется не в моем личном роботе с моим личным кодом, а в ВАШЕМ же примере! Следовательно ошибка в ВАШЕМ коде, а не моем, и касается она ВСЕХ, кто пользуется ВАШЕЙ библиотекой! И прочитайте пункт 2 чуть выше ЕЩЕ раз.

**Comment by RomSunZ** [comment]
Вот опять повторяется ситуация для меня не понятная как и с неправильным стаканом quikLUA. Там вы тоже отмахивались подобными фразами, пока вас носом не ткнул...

**Comment by mironovpro** [comment]
Если я не ошибаюсь, эта ошибка из базового функционала. Без которого не возможна работа со стратегиями. 
Прошу прощения, но будет странно отложить её фикс на следующий год.

**Comment by mikasoukhov** [comment]
http://stocksharp.com/news/10454-ishodnyi-kod-s-na-github последие 2 абзаца. Дело не в том, что вы не можете продолжить или нет, а в том, что мы реагирует только на запросы клиентов. Клиенты пока по данной ошибке не сообщали (если ошибка вообще есть). Выше RomSunZ привел пример с Lua. Он свою ошибку написал за месяц до фикса. Работа пошла только тогда, когда написал клиент. Поэтому так просто совпало.

Или самостоятельно исправляйте, или ждите клиентов, или сами становитесь клиентами, или делайте бранч и ведите проект своими силами. Вариантов море. Не понимаю, почему вы так настаиваете на самом маловерятном варианте - что это сделает кто-то другой.

**Comment by RomSunZ** [comment]
1. Михаил, напишите на сайте на главной странице о том, что вы не собираетесь рассматривать баги, о которых пишут пользователи, которые не платят вам деньги, и напишите то же самое в соглашение об использовании вашего продукта. Сделайте это чтобы ни я, ни подобные мне люди не теряли время на бесполезный срач, логи и прочую лабуду.
2. Вот именно из-за такого отношения (если денег не платишь - значит баги, выявленные тобой - это не баги, а "сам дурак" - я и не собираюсь платить вам деньги и становиться вашим клиентом.
3. Именно из-за такого отношения ваш форум мертв, и проект как-то не особо развивается.
4. Я нигде ни в одной фразе не настаивал на том, что кто-то сдеалет что-то для меня, я писал о том, что коль проект стал опенсорс, то предполагается участие большого количества пользователей. Кто-то пишет про баги или улучшения, кто-то предлагает решения, за счет чего проект развивается. Если у вас другое видение, то какого лешего вы сначала открываете код, а потом пишите, что баги принимаются только от платных пользователей и описание багов от прочих пользователей не рассматриваются и не принимаются? Какой смысл в этом для опенсорс проекта? Зачем еще плодить какие-то бранчи и ветви? Проект один есть, зачем еще что-то плодить, если можно довести до ума то, что есть? Ну не собираетесь вы решать какой-то баг - да и нехай с вами, найдутся другие, для кого этот баг критичен и они найдут решение, но зачем закрывать не решенную проблему, пусть ее написал не ваш клиент, но пользователь ВАШЕГО проекта? Логики - ноль.

**Comment by mikasoukhov** [comment]
1. Ссылка, что я привел, идет с главной странице сайта. Дополнительная информация что именно размещать будет определятся нами, а не пользователями.

2. Это ваше право.

3. Это ваше мнение.

4. Ваше мнение - это ваше мнение. Я привел достаточно информации. Если вы будете дальше устраивать скандалы, к сожалению, мне придется вас заблокировать.
