### ISSUE TITLE
Не получается подключиться к CQG

### ISSUE THREAD

**Issue by goodvin** [StockSharp/StockSharp#98]
1. Установил CQG FX (CQG 2015). Проверил, что логин и пароль верные, CQG FX работает.
2. Запускаю SampleCQG, ввожу логин и пароль, жму "Подключиться".
3. В лог выводится единственное сообщение "Connect".
4. Больше ничего не происходит (ждал больше 10 минут), все кнопки остаются недоступными.

Без установки CQG FX сразу же появлялось исключение о том, что COM-компонент не найден.
Проверял версии S# 4.3.6 и 4.2.66 - в обеих результат одинаковый.

**Comment by mikasoukhov** [comment]
Исходники коннектора CQG доступны.
